// Qwik/src/components/bd/Subscribe.tsx
import { $, component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";

/**
 * Newsletter signup wired to BD followers. The same component powers the
 * footer and the about-section signups (mirrors the DGP `SubscribeStub`).
 *
 * Browser-safe by design: it joins via a PUBLISHABLE token (`pk_…`,
 * origin-locked, scope `followers:self`) using the core `createBdClient`
 * inside a `$` handler — no backend round-trip needed. The publishable token,
 * site id, and optional base URL come from Qwik City's `PUBLIC_`-prefixed env,
 * read through `import.meta.env` so they're available client-side.
 *
 * When the publishable env isn't set the component degrades to a "coming soon"
 * placeholder so the template still runs in an unconfigured checkout.
 *
 * "Already subscribed" hint:
 *   - Anonymous → a per-browser flag in `localStorage` under
 *     `bd.followers.<siteId>` (`{ email, at }`), set after a successful join
 *     and read on mount. This mirrors what `useFollowers` does internally.
 *   - Logged-in → the authoritative source is `client.followers.me(email)`
 *     (cross-device); a starter footer/about signup stays anonymous, so the
 *     localStorage flag is the UX source of truth here. IP is deliberately NOT
 *     used.
 */

// Publishable BD credentials — browser-exposed via `import.meta.env`. Prefer
// the canonical `PUBLIC_BD_*` names (Vite envPrefix), falling back to the
// starter's original `PUBLIC_BD_*` names. Unset → placeholder mode (the page
// never breaks).
const BD_PK =
	(import.meta.env.PUBLIC_BD_PK as string | undefined) ??
	(import.meta.env.PUBLIC_BD_PK as string | undefined);
const BD_SITE_ID =
	(import.meta.env.PUBLIC_BD_SITE_ID as string | undefined) ??
	(import.meta.env.PUBLIC_BD_SITE_ID as string | undefined);
const BD_BASE_URL =
	(import.meta.env.PUBLIC_BD_PACKAGE_API_BASE_URL as
		| string
		| undefined) ??
	(import.meta.env.PUBLIC_BD_PACKAGE_API_BASE_URL as string | undefined);
const BD_FOLLOWERS_ENABLED = Boolean(BD_PK && BD_SITE_ID);

const FOLLOWER_STORE_PREFIX = "bd.followers.";

/** Per-browser "already subscribed?" hint — true once this browser has joined. */
function hasLocalFollow(siteId: string): boolean {
	if (typeof window === "undefined") return false;
	try {
		const raw = window.localStorage.getItem(`${FOLLOWER_STORE_PREFIX}${siteId}`);
		if (!raw) return false;
		const parsed = JSON.parse(raw) as { email?: unknown };
		return typeof parsed?.email === "string";
	} catch {
		return false;
	}
}

/** Remember the join on this browser (best-effort — storage may be disabled). */
function writeLocalFollow(siteId: string, email: string): void {
	if (typeof window === "undefined") return;
	try {
		window.localStorage.setItem(
			`${FOLLOWER_STORE_PREFIX}${siteId}`,
			JSON.stringify({ email, at: Date.now() }),
		);
	} catch {
		// quota / disabled — the hint is best-effort.
	}
}

export type SubscribeProps = {
	/** Visible field label. */
	label: string;
	/** Email input placeholder. */
	placeholder?: string;
	/** Submit button copy. */
	buttonLabel?: string;
	/** Lead-source provenance forwarded to `followers.join`. */
	source?: string;
	/** Extra class on the wrapper. */
	class?: string;
};

export const Subscribe = component$<SubscribeProps>((props) => {
	const {
		label,
		placeholder = "you@example.com",
		buttonLabel = "Subscribe",
		source = "subscribe",
	} = props;

	const status = useSignal<"idle" | "submitting" | "done" | "error">("idle");
	const subscribedLocally = useSignal(false);

	// Read the per-browser hint on mount (client-only — localStorage isn't on
	// the server). Skips straight to the "subscribed" state for repeat visitors.
	useVisibleTask$(() => {
		if (BD_SITE_ID && hasLocalFollow(BD_SITE_ID)) {
			subscribedLocally.value = true;
		}
	});

	const onSubmit$ = $(async (event: SubmitEvent) => {
		event.preventDefault();
		const form = event.target as HTMLFormElement;
		const email = String(new FormData(form).get("email") ?? "").trim();
		if (!email) return;

		// Placeholder mode — no publishable token, so just confirm locally.
		if (!BD_FOLLOWERS_ENABLED) {
			status.value = "done";
			return;
		}

		status.value = "submitting";
		try {
			// Lazy-load the core client client-side so it never bloats the SSR
			// path; the publishable token is safe in the browser bundle.
			const { createBdClient } = await import("@businessdash/sdk");
			const client = createBdClient({
				apiKey: BD_PK as string,
				siteId: BD_SITE_ID as string,
				...(BD_BASE_URL ? { baseUrl: BD_BASE_URL } : {}),
			});
			await client.followers.join({ email, source });
			writeLocalFollow(BD_SITE_ID as string, email);
			status.value = "done";
		} catch {
			status.value = "error";
		}
	});

	// Already-subscribed (this browser) or a fresh success → confirmation copy.
	if (subscribedLocally.value || status.value === "done") {
		return (
			<p class={`bd-subscribe__note ${props.class ?? ""}`.trim()}>
				{BD_FOLLOWERS_ENABLED
					? "You're subscribed — thanks!"
					: "Thanks — newsletter signup is coming soon."}
			</p>
		);
	}

	const disabled = status.value === "submitting";

	return (
		<div class={props.class}>
			<form class="bd-subscribe" preventdefault:submit onSubmit$={onSubmit$}>
				<label class="bd-label" for={`${source}-email`}>
					{label}
				</label>
				<div class="bd-subscribe__row">
					<input
						autoComplete="email"
						class="bd-input"
						disabled={disabled}
						id={`${source}-email`}
						name="email"
						placeholder={placeholder}
						required
						type="email"
					/>
					<button class="bd-btn" disabled={disabled} type="submit">
						{disabled ? "Sending…" : buttonLabel}
					</button>
				</div>
			</form>
			{status.value === "error" ? (
				<p class="bd-subscribe__error">
					Couldn't subscribe — please try again.
				</p>
			) : null}
		</div>
	);
});

// Tanstack-Start-Solid/solid/src/components/bd/Subscribe.tsx
import { createBdClient } from "@businessdash/sdk";
import { createMemo, createSignal, onMount, Show } from "solid-js";

/**
 * Newsletter signup wired to BD followers.
 *
 * Browser-safe by design: it runs on a BD *publishable* token (origin-locked,
 * rate-limited, `followers:self` only) — never the server-side secret key. The
 * three browser-exposed env vars are the same trio the analytics tracker uses
 * in `__root.tsx`: the canonical `VITE_BD_*` names (exposed to the
 * bundle via `envPrefix` in vite.config.ts), falling back to the legacy
 * `VITE_BD_*` twins so existing setups keep working.
 *
 * Solid has no `useFollowers` hook (that's the React adapter), so this talks to
 * the core client's `followers` resource directly and re-implements the same
 * per-browser "already subscribed" hint the hook keeps internally: a
 * `localStorage` flag under `bd.followers.<siteId>`, written on a successful
 * `join` and read on mount.
 *
 * Graceful fallback (golden rule #2): when the publishable token or site id is
 * unset the component renders a placeholder that POSTs nowhere and just shows a
 * "coming soon" note, so the page still works in an unconfigured checkout. One
 * shared component powers both the footer and the home about block.
 */

const BD_PK = (import.meta.env.VITE_BD_PK ??
	import.meta.env.VITE_BD_PUBLIC_KEY) as string | undefined;
const BD_SITE_ID = (import.meta.env.VITE_BD_SITE_ID ??
	import.meta.env.VITE_BD_SITE_ID) as string | undefined;
const BD_BASE_URL = (import.meta.env.VITE_BD_PACKAGE_API_BASE_URL ??
	import.meta.env.VITE_BD_PACKAGE_API_BASE_URL) as string | undefined;
const BD_FOLLOWERS_ENABLED = Boolean(BD_PK && BD_SITE_ID);

const FOLLOWER_STORE_PREFIX = "bd.followers.";

type LocalFollow = { email: string; at: number };

/** `createBdClient` concatenates `baseUrl` + path verbatim, so the base must
 *  already carry the `/api/package/v1` suffix. The template's
 *  `VITE_BD_PACKAGE_API_BASE_URL` is a bare host (e.g. https://www.biab.app),
 *  so normalize it here — mirrors `normalizeBaseUrl` in `src/lib/bd.ts`. */
function normalizeBaseUrl(input: string): string {
	const next = input.trim().replace(/\/+$/, "");
	if (next.endsWith("/api/package/v1")) return next;
	return `${next}/api/package/v1`;
}

function readLocalFollow(key: string): LocalFollow | null {
	if (typeof window === "undefined") return null;
	try {
		const raw = window.localStorage.getItem(key);
		if (!raw) return null;
		const parsed = JSON.parse(raw) as Partial<LocalFollow>;
		return typeof parsed?.email === "string"
			? { email: parsed.email, at: Number(parsed.at) || 0 }
			: null;
	} catch {
		return null;
	}
}

function writeLocalFollow(key: string, value: LocalFollow): void {
	if (typeof window === "undefined") return;
	try {
		window.localStorage.setItem(key, JSON.stringify(value));
	} catch {
		// storage disabled / quota — the local hint is best-effort.
	}
}

export type SubscribeProps = {
	label?: string;
	placeholder?: string;
	buttonLabel?: string;
	/** Extra class on the wrapping element. */
	class?: string;
	/** `source` tag persisted on the follower row + id-prefix for field ids. */
	source?: string;
};

/** Public entry — live signup when configured, placeholder otherwise. */
export function Subscribe(props: SubscribeProps) {
	return (
		<Show
			when={BD_FOLLOWERS_ENABLED}
			fallback={<PlaceholderSubscribe {...props} />}
		>
			<LiveSubscribe {...props} />
		</Show>
	);
}

/** Shared input + button markup (identical look in both modes). */
function SubscribeFields(
	props: SubscribeProps & {
		disabled?: boolean;
		onSubmit: (event: SubmitEvent) => void;
	},
) {
	const idPrefix = () => props.source ?? "subscribe";
	const label = () => props.label ?? "Get updates in your inbox";
	const placeholder = () => props.placeholder ?? "you@example.com";
	const buttonLabel = () => props.buttonLabel ?? "Subscribe";
	return (
		<form class="bd-subscribe" onSubmit={props.onSubmit}>
			<label class="bd-label" for={`${idPrefix()}-email`}>
				{label()}
			</label>
			<div class="bd-subscribe__row">
				<input
					autocomplete="email"
					class="bd-input"
					disabled={props.disabled}
					id={`${idPrefix()}-email`}
					name="email"
					placeholder={placeholder()}
					required
					type="email"
				/>
				<button class="bd-btn" disabled={props.disabled} type="submit">
					{buttonLabel()}
				</button>
			</div>
		</form>
	);
}

/** Live signup → BD followers table via the publishable token. */
function LiveSubscribe(props: SubscribeProps) {
	const storeKey = `${FOLLOWER_STORE_PREFIX}${BD_SITE_ID}`;
	const client = createMemo(() =>
		createBdClient({
			apiKey: BD_PK as string,
			siteId: BD_SITE_ID as string,
			...(BD_BASE_URL ? { baseUrl: normalizeBaseUrl(BD_BASE_URL) } : {}),
		}),
	);

	// Anonymous "already subscribed" hint (per-browser). Read on mount so SSR and
	// the first client paint agree (localStorage is unavailable during SSR).
	const [subscribedLocally, setSubscribedLocally] = createSignal(false);
	onMount(() => setSubscribedLocally(readLocalFollow(storeKey) !== null));

	const [status, setStatus] = createSignal<
		"idle" | "submitting" | "done" | "error"
	>("idle");

	const onSubmit = async (event: SubmitEvent) => {
		event.preventDefault();
		const form = event.currentTarget as HTMLFormElement;
		const email = String(new FormData(form).get("email") ?? "").trim();
		if (!email) return;
		setStatus("submitting");
		try {
			await client().followers.join({
				email,
				source: props.source ?? "subscribe",
			});
			writeLocalFollow(storeKey, { email, at: Date.now() });
			setSubscribedLocally(true);
			setStatus("done");
		} catch {
			setStatus("error");
		}
	};

	return (
		<Show
			when={!(subscribedLocally() || status() === "done")}
			fallback={
				<p class={`bd-subscribe__note ${props.class ?? ""}`.trim()}>
					You're subscribed — thanks!
				</p>
			}
		>
			<div class={props.class}>
				<SubscribeFields
					{...props}
					disabled={status() === "submitting"}
					onSubmit={onSubmit}
				/>
				<Show when={status() === "error"}>
					<p class="bd-subscribe__error">
						Couldn't subscribe — please try again.
					</p>
				</Show>
			</div>
		</Show>
	);
}

/** Fallback when BD isn't configured (no publishable token). */
function PlaceholderSubscribe(props: SubscribeProps) {
	const [submitted, setSubmitted] = createSignal(false);
	return (
		<Show
			when={!submitted()}
			fallback={
				<p class={`bd-subscribe__note ${props.class ?? ""}`.trim()}>
					Thanks — newsletter signup is coming soon.
				</p>
			}
		>
			<div class={props.class}>
				<SubscribeFields
					{...props}
					onSubmit={(event) => {
						event.preventDefault();
						setSubmitted(true);
					}}
				/>
			</div>
		</Show>
	);
}
