// Qwik/src/routes/store/[id]/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import {
	type DocumentHead,
	Link,
	routeLoader$,
	server$,
	useNavigate,
} from "@builder.io/qwik-city";

import {
	BiabPaymentLapsedError,
	BiabServiceSuspendedError,
} from "@businessdash/sdk";
import type {
	StorefrontAddon,
	StorefrontProductDetail,
	StorefrontRelatedProduct,
	StorefrontReview,
} from "@businessdash/sdk/contracts";

import { Footer } from "../../../components/biab/Footer";
import { SiteHeader } from "../../../components/biab/SiteHeader";
import { Stars } from "../../../components/biab/Stars";
import { getBiab } from "../../../lib/biab";
import {
	addToCart,
	formatMoney,
	getCartSnapshot,
	getStoreProductAddons,
	getStoreProductReviews,
	getStoreRelatedProducts,
} from "../../../lib/biab-store";
import { getCustomerSession } from "../../../lib/biab-portal";

/** A variant row is an untyped passthrough record; pull the fields we render. */
type Variant = {
	id?: string;
	title?: string | null;
	priceCents?: number | null;
	currency?: string | null;
	isLive?: boolean;
};

export const useProduct = routeLoader$(async ({ params, cookie, status }) => {
	const biab = getBiab();
	const empty = {
		configured: false,
		suspended: false,
		product: null as StorefrontProductDetail | null,
		reviews: { items: [] as StorefrontReview[], avgRating: 0, totalCount: 0 },
		addons: [] as StorefrontAddon[],
		related: [] as StorefrontRelatedProduct[],
		cartCount: 0,
		signedIn: false,
	} as const;

	if (!biab) return empty;
	try {
		const [product, reviews, addons, related, cart, session] =
			await Promise.all([
				biab.storefront.getProduct(params.id),
				getStoreProductReviews(params.id, { limit: 20 }),
				getStoreProductAddons(params.id),
				getStoreRelatedProducts(params.id, { limit: 6 }),
				getCartSnapshot(cookie),
				getCustomerSession(cookie),
			]);
		return {
			configured: true,
			suspended: false,
			product: product as StorefrontProductDetail,
			reviews: reviews
				? {
						items: reviews.items,
						avgRating: reviews.avgRating,
						totalCount: reviews.totalCount,
					}
				: { items: [], avgRating: 0, totalCount: 0 },
			addons: addons?.items ?? [],
			related: related?.items ?? [],
			cartCount: cart?.itemCount ?? 0,
			signedIn: !!session,
		} as const;
	} catch (err) {
		if (
			err instanceof BiabServiceSuspendedError ||
			err instanceof BiabPaymentLapsedError
		) {
			return { ...empty, configured: true, suspended: true } as const;
		}
		status(404);
		return { ...empty, configured: true } as const;
	}
});

/**
 * Server RPC: add a (product, variant) to the visitor cart. `this` is the
 * RequestEvent, so we read/write the `biab_cart_visitor` cookie through it.
 * Mutations mint the cookie on first use inside `addToCart`.
 */
const addToCartRpc = server$(async function (
	this,
	input: { productId: string; variantId: string | null; quantity: number },
) {
	return await addToCart(this.cookie, input);
});

export default component$(() => {
	const data = useProduct();
	const nav = useNavigate();
	const product = data.value.product as StorefrontProductDetail | null;
	const variants = (product?.variants ?? []) as Variant[];
	const selectedVariant = useSignal<string>(variants[0]?.id ?? "");
	const adding = useSignal(false);
	const error = useSignal<string | null>(null);

	const handleAdd = $(async () => {
		if (!product) return;
		adding.value = true;
		error.value = null;
		const res = await addToCartRpc({
			productId: product.id,
			variantId: selectedVariant.value || null,
			quantity: 1,
		});
		adding.value = false;
		if (res.ok) {
			await nav("/cart");
		} else {
			error.value = res.error;
		}
	});

	const addToCartProduct = $(async (productId: string) => {
		const res = await addToCartRpc({ productId, variantId: null, quantity: 1 });
		if (res.ok) await nav("/cart");
		else error.value = res.error;
	});

	const image = product?.images?.[0] ?? null;
	const reviews = data.value.reviews;
	const addons = data.value.addons;
	const related = data.value.related;

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} cartCount={data.value.cartCount} />
			<main>
				<section class="biab-section biab-section--narrow">
					{data.value.suspended ? (
						<div class="biab-empty">
							The store is temporarily unavailable. Please check back soon.
						</div>
					) : !product ? (
						<div class="biab-empty">
							Product not found, or the store isn't connected yet.
						</div>
					) : (
						<div class="biab-card" style="padding: 2rem; display: flex; flex-direction: column; gap: 1.25rem;">
							{image ? (
								<img
									alt={product.name}
									src={image}
									style="border-radius: 1rem; aspect-ratio: 4/3; object-fit: cover;"
								/>
							) : null}
							<h1 class="biab-section__title">{product.name}</h1>

							{reviews.totalCount > 0 ? (
								<div class="store-card__rating">
									<Stars rating={reviews.avgRating} />
									<span class="store-card__reviews">
										{reviews.avgRating.toFixed(1)} · {reviews.totalCount}{" "}
										{reviews.totalCount === 1 ? "review" : "reviews"}
									</span>
								</div>
							) : null}

							{variants.length > 1 ? (
								<div>
									<label class="biab-label" for="variant">
										Option
									</label>
									<select
										bind:value={selectedVariant}
										class="biab-select"
										id="variant"
									>
										{variants.map((v, i) => (
											<option key={v.id ?? i} value={v.id ?? ""}>
												{`${v.title ?? `Option ${i + 1}`}${
													typeof v.priceCents === "number"
														? ` · ${formatMoney(v.priceCents, v.currency ?? "usd")}`
														: ""
												}`}
											</option>
										))}
									</select>
								</div>
							) : variants[0] && typeof variants[0].priceCents === "number" ? (
								<div class="service-card__price">
									{formatMoney(
										variants[0].priceCents,
										variants[0].currency ?? "usd",
									)}
								</div>
							) : null}

							<button
								class="biab-btn"
								disabled={adding.value}
								onClick$={handleAdd}
								style="align-self: flex-start;"
								type="button"
							>
								{adding.value ? "Adding…" : "Add to cart"}
							</button>

							{error.value ? (
								<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
									{error.value}
								</div>
							) : null}
						</div>
					)}

					{/* Addons rail — companion / cross-sell ("complete your X") */}
					{product && addons.length > 0 ? (
						<div class="store-detail__block">
							<h2 class="store-detail__heading">Complete your purchase</h2>
							<div class="store-addons">
								{addons.map((a) => (
									<div class="biab-card store-addon" key={a.id}>
										{a.imageUrl ? (
											<img
												alt={a.addonName}
												class="store-addon__img"
												loading="lazy"
												referrerPolicy="no-referrer"
												src={a.imageUrl}
											/>
										) : null}
										<div class="store-addon__body">
											{a.groupLabel ? (
												<span class="biab-badge">{a.groupLabel}</span>
											) : null}
											<h3 class="store-addon__name">{a.addonName}</h3>
											{a.addonDescription ? (
												<p class="store-addon__desc">{a.addonDescription}</p>
											) : null}
											<div class="store-card__price">
												{a.priceCents != null ? (
													<span class="service-card__price">
														{formatMoney(a.priceCents, "usd")}
													</span>
												) : null}
												{a.originalPriceCents != null &&
												a.priceCents != null &&
												a.originalPriceCents > a.priceCents ? (
													<span class="store-card__compare">
														{formatMoney(a.originalPriceCents, "usd")}
													</span>
												) : null}
											</div>
											<button
												class="biab-btn biab-btn--ghost"
												onClick$={() => addToCartProduct(a.addonProductId)}
												style="align-self: flex-start;"
												type="button"
											>
												Add
											</button>
										</div>
									</div>
								))}
							</div>
						</div>
					) : null}

					{/* Reviews */}
					{product && reviews.items.length > 0 ? (
						<div class="store-detail__block">
							<h2 class="store-detail__heading">
								Reviews{" "}
								<span class="store-detail__heading-sub">
									{reviews.avgRating.toFixed(1)} · {reviews.totalCount}{" "}
									{reviews.totalCount === 1 ? "review" : "reviews"}
								</span>
							</h2>
							<div class="store-reviews">
								{reviews.items.map((r) => (
									<div class="biab-card store-review" key={r.id}>
										<div class="store-review__head">
											<Stars rating={r.rating} />
											{r.reviewerName ? (
												<span class="store-review__author">
													{r.reviewerName}
												</span>
											) : null}
										</div>
										{r.title ? (
											<h3 class="store-review__title">{r.title}</h3>
										) : null}
										{r.body || r.content ? (
											<p class="store-review__body">{r.body ?? r.content}</p>
										) : null}
									</div>
								))}
							</div>
						</div>
					) : null}

					{/* Related grid — "you may also like" */}
					{product && related.length > 0 ? (
						<div class="store-detail__block">
							<h2 class="store-detail__heading">You may also like</h2>
							<div class="biab-grid-3">
								{related.map((p) => (
									<Link
										class="biab-card service-card store-card"
										href={`/store/${p.id}`}
										key={p.id}
									>
										<div class="store-card__media">
											{p.coverImageUrl ? (
												<img
													alt={p.name}
													loading="lazy"
													referrerPolicy="no-referrer"
													src={p.coverImageUrl}
												/>
											) : (
												<div class="store-card__placeholder">No image</div>
											)}
										</div>
										<h3>{p.name}</h3>
										{p.minPriceDollars != null ? (
											<span class="service-card__price">
												{formatMoney(Math.round(p.minPriceDollars * 100), "usd")}
											</span>
										) : null}
									</Link>
								))}
							</div>
						</div>
					) : null}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = ({ resolveValue }) => {
	const data = resolveValue(useProduct);
	const name = data.product?.name ?? "Product";
	return {
		title: `${name} — Your Business`,
		meta: [{ name: "description", content: `${name} — buy now.` }],
	};
};

// Svelte/src/routes/store/[id]/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import StoreNav from '$lib/components/biab/StoreNav.svelte';
	import { addToCart, formatDollars, formatCents } from '$lib/biab/cart-client';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	function asString(v: unknown): string {
		return typeof v === 'string' ? v : '';
	}
	function asNumber(v: unknown): number | null {
		return typeof v === 'number' && Number.isFinite(v) ? v : null;
	}
	function firstImage(images: unknown): string | null {
		return Array.isArray(images) && typeof images[0] === 'string'
			? images[0]
			: null;
	}

	type Variant = {
		id: string;
		name: string;
		price: number | null;
		isLive: boolean;
	};

	const variants: Variant[] = $derived(
		(data.product?.variants ?? []).map((raw) => ({
			id: asString(raw.id),
			name: asString(raw.name) || 'Default',
			price: asNumber(raw.price),
			isLive: raw.isLive !== false,
		})),
	);

	/** First purchasable variant id of an addon, for the rail's "Add" button. */
	function addonFirstVariantId(variants: unknown): string | undefined {
		if (!Array.isArray(variants)) return undefined;
		const first = variants[0] as { variantId?: unknown } | undefined;
		return first && typeof first.variantId === 'string'
			? first.variantId
			: undefined;
	}

	// svelte-ignore state_referenced_locally
	let cartCount = $state(data.cartCount);
	let selectedVariant = $state<string>('');
	let quantity = $state(1);
	let busy = $state(false);
	let message = $state<string | null>(null);
	let messageKind = $state<'ok' | 'error'>('ok');
	let addingAddon = $state<string | null>(null);
	let addedAddons = $state<Record<string, boolean>>({});

	$effect(() => {
		// Default to the first live variant once data is in.
		if (!selectedVariant && variants.length > 0) {
			selectedVariant = variants.find((v) => v.isLive)?.id ?? variants[0].id;
		}
	});

	async function handleAdd() {
		if (!data.product) return;
		busy = true;
		message = null;
		const res = await addToCart({
			productId: data.product.id,
			variantId: selectedVariant || undefined,
			quantity,
		});
		busy = false;
		if (res.ok) {
			cartCount = res.snapshot.itemCount;
			messageKind = 'ok';
			message = 'Added to cart.';
		} else {
			messageKind = 'error';
			message = res.error;
		}
	}

	async function handleAddAddon(addon: (typeof data.addons)[number]) {
		addingAddon = addon.id;
		const res = await addToCart({
			productId: addon.addonProductId,
			variantId: addonFirstVariantId(addon.variants),
			quantity: 1,
		});
		addingAddon = null;
		if (res.ok) {
			cartCount = res.snapshot.itemCount;
			addedAddons = { ...addedAddons, [addon.id]: true };
		}
	}
</script>

{#snippet stars(rating: number)}
	<span class="stars" role="img" aria-label={`${rating.toFixed(1)} out of 5`}>
		{#each [0, 1, 2, 3, 4] as i (i)}
			<span class="stars__star" class:stars__star--on={rating >= i + 1}>★</span>
		{/each}
	</span>
{/snippet}

<svelte:head>
	<title>{asString(data.product?.name) || 'Product'}</title>
</svelte:head>

<Header />
<StoreNav {cartCount} />

<main class="biab-section">
	{#if !data.configured}
		<div class="biab-empty">Store isn't connected.</div>
	{:else if data.product}
		<a href="/store" style="font-size: 0.9rem;">← Back to products</a>
		<div class="product-detail">
			<div class="product-detail__media">
				{#if firstImage(data.product.images)}
					<img src={firstImage(data.product.images)} alt={asString(data.product.name)} />
				{:else}
					<div class="product-detail__placeholder">No image</div>
				{/if}
			</div>
			<div class="product-detail__info biab-card">
				<h1>{asString(data.product.name) || 'Untitled'}</h1>

				{#if data.reviews && data.reviews.totalCount > 0}
					<div class="product-detail__rating">
						{@render stars(data.reviews.avgRating)}
						<span>{data.reviews.avgRating.toFixed(1)} ({data.reviews.totalCount})</span>
					</div>
				{/if}

				{#if asString((data.product as Record<string, unknown>).description)}
					<p class="product-detail__desc">
						{asString((data.product as Record<string, unknown>).description)}
					</p>
				{/if}

				{#if variants.length > 0}
					<div>
						<label class="biab-label" for="variant">Option</label>
						<select id="variant" class="biab-select" bind:value={selectedVariant}>
							{#each variants as v (v.id)}
								<option value={v.id} disabled={!v.isLive}>
									{v.name}{v.price != null ? ` — ${formatDollars(v.price)}` : ''}
									{v.isLive ? '' : ' (unavailable)'}
								</option>
							{/each}
						</select>
					</div>
				{/if}

				<div>
					<label class="biab-label" for="qty">Quantity</label>
					<input
						id="qty"
						class="biab-input"
						type="number"
						min="1"
						max="999"
						bind:value={quantity}
						style="max-width: 7rem;"
					/>
				</div>

				<button class="biab-btn" onclick={handleAdd} disabled={busy}>
					{busy ? 'Adding…' : 'Add to cart'}
				</button>

				{#if message}
					<div
						class="product-detail__msg"
						class:product-detail__msg--err={messageKind === 'error'}
					>
						{message}
						{#if messageKind === 'ok'}
							<button class="biab-btn biab-btn--ghost" onclick={() => goto('/store/cart')}>
								View cart
							</button>
						{/if}
					</div>
				{/if}
			</div>
		</div>

		{#if data.addons.length > 0}
			<section class="product-section">
				<h2 class="product-section__title">Complete your purchase</h2>
				<div class="addon-grid">
					{#each data.addons as addon (addon.id)}
						<div class="addon-card biab-card">
							<div class="addon-card__media">
								{#if addon.imageUrl}
									<img src={addon.imageUrl} alt={addon.addonName} loading="lazy" referrerpolicy="no-referrer" />
								{:else}
									<div class="addon-card__noimg">—</div>
								{/if}
							</div>
							<div class="addon-card__body">
								{#if addon.groupLabel}
									<span class="addon-card__group">{addon.groupLabel}</span>
								{/if}
								<p class="addon-card__name">{addon.addonName}</p>
								{#if addon.priceCents != null}
									<span class="addon-card__price">{formatCents(addon.priceCents)}</span>
								{/if}
							</div>
							<button
								class="biab-btn biab-btn--ghost addon-card__add"
								onclick={() => handleAddAddon(addon)}
								disabled={addingAddon === addon.id || addedAddons[addon.id]}
							>
								{addedAddons[addon.id]
									? 'Added'
									: addingAddon === addon.id
										? '…'
										: 'Add'}
							</button>
						</div>
					{/each}
				</div>
			</section>
		{/if}

		{#if data.reviews && data.reviews.items.length > 0}
			<section class="product-section">
				<h2 class="product-section__title">Reviews</h2>
				<div class="review-list">
					{#each data.reviews.items as review (review.id)}
						{@const name = asString(review.reviewerName) || 'Verified buyer'}
						{@const text = asString(review.content) || asString(review.body)}
						{@const title = asString(review.title)}
						<div class="review">
							<div class="review__head">
								{@render stars(asNumber(review.rating) ?? 0)}
								<span class="review__name">{name}</span>
							</div>
							{#if title}
								<p class="review__title">{title}</p>
							{/if}
							{#if text}
								<p class="review__body">{text}</p>
							{/if}
						</div>
					{/each}
				</div>
			</section>
		{/if}

		{#if data.related.length > 0}
			<section class="product-section">
				<h2 class="product-section__title">You may also like</h2>
				<div class="biab-grid-4">
					{#each data.related as rp (rp.id)}
						<a class="biab-card related-card" href={`/store/${rp.id}`}>
							<div class="related-card__media">
								{#if rp.coverImageUrl}
									<img src={rp.coverImageUrl} alt={rp.name} loading="lazy" referrerpolicy="no-referrer" />
								{:else}
									<div class="related-card__noimg">—</div>
								{/if}
							</div>
							<div class="related-card__body">
								<h3>{rp.name}</h3>
								{#if rp.minPriceDollars != null}
									<span class="related-card__price">{formatDollars(rp.minPriceDollars)}</span>
								{/if}
							</div>
						</a>
					{/each}
				</div>
			</section>
		{/if}
	{/if}
</main>

<Footer />

<style>
	.product-detail {
		display: grid;
		grid-template-columns: 1fr;
		gap: 2rem;
		margin-top: 1.5rem;
	}
	@media (min-width: 800px) {
		.product-detail {
			grid-template-columns: 1fr 1fr;
		}
	}
	.product-detail__media img {
		width: 100%;
		border-radius: 1rem;
		object-fit: cover;
	}
	.product-detail__placeholder {
		display: grid;
		place-items: center;
		aspect-ratio: 4 / 3;
		border: 1px dashed var(--border-strong);
		border-radius: 1rem;
		color: var(--text-muted);
	}
	.product-detail__info {
		padding: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}
	.product-detail__rating {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		font-size: 0.9rem;
		color: var(--text-muted);
	}
	.product-detail__desc {
		color: var(--text-muted);
	}
	.product-detail__msg {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		flex-wrap: wrap;
		padding: 0.75rem 1rem;
		border-radius: 0.5rem;
		background: var(--success-bg);
		color: var(--success);
		font-size: 0.9rem;
	}
	.product-detail__msg--err {
		background: var(--danger-bg);
		color: var(--danger);
	}

	.stars {
		display: inline-flex;
		gap: 0.05rem;
		line-height: 1;
	}
	.stars__star {
		color: var(--border-strong);
		font-size: 0.85rem;
	}
	.stars__star--on {
		color: #e8a317;
	}

	/* Shared section scaffolding for addons / reviews / related */
	.product-section {
		margin-top: 3rem;
	}
	.product-section__title {
		font-size: 1.4rem;
		margin-bottom: 1.25rem;
	}

	.addon-grid {
		display: grid;
		grid-template-columns: 1fr;
		gap: 0.85rem;
	}
	@media (min-width: 600px) {
		.addon-grid {
			grid-template-columns: repeat(2, 1fr);
		}
	}
	@media (min-width: 900px) {
		.addon-grid {
			grid-template-columns: repeat(3, 1fr);
		}
	}
	.addon-card {
		display: flex;
		align-items: center;
		gap: 0.85rem;
		padding: 0.75rem;
	}
	.addon-card:hover {
		transform: none;
	}
	.addon-card__media {
		width: 4rem;
		height: 4rem;
		flex-shrink: 0;
		border-radius: 0.5rem;
		overflow: hidden;
		background: var(--bg-soft);
	}
	.addon-card__media img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}
	.addon-card__noimg {
		display: grid;
		place-items: center;
		width: 100%;
		height: 100%;
		color: var(--text-muted);
	}
	.addon-card__body {
		min-width: 0;
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: 0.15rem;
	}
	.addon-card__group {
		font-size: 0.68rem;
		font-weight: 700;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		color: var(--accent);
	}
	.addon-card__name {
		font-weight: 600;
		color: var(--title);
		font-size: 0.92rem;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}
	.addon-card__price {
		color: var(--accent);
		font-weight: 700;
		font-size: 0.88rem;
	}
	.addon-card__add {
		flex-shrink: 0;
		padding: 0.45rem 0.9rem;
		font-size: 0.8rem;
	}

	.review-list {
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}
	.review {
		padding-bottom: 1.25rem;
		border-bottom: 1px solid var(--border);
	}
	.review__head {
		display: flex;
		align-items: center;
		gap: 0.6rem;
	}
	.review__name {
		font-weight: 600;
		color: var(--title);
		font-size: 0.9rem;
	}
	.review__title {
		margin-top: 0.4rem;
		font-weight: 600;
		color: var(--title);
		font-size: 0.92rem;
	}
	.review__body {
		margin-top: 0.25rem;
		color: var(--text-muted);
		font-size: 0.92rem;
		line-height: 1.55;
	}

	.related-card {
		display: flex;
		flex-direction: column;
		overflow: hidden;
		color: inherit;
	}
	.related-card:hover {
		border-bottom-color: transparent;
	}
	.related-card__media {
		aspect-ratio: 1 / 1;
		background: var(--bg-soft);
	}
	.related-card__media img {
		width: 100%;
		height: 100%;
		object-fit: cover;
	}
	.related-card__noimg {
		display: grid;
		place-items: center;
		width: 100%;
		height: 100%;
		color: var(--text-muted);
	}
	.related-card__body {
		padding: 0.85rem 1rem;
		display: flex;
		flex-direction: column;
		gap: 0.3rem;
	}
	.related-card__body h3 {
		font-size: 0.92rem;
	}
	.related-card__price {
		color: var(--accent);
		font-weight: 700;
		font-size: 0.88rem;
	}
</style>
