// Svelte/src/lib/components/bd/Footer.svelte
<script lang="ts">
	import Subscribe from '$lib/components/bd/Subscribe.svelte';
</script>

<footer class="app-footer">
	<div class="app-footer__meta">
		<div>© {new Date().getFullYear()} Your Business. All rights reserved.</div>
		<div>
			Built with
			<a href="https://github.com/Gold240sx/business-in-a-box">@businessdash/sdk</a>
		</div>
	</div>
	<div class="app-footer__subscribe">
		<Subscribe
			source="footer"
			idPrefix="footer-subscribe"
			label="Get updates in your inbox"
			buttonLabel="Subscribe"
		/>
	</div>
</footer>

<style>
	.app-footer__meta {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
	}
	.app-footer__subscribe {
		flex: 1;
		min-width: 16rem;
		display: flex;
		justify-content: flex-end;
	}
</style>

// T3-App/src/app/_components/bd/Footer.tsx
import { Subscribe } from "./Subscribe";

export function BdFooter() {
	return (
		<footer className="app-footer">
			<div className="app-footer__meta">
				<div>
					© {new Date().getFullYear()} Your Business. All rights reserved.
				</div>
				<div>
					Built with{" "}
					<a href="https://github.com/businessdash/platform">
						@businessdash/sdk
					</a>
				</div>
			</div>
			<Subscribe
				className="app-footer__subscribe"
				idPrefix="footer-subscribe"
				label="Get updates in your inbox"
				source="footer"
			/>
		</footer>
	);
}
