// Qwik/src/routes/my-account/index.tsx
import { component$ } from "@builder.io/qwik";
import {
	type DocumentHead,
	Form,
	routeAction$,
	routeLoader$,
	zod$,
	z,
} from "@builder.io/qwik-city";

import type { CustomerWorkBundle } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import {
	getCustomerSession,
	getCustomerWork,
	isCustomerPortalConfigured,
	submitCustomerReview,
} from "../../lib/biab-portal";

/**
 * Customer portal "my account" page.
 *
 *  - `routeLoader$` reads the `biab_session` cookie via `getCustomerSession`
 *    (which calls `getTenantSession`), then loads the work bundle (`getWork`).
 *  - When signed out, we render sign-in / sign-up links to the auth handler.
 *  - `routeAction$` submits a customer review through the portal.
 */
export const useAccount = routeLoader$(async ({ cookie }) => {
	const session = await getCustomerSession(cookie);
	if (!session) {
		return { configured: isCustomerPortalConfigured(), session: null, work: null };
	}
	const work = await getCustomerWork(cookie);
	return {
		configured: true,
		session: {
			email: session.user.email,
			firstName: session.user.firstName,
			lastName: session.user.lastName,
		},
		work,
	};
});

export const useSubmitReview = routeAction$(
	async (data, { cookie }) => {
		try {
			const res = await submitCustomerReview(cookie, {
				rating: data.rating,
				title: data.title || undefined,
				body: data.body,
				jobId: data.jobId || undefined,
			});
			return {
				ok: true as const,
				message:
					"Thanks! Your review was submitted and will appear once it's approved.",
				status: res.status,
			};
		} catch (err) {
			return {
				ok: false as const,
				message:
					err instanceof Error
						? err.message
						: "We couldn't submit your review. You may need to be signed in.",
			};
		}
	},
	zod$({
		rating: z.coerce.number().int().min(1).max(5),
		title: z.string().trim().max(200).optional(),
		body: z.string().trim().min(1, "Please write a few words.").max(5000),
		jobId: z
			.string()
			.uuid()
			.optional()
			.or(z.literal("").transform(() => undefined)),
	}),
);

function WorkSummary({ work }: { work: CustomerWorkBundle }) {
	const s = work.summary;
	return (
		<div class="biab-card" style="padding: 1.5rem; display: flex; gap: 1.5rem; flex-wrap: wrap;">
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.openJobCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Open jobs
				</div>
			</div>
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.pendingQuoteCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Pending quotes
				</div>
			</div>
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.unpaidInvoiceCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Unpaid invoices
				</div>
			</div>
		</div>
	);
}

export default component$(() => {
	const data = useAccount();
	const review = useSubmitReview();
	const signedIn = !!data.value.session;
	const work = data.value.work;

	return (
		<>
			<SiteHeader signedIn={signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Portal</span>
						<h2 class="biab-section__title">My account</h2>
					</div>

					{!data.value.configured ? (
						<div class="biab-empty">
							Customer accounts aren't connected yet. Set
							<code> BIAB_AUTH_CALLBACK_URL</code> (see .env.example).
						</div>
					) : !signedIn ? (
						<div class="biab-card" style="padding: 2rem; display: flex; flex-direction: column; gap: 1rem; align-items: flex-start;">
							<p>Sign in to view your jobs, quotes, and invoices.</p>
							<div style="display: flex; gap: 0.75rem;">
								<a class="biab-btn" href="/api/biab-auth/sign-in">
									Sign in
								</a>
								<a class="biab-btn biab-btn--ghost" href="/api/biab-auth/sign-up">
									Create account
								</a>
							</div>
						</div>
					) : (
						<div style="display: flex; flex-direction: column; gap: 2rem;">
							<div class="biab-card" style="padding: 1.5rem;">
								<div style="font-weight: 600; color: var(--title);">
									{[data.value.session?.firstName, data.value.session?.lastName]
										.filter(Boolean)
										.join(" ") || "Signed in"}
								</div>
								<div style="color: var(--text-muted);">
									{data.value.session?.email}
								</div>
							</div>

							{work?.unlinked ? (
								<div class="biab-empty">
									Your account isn't linked to a customer record yet. Once we
									connect it, your jobs and invoices will show here.
								</div>
							) : work ? (
								<WorkSummary work={work} />
							) : null}

							{/* Customer review submission */}
							<div class="biab-card" style="padding: 2rem;">
								<h3 style="margin-bottom: 1rem;">Leave a review</h3>
								{review.value?.ok ? (
									<p style="color: var(--success);">
										{review.value.message}
									</p>
								) : (
									<Form
										action={review}
										style="display: flex; flex-direction: column; gap: 1rem;"
									>
										<div>
											<label class="biab-label" for="rating">
												Rating
											</label>
											<select class="biab-select" id="rating" name="rating">
												<option value="5">★★★★★ — Excellent</option>
												<option value="4">★★★★ — Good</option>
												<option value="3">★★★ — Okay</option>
												<option value="2">★★ — Poor</option>
												<option value="1">★ — Bad</option>
											</select>
										</div>
										<div>
											<label class="biab-label" for="title">
												Title (optional)
											</label>
											<input class="biab-input" id="title" name="title" />
										</div>
										<div>
											<label class="biab-label" for="body">
												Your review
											</label>
											<textarea
												class="biab-textarea"
												id="body"
												name="body"
												required
											/>
										</div>
										<button
											class="biab-btn"
											style="align-self: flex-start;"
											type="submit"
										>
											Submit review
										</button>
										{review.value && !review.value.ok ? (
											<div style="color: var(--danger); font-size: 0.9rem;">
												{review.value.message}
											</div>
										) : null}
									</Form>
								)}
							</div>
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "My account — Your Business",
	meta: [
		{
			name: "description",
			content: "Customer portal: jobs, quotes, invoices, and reviews.",
		},
	],
};

// Svelte/src/routes/my-account/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import type { ActionData, PageData } from './$types';
	import type { ReviewState } from './+page.server';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	// SvelteKit's generated `ActionData` flattens the action's union; read the
	// review payload through the server-defined `ReviewState` so `fieldErrors`
	// narrows on `status`.
	const review = $derived(form?.review as ReviewState | undefined);
	const user = $derived(data.session?.user);
	const work = $derived(data.work);

	function displayName(): string {
		if (!user) return '';
		const name = [user.firstName, user.lastName].filter(Boolean).join(' ');
		return name || user.email || 'there';
	}
</script>

<svelte:head><title>My account</title></svelte:head>

<Header />

<main class="biab-section biab-section--narrow">
	{#if !data.configured}
		<div class="biab-empty">
			Customer accounts aren't configured. Set <code>BIAB_AUTH_CALLBACK_URL</code>
			(plus the API key + base URL) to enable sign-in.
		</div>
	{:else if !data.session}
		<div class="biab-card account-signin">
			<h1 class="biab-section__title">My account</h1>
			<p>Sign in to view your jobs, quotes and invoices, and to leave a review.</p>
			<div style="display: flex; gap: 0.75rem; flex-wrap: wrap;">
				<a class="biab-btn" href="/api/biab-auth/sign-in">Sign in</a>
				<a class="biab-btn biab-btn--ghost" href="/api/biab-auth/sign-up">Create account</a>
			</div>
		</div>
	{:else}
		<div class="biab-section__lead" style="text-align: left;">
			<span class="biab-section__eyebrow">Account</span>
			<h1 class="biab-section__title">Welcome back, {displayName()}.</h1>
		</div>

		<div class="biab-card account-card">
			<div class="account-card__head">
				<div>
					<strong>{user?.email ?? 'Signed in'}</strong>
					{#if data.session.role}
						<span class="biab-badge">{data.session.role}</span>
					{/if}
				</div>
				<a class="biab-btn biab-btn--ghost" href="/api/biab-auth/sign-out">Sign out</a>
			</div>

			{#if work}
				{#if work.unlinked}
					<p class="account-note">
						Your account isn't linked to a customer record yet. Once we connect
						your email to a project, your jobs and invoices will appear here.
					</p>
				{:else}
					<div class="account-stats">
						<div><span>{work.summary.openJobCount}</span>Open jobs</div>
						<div><span>{work.summary.pendingQuoteCount}</span>Pending quotes</div>
						<div><span>{work.summary.unpaidInvoiceCount}</span>Unpaid invoices</div>
						<div><span>{work.summary.awaitingSignatureCount}</span>Awaiting signature</div>
					</div>
					{#if work.jobs.length > 0}
						<div class="account-jobs">
							<h3>Recent jobs</h3>
							<ul>
								{#each work.jobs.slice(0, 5) as job (job.id)}
									<li>
										<strong>{job.name ?? 'Job'}</strong>
										<span class="biab-badge">{job.status}</span>
									</li>
								{/each}
							</ul>
						</div>
					{/if}
				{/if}
			{/if}
		</div>

		<div class="biab-card account-card">
			<h3>Leave a review</h3>
			{#if review?.status === 'success'}
				<div class="account-msg account-msg--ok">{review.message}</div>
			{:else}
				<form method="POST" action="?/submitReview" use:enhance class="review-form">
					<div>
						<label class="biab-label" for="rating">Rating (1–5)</label>
						<input
							class="biab-input"
							id="rating"
							name="rating"
							type="number"
							min="1"
							max="5"
							value="5"
							style="max-width: 6rem;"
						/>
						{#if review?.status === 'error' && review.fieldErrors?.rating}
							<small style="color: var(--danger);">{review.fieldErrors.rating}</small>
						{/if}
					</div>
					<div>
						<label class="biab-label" for="title">Title (optional)</label>
						<input class="biab-input" id="title" name="title" type="text" />
					</div>
					<div>
						<label class="biab-label" for="body">Your review</label>
						<textarea class="biab-textarea" id="body" name="body" required></textarea>
						{#if review?.status === 'error' && review.fieldErrors?.body}
							<small style="color: var(--danger);">{review.fieldErrors.body}</small>
						{/if}
					</div>
					<button class="biab-btn" type="submit" style="align-self: flex-start;">
						Submit review
					</button>
					{#if review?.status === 'error'}
						<div class="account-msg account-msg--err">{review.message}</div>
					{/if}
				</form>
			{/if}
		</div>
	{/if}
</main>

<Footer />

<style>
	.account-signin,
	.account-card {
		padding: 2rem;
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
		margin-bottom: 1.5rem;
	}
	.account-card__head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 1rem;
		flex-wrap: wrap;
	}
	.account-card__head .biab-badge {
		margin-left: 0.5rem;
	}
	.account-note {
		color: var(--text-muted);
	}
	.account-stats {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(8rem, 1fr));
		gap: 1rem;
	}
	.account-stats div {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
		padding: 1rem;
		border: 1px solid var(--border);
		border-radius: 0.75rem;
		font-size: 0.85rem;
		color: var(--text-muted);
	}
	.account-stats span {
		font-size: 1.5rem;
		font-weight: 800;
		color: var(--title);
	}
	.account-jobs ul {
		list-style: none;
		padding: 0;
		margin: 0.5rem 0 0;
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}
	.account-jobs li {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 0.75rem;
		padding: 0.6rem 0.85rem;
		border: 1px solid var(--border);
		border-radius: 0.5rem;
	}
	.review-form {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	.account-msg {
		padding: 0.75rem 1rem;
		border-radius: 0.5rem;
		font-size: 0.9rem;
	}
	.account-msg--ok {
		background: var(--success-bg);
		color: var(--success);
	}
	.account-msg--err {
		background: var(--danger-bg);
		color: var(--danger);
	}
</style>
