// Qwik/src/components/biab/Footer.tsx
import { component$ } from "@builder.io/qwik";

import { Subscribe } from "./Subscribe";

export const Footer = component$(() => {
	return (
		<footer class="app-footer">
			<div style="max-width: 24rem; flex: 1 1 18rem;">
				<Subscribe
					buttonLabel="Subscribe"
					label="Get updates in your inbox"
					source="footer"
				/>
			</div>
			<div style="display: flex; flex-direction: column; gap: 0.5rem; align-items: flex-end;">
				<div>
					© {new Date().getFullYear()} Your Business. All rights reserved.
				</div>
				<div>
					Built with
					<a href="https://github.com/businessdash/platform">
						@businessdash/sdk
					</a>
				</div>
			</div>
		</footer>
	);
});

// Svelte/src/lib/components/biab/Footer.svelte
<script lang="ts">
	import Subscribe from '$lib/components/biab/Subscribe.svelte';
</script>

<footer class="app-footer">
	<div class="app-footer__meta">
		<div>© {new Date().getFullYear()} Your Business. All rights reserved.</div>
		<div>
			Built with
			<a href="https://github.com/Gold240sx/business-in-a-box">@businessdash/sdk</a>
		</div>
	</div>
	<div class="app-footer__subscribe">
		<Subscribe
			source="footer"
			idPrefix="footer-subscribe"
			label="Get updates in your inbox"
			buttonLabel="Subscribe"
		/>
	</div>
</footer>

<style>
	.app-footer__meta {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
	}
	.app-footer__subscribe {
		flex: 1;
		min-width: 16rem;
		display: flex;
		justify-content: flex-end;
	}
</style>
