// Qwik/src/routes/my-account/index.tsx
import { component$ } from "@builder.io/qwik";
import {
	type DocumentHead,
	Form,
	routeAction$,
	routeLoader$,
	zod$,
	z,
} from "@builder.io/qwik-city";

import type { CustomerWorkBundle } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import {
	getCustomerSession,
	getCustomerWork,
	isCustomerPortalConfigured,
	submitCustomerReview,
} from "../../lib/biab-portal";

/**
 * Customer portal "my account" page.
 *
 *  - `routeLoader$` reads the `biab_session` cookie via `getCustomerSession`
 *    (which calls `getTenantSession`), then loads the work bundle (`getWork`).
 *  - When signed out, we render sign-in / sign-up links to the auth handler.
 *  - `routeAction$` submits a customer review through the portal.
 */
export const useAccount = routeLoader$(async ({ cookie }) => {
	const session = await getCustomerSession(cookie);
	if (!session) {
		return { configured: isCustomerPortalConfigured(), session: null, work: null };
	}
	const work = await getCustomerWork(cookie);
	return {
		configured: true,
		session: {
			email: session.user.email,
			firstName: session.user.firstName,
			lastName: session.user.lastName,
		},
		work,
	};
});

export const useSubmitReview = routeAction$(
	async (data, { cookie }) => {
		try {
			const res = await submitCustomerReview(cookie, {
				rating: data.rating,
				title: data.title || undefined,
				body: data.body,
				jobId: data.jobId || undefined,
			});
			return {
				ok: true as const,
				message:
					"Thanks! Your review was submitted and will appear once it's approved.",
				status: res.status,
			};
		} catch (err) {
			return {
				ok: false as const,
				message:
					err instanceof Error
						? err.message
						: "We couldn't submit your review. You may need to be signed in.",
			};
		}
	},
	zod$({
		rating: z.coerce.number().int().min(1).max(5),
		title: z.string().trim().max(200).optional(),
		body: z.string().trim().min(1, "Please write a few words.").max(5000),
		jobId: z
			.string()
			.uuid()
			.optional()
			.or(z.literal("").transform(() => undefined)),
	}),
);

function WorkSummary({ work }: { work: CustomerWorkBundle }) {
	const s = work.summary;
	return (
		<div class="biab-card" style="padding: 1.5rem; display: flex; gap: 1.5rem; flex-wrap: wrap;">
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.openJobCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Open jobs
				</div>
			</div>
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.pendingQuoteCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Pending quotes
				</div>
			</div>
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.unpaidInvoiceCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Unpaid invoices
				</div>
			</div>
		</div>
	);
}

export default component$(() => {
	const data = useAccount();
	const review = useSubmitReview();
	const signedIn = !!data.value.session;
	const work = data.value.work;

	return (
		<>
			<SiteHeader signedIn={signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Portal</span>
						<h2 class="biab-section__title">My account</h2>
					</div>

					{!data.value.configured ? (
						<div class="biab-empty">
							Customer accounts aren't connected yet. Set
							<code> BIAB_AUTH_CALLBACK_URL</code> (see .env.example).
						</div>
					) : !signedIn ? (
						<div class="biab-card" style="padding: 2rem; display: flex; flex-direction: column; gap: 1rem; align-items: flex-start;">
							<p>Sign in to view your jobs, quotes, and invoices.</p>
							<div style="display: flex; gap: 0.75rem;">
								<a class="biab-btn" href="/api/biab-auth/sign-in">
									Sign in
								</a>
								<a class="biab-btn biab-btn--ghost" href="/api/biab-auth/sign-up">
									Create account
								</a>
							</div>
						</div>
					) : (
						<div style="display: flex; flex-direction: column; gap: 2rem;">
							<div class="biab-card" style="padding: 1.5rem;">
								<div style="font-weight: 600; color: var(--title);">
									{[data.value.session?.firstName, data.value.session?.lastName]
										.filter(Boolean)
										.join(" ") || "Signed in"}
								</div>
								<div style="color: var(--text-muted);">
									{data.value.session?.email}
								</div>
							</div>

							{work?.unlinked ? (
								<div class="biab-empty">
									Your account isn't linked to a customer record yet. Once we
									connect it, your jobs and invoices will show here.
								</div>
							) : work ? (
								<WorkSummary work={work} />
							) : null}

							{/* Customer review submission */}
							<div class="biab-card" style="padding: 2rem;">
								<h3 style="margin-bottom: 1rem;">Leave a review</h3>
								{review.value?.ok ? (
									<p style="color: var(--success);">
										{review.value.message}
									</p>
								) : (
									<Form
										action={review}
										style="display: flex; flex-direction: column; gap: 1rem;"
									>
										<div>
											<label class="biab-label" for="rating">
												Rating
											</label>
											<select class="biab-select" id="rating" name="rating">
												<option value="5">★★★★★ — Excellent</option>
												<option value="4">★★★★ — Good</option>
												<option value="3">★★★ — Okay</option>
												<option value="2">★★ — Poor</option>
												<option value="1">★ — Bad</option>
											</select>
										</div>
										<div>
											<label class="biab-label" for="title">
												Title (optional)
											</label>
											<input class="biab-input" id="title" name="title" />
										</div>
										<div>
											<label class="biab-label" for="body">
												Your review
											</label>
											<textarea
												class="biab-textarea"
												id="body"
												name="body"
												required
											/>
										</div>
										<button
											class="biab-btn"
											style="align-self: flex-start;"
											type="submit"
										>
											Submit review
										</button>
										{review.value && !review.value.ok ? (
											<div style="color: var(--danger); font-size: 0.9rem;">
												{review.value.message}
											</div>
										) : null}
									</Form>
								)}
							</div>
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "My account — Your Business",
	meta: [
		{
			name: "description",
			content: "Customer portal: jobs, quotes, invoices, and reviews.",
		},
	],
};

// Remix/app/routes/my-account.tsx
import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import type {
	ActionFunctionArgs,
	LoaderFunctionArgs,
	MetaFunction,
} from "react-router";

import { SiteHeader } from "~/components/SiteHeader";
import {
	getCustomerSession,
	getCustomerWork,
	isCustomerPortalConfigured,
	submitCustomerReview,
} from "~/lib/biab-portal.server";

export const meta: MetaFunction = () => [
	{ title: "My account — Your Business" },
];

export async function loader({ request }: LoaderFunctionArgs) {
	const configured = isCustomerPortalConfigured();
	const session = await getCustomerSession(request);
	if (!session) {
		return { configured, signedIn: false as const };
	}
	const work = await getCustomerWork(request);
	return {
		configured,
		signedIn: true as const,
		user: session.user,
		unlinked: work?.unlinked ?? true,
		summary: work?.summary ?? null,
		jobs: (work?.jobs ?? []).slice(0, 10).map((j) => {
			const job = j as Record<string, unknown>;
			return {
				id: typeof job["id"] === "string" ? (job["id"] as string) : "",
				title:
					typeof job["title"] === "string"
						? (job["title"] as string)
						: typeof job["name"] === "string"
							? (job["name"] as string)
							: "Job",
				status:
					typeof job["status"] === "string" ? (job["status"] as string) : "",
			};
		}),
	};
}

export async function action({ request }: ActionFunctionArgs) {
	const fd = await request.formData();
	const rating = Number.parseInt(String(fd.get("rating") ?? "5"), 10);
	const title = (String(fd.get("title") ?? "").trim() || undefined) as
		| string
		| undefined;
	const body = String(fd.get("body") ?? "").trim();
	const jobId = (String(fd.get("jobId") ?? "").trim() || undefined) as
		| string
		| undefined;
	if (!body) {
		return { status: "error" as const, message: "Please write a few words." };
	}
	try {
		const res = await submitCustomerReview(request, {
			rating: Math.min(5, Math.max(1, rating)),
			title,
			body,
			jobId,
		});
		return {
			status: "success" as const,
			message: "Thanks! Your review will appear once approved.",
			reviewStatus: res.status,
		};
	} catch {
		return {
			status: "error" as const,
			message:
				"We couldn't submit your review. You may need to sign in again.",
		};
	}
}

export default function MyAccount() {
	const data = useLoaderData<typeof loader>();
	const actionData = useActionData<typeof action>();
	const nav = useNavigation();
	const submitting = nav.state === "submitting";

	return (
		<>
			<SiteHeader />
			<main>
				<section className="section">
					<h1 className="section__title">My account</h1>

					{!data.configured ? (
						<p className="muted">
							Customer accounts aren't connected yet. Set BIAB_AUTH_CALLBACK_URL
							to enable sign-in.
						</p>
					) : !data.signedIn ? (
						<div className="card">
							<p>You're not signed in.</p>
							{/* Auth endpoints are resource routes — use plain links. */}
							<p>
								<a className="biab-btn" href="/api/biab-auth/sign-in">
									Sign in
								</a>{" "}
								<a className="muted" href="/api/biab-auth/sign-up">
									or create an account
								</a>
							</p>
						</div>
					) : (
						<>
							<div className="card">
								<h3>
									{data.user.firstName ?? ""} {data.user.lastName ?? ""}
								</h3>
								<p className="muted">{data.user.email}</p>
								<p>
									<a className="muted" href="/api/biab-auth/sign-out">
										Sign out
									</a>
								</p>
							</div>

							<h2 className="section__subtitle">Your work</h2>
							{data.unlinked ? (
								<p className="muted">
									Your account isn't linked to a customer record yet. New jobs
									and invoices will show here once it is.
								</p>
							) : (
								<>
									{data.summary ? (
										<ul className="stat-row">
											<li>Open jobs: {data.summary.openJobCount}</li>
											<li>Pending quotes: {data.summary.pendingQuoteCount}</li>
											<li>Unpaid invoices: {data.summary.unpaidInvoiceCount}</li>
										</ul>
									) : null}
									{data.jobs.length > 0 ? (
										<ul className="post-list">
											{data.jobs.map((j) => (
												<li key={j.id}>
													<strong>{j.title}</strong>
													{j.status ? (
														<span className="muted"> · {j.status}</span>
													) : null}
												</li>
											))}
										</ul>
									) : (
										<p className="muted">No jobs yet.</p>
									)}
								</>
							)}

							<h2 className="section__subtitle">Leave a review</h2>
							{actionData?.status === "success" ? (
								<p className="muted">{actionData.message}</p>
							) : (
								<Form method="post">
									<label>
										Rating
										<select name="rating" defaultValue="5">
											{[5, 4, 3, 2, 1].map((n) => (
												<option value={n} key={n}>
													{n} star{n === 1 ? "" : "s"}
												</option>
											))}
										</select>
									</label>
									<label>
										Title (optional)
										<input name="title" />
									</label>
									<label>
										Your review
										<textarea name="body" rows={4} required />
									</label>
									{data.jobs.length > 0 ? (
										<label>
											About a job (optional)
											<select name="jobId" defaultValue="">
												<option value="">— none —</option>
												{data.jobs.map((j) => (
													<option value={j.id} key={j.id}>
														{j.title}
													</option>
												))}
											</select>
										</label>
									) : null}
									<button className="biab-btn" type="submit" disabled={submitting}>
										{submitting ? "Submitting…" : "Submit review"}
									</button>
									{actionData?.status === "error" ? (
										<p className="error">{actionData.message}</p>
									) : null}
								</Form>
							)}
						</>
					)}
				</section>
			</main>
		</>
	);
}
