// Tanstack-Start-Solid/solid/src/routes/services.$service.$area.tsx
import { createFileRoute, Link } from "@tanstack/solid-router";
import { Show } from "solid-js";

import { renderServiceAreaPage } from "../lib/biab-server-fns";

/**
 * Programmatic SEO page: /services/[service]/[area]. SSR-rendered — the
 * loader calls `parallelPages.render("service-area", { service, area })`,
 * which resolves all tokens server-side in BIAB. The `head` callback
 * lifts the returned meta (title / description / canonical) into the
 * document head so crawlers see fully-resolved tags. Suspended-billing
 * orgs degrade to a minimal "unavailable" state.
 */
export const Route = createFileRoute("/services/$service/$area")({
	component: ServiceAreaPage,
	loader: ({ params }) =>
		renderServiceAreaPage({
			data: { service: params.service, area: params.area },
		}),
	head: ({ loaderData }) => {
		if (!loaderData || !loaderData.ok)
			return { meta: [{ title: "Not found" }] };
		const meta: Array<Record<string, string>> = [
			{ title: loaderData.meta.title },
			{ name: "description", content: loaderData.meta.description },
		];
		const links = loaderData.meta.canonical
			? [{ rel: "canonical", href: loaderData.meta.canonical }]
			: undefined;
		return { meta, ...(links ? { links } : {}) };
	},
});

function ServiceAreaPage() {
	const result = Route.useLoaderData();
	const reason = () => {
		const r = result();
		return r.ok ? null : r.reason;
	};

	return (
		<main>
			<section class="biab-section biab-section--narrow">
				<Link
					to="/services"
					class="biab-section__eyebrow"
					style="display: inline-block; margin-bottom: 1rem;"
				>
					← All areas
				</Link>

				<Show
					when={result().ok}
					fallback={
						<div class="biab-empty">
							<Show
								when={reason() === "suspended"}
								fallback={<>This page isn't available.</>}
							>
								This page is temporarily unavailable. Please check back soon.
							</Show>
						</div>
					}
				>
					{(() => {
						const r = result();
						if (!r.ok) return null;
						const body = r.body as {
							PageTitle?: string;
							PageHeadline?: string;
							intro?: string;
						} | null;
						return (
							<>
								<h1 class="biab-section__title" style="text-align: left;">
									{r.meta.title.split(" | ")[0]}
								</h1>
								<p class="biab-section__sub" style="margin: 0.75rem 0 2rem;">
									{r.meta.description}
								</p>
								<Show
									when={body?.PageTitle || body?.PageHeadline || body?.intro}
								>
									<div class="biab-card" style="padding: 1.5rem;">
										<Show when={body?.PageTitle}>
											<h2 style="font-size: 1.25rem; margin-bottom: 0.5rem;">
												{body?.PageTitle}
											</h2>
										</Show>
										<Show when={body?.PageHeadline}>
											<p style="margin-bottom: 0.75rem;">
												{body?.PageHeadline}
											</p>
										</Show>
										<Show when={body?.intro}>
											<p>{body?.intro}</p>
										</Show>
									</div>
								</Show>
							</>
						);
					})()}
				</Show>
			</section>
		</main>
	);
}

// Remix/app/routes/services.$service.$area.tsx
import { Link, useLoaderData } from "react-router";
import { data } from "react-router";
import type { LoaderFunctionArgs, MetaFunction } from "react-router";

import { SiteHeader } from "~/components/SiteHeader";
import { renderServiceArea } from "~/lib/biab-pages.server";
import { isServiceSuspended } from "~/lib/biab.server";

/**
 * Programmatic SEO page — one URL per (service × area) declared in
 * `biab.config.ts`'s `defineParallelPage`. The high-level
 * `client.parallelPages.render("service-area", { service, area })` returns
 * fully token-resolved `meta` + `body` (token expansion happens server-side
 * inside BIAB), so crawlers see complete HTML.
 */

export const meta: MetaFunction<typeof loader> = ({ data: loaderData }) => {
	if (!loaderData || !loaderData.variant) return [{ title: "Not found" }];
	const m = loaderData.variant.meta;
	const tags: ReturnType<MetaFunction> = [
		{ title: m.title },
		{ name: "description", content: m.description },
	];
	if (m.canonical) tags.push({ tagName: "link", rel: "canonical", href: m.canonical });
	if (m.ogImage) tags.push({ property: "og:image", content: m.ogImage });
	return tags;
};

export async function loader({ params }: LoaderFunctionArgs) {
	const service = params["service"]!;
	const area = params["area"]!;
	try {
		const variant = await renderServiceArea(service, area);
		if (!variant) {
			throw data({ message: "Not found" }, { status: 404 });
		}
		const body = (variant.body ?? null) as {
			PageTitle?: string;
			PageHeadline?: string;
		} | null;
		return {
			variant: {
				meta: variant.meta,
				bodyTitle: body?.PageTitle ?? null,
				bodyHeadline: body?.PageHeadline ?? null,
			},
		};
	} catch (err) {
		if (isServiceSuspended(err)) {
			// Surface a 503 so search engines treat the outage as temporary.
			throw data({ message: "Temporarily unavailable" }, { status: 503 });
		}
		throw err;
	}
}

export default function ServiceAreaPage() {
	const { variant } = useLoaderData<typeof loader>();
	const headline = variant.meta.title.split(" | ")[0];
	return (
		<>
			<SiteHeader />
			<main>
				<section className="section">
					<Link className="muted" to="/services">
						← All service areas
					</Link>
					<h1 className="hero__title">{headline}</h1>
					<p className="hero__sub">{variant.meta.description}</p>
					{variant.bodyTitle ? (
						<article className="card">
							<h2>{variant.bodyTitle}</h2>
							{variant.bodyHeadline ? <p>{variant.bodyHeadline}</p> : null}
						</article>
					) : null}
				</section>
			</main>
		</>
	);
}
