// Qwik/src/routes/store/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import {
	type DocumentHead,
	Link,
	routeLoader$,
	useLocation,
	useNavigate,
} from "@builder.io/qwik-city";

import {
	BiabPaymentLapsedError,
	BiabServiceSuspendedError,
} from "@businessdash/sdk";
import type {
	StorefrontCategory,
	StorefrontProductCard,
	StorefrontSort,
} from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import { Stars } from "../../components/biab/Stars";
import { getBiab } from "../../lib/biab";
import {
	formatMoney,
	getCartSnapshot,
	listStoreCategories,
	listStoreProductsWithMeta,
} from "../../lib/biab-store";
import { getCustomerSession } from "../../lib/biab-portal";

const SORT_VALUES: readonly StorefrontSort[] = [
	"featured",
	"newest",
	"price-asc",
	"price-desc",
	"rating-desc",
];

const SORT_LABELS: Record<StorefrontSort, string> = {
	featured: "Featured",
	newest: "Newest",
	"price-asc": "Price: low to high",
	"price-desc": "Price: high to low",
	"rating-desc": "Top rated",
};

/** Parse a `min-max` price param (either side optional) into dollar bounds. */
function parsePrice(raw: string | undefined): {
	minDollars: number | null;
	maxDollars: number | null;
} {
	if (!raw) return { minDollars: null, maxDollars: null };
	const [min, max] = raw.split("-");
	const toNum = (s: string | undefined) => {
		const n = Number((s ?? "").trim());
		return Number.isFinite(n) && s?.trim() ? n : null;
	};
	return { minDollars: toNum(min), maxDollars: toNum(max) };
}

/**
 * Storefront product list. `routeLoader$` reads the filterable catalog
 * server-side via `storefront.listProductsWithMeta` (facets + ratings +
 * badges) plus the category list for the sidebar. Filters are driven by URL
 * search params (`q`, `category`, `price`, `rating`, `sort`). Suspension
 * errors degrade to a minimal "unavailable" state instead of crashing.
 */
export const useStoreData = routeLoader$(async ({ cookie, query }) => {
	const biab = getBiab();
	const empty = {
		configured: false,
		suspended: false,
		items: [] as StorefrontProductCard[],
		categories: [] as StorefrontCategory[],
		categoryCounts: [] as Array<{ categoryId: string; count: number }>,
		priceRange: { minDollars: 0, maxDollars: 0 },
		cartCount: 0,
		signedIn: false,
	} as const;

	if (!biab) return empty;

	const search = query.get("q")?.trim() || undefined;
	const categoryId = query.get("category") || undefined;
	const minRating = query.get("rating") ? Number(query.get("rating")) : undefined;
	const sortParam = query.get("sort") as StorefrontSort | null;
	const sort =
		sortParam && SORT_VALUES.includes(sortParam) ? sortParam : undefined;
	const { minDollars, maxDollars } = parsePrice(query.get("price") ?? undefined);

	try {
		const [meta, categories, cart, session] = await Promise.all([
			listStoreProductsWithMeta({
				...(search ? { search } : {}),
				...(categoryId ? { categoryId } : {}),
				...(minRating ? { minRating } : {}),
				...(sort ? { sort } : {}),
				...(minDollars != null ? { minPriceCents: Math.round(minDollars * 100) } : {}),
				...(maxDollars != null ? { maxPriceCents: Math.round(maxDollars * 100) } : {}),
				limit: 48,
			}),
			listStoreCategories(),
			getCartSnapshot(cookie),
			getCustomerSession(cookie),
		]);

		if (!meta) {
			return { ...empty, configured: true } as const;
		}

		return {
			configured: true,
			suspended: false,
			items: meta.items,
			categories: categories?.items ?? [],
			categoryCounts: meta.categoryCounts,
			priceRange: meta.priceRange,
			cartCount: cart?.itemCount ?? 0,
			signedIn: !!session,
		} as const;
	} catch (err) {
		if (
			err instanceof BiabServiceSuspendedError ||
			err instanceof BiabPaymentLapsedError
		) {
			return { ...empty, configured: true, suspended: true } as const;
		}
		return { ...empty, configured: true } as const;
	}
});

export default component$(() => {
	const data = useStoreData();
	const loc = useLocation();
	const nav = useNavigate();

	const search = loc.url.searchParams.get("q") ?? "";
	const activeCategory = loc.url.searchParams.get("category") ?? "";
	const activeRating = Number(loc.url.searchParams.get("rating") ?? "0");
	const activeSort = (loc.url.searchParams.get("sort") as StorefrontSort) ?? "featured";
	const price = loc.url.searchParams.get("price") ?? "";
	const [minPriceStr = "", maxPriceStr = ""] = price.split("-");

	const minPrice = useSignal(minPriceStr);
	const maxPrice = useSignal(maxPriceStr);

	const hasFilters = Boolean(search || activeCategory || activeRating || price);

	/** Replace one search param (drop when empty/featured) and navigate. */
	const setParam = $(async (key: string, value: string | null) => {
		const params = new URLSearchParams(loc.url.searchParams);
		if (value === null || value === "") params.delete(key);
		else params.set(key, value);
		const qs = params.toString();
		await nav(qs ? `/store?${qs}` : "/store");
	});

	const countByCategory = new Map(
		data.value.categoryCounts.map((c) => [c.categoryId, c.count]),
	);

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} cartCount={data.value.cartCount} />
			<main>
				<section class="biab-section">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Shop</span>
						<h2 class="biab-section__title">Store</h2>
						<p class="biab-section__sub">
							Live products from the BIAB storefront surface. Filter, add to cart,
							and check out via Stripe.
						</p>
					</div>

					{data.value.suspended ? (
						<div class="biab-empty">
							The store is temporarily unavailable. Please check back soon.
						</div>
					) : !data.value.configured ? (
						<div class="biab-empty">
							Store isn't connected yet. Set the BIAB env vars (see
							<code> .env.example</code>) to go live.
						</div>
					) : (
						<div class="store-layout">
							{/* Sidebar — search, categories, price, rating */}
							<aside class="store-sidebar">
								<form
									class="store-filter"
									preventdefault:submit
									onSubmit$={(e) => {
										const fd = new FormData(e.target as HTMLFormElement);
										const q = String(fd.get("q") ?? "").trim();
										setParam("q", q || null);
									}}
								>
									<label class="biab-label" for="store-search">
										Search
									</label>
									<input
										class="biab-input"
										id="store-search"
										name="q"
										placeholder="Search products…"
										type="search"
										value={search}
									/>
								</form>

								{data.value.categories.length > 0 ? (
									<div class="store-filter">
										<p class="store-filter__title">Category</p>
										<ul class="store-filter__list">
											<li>
												<button
													aria-pressed={!activeCategory}
													class="store-filter__link"
													onClick$={() => setParam("category", null)}
													type="button"
												>
													<span>All products</span>
												</button>
											</li>
											{data.value.categories.map((c) => {
												const active = activeCategory === c.id;
												const count = countByCategory.get(c.id) ?? 0;
												return (
													<li key={c.id}>
														<button
															aria-pressed={active}
															class="store-filter__link"
															onClick$={() =>
																setParam("category", active ? null : c.id)
															}
															type="button"
														>
															<span>{c.name}</span>
															<span class="store-filter__count">{count}</span>
														</button>
													</li>
												);
											})}
										</ul>
									</div>
								) : null}

								<form
									class="store-filter"
									preventdefault:submit
									onSubmit$={() => {
										const min = minPrice.value.trim();
										const max = maxPrice.value.trim();
										setParam("price", min || max ? `${min}-${max}` : null);
									}}
								>
									<p class="store-filter__title">Price</p>
									<div class="store-filter__price">
										<input
											bind:value={minPrice}
											class="biab-input"
											inputMode="numeric"
											placeholder={`$${data.value.priceRange.minDollars}`}
										/>
										<span class="store-filter__dash">–</span>
										<input
											bind:value={maxPrice}
											class="biab-input"
											inputMode="numeric"
											placeholder={`$${data.value.priceRange.maxDollars}`}
										/>
									</div>
									<button
										class="biab-btn biab-btn--ghost store-filter__apply"
										type="submit"
									>
										Apply
									</button>
								</form>

								<div class="store-filter">
									<p class="store-filter__title">Rating</p>
									<ul class="store-filter__list">
										{[4, 3, 2].map((r) => {
											const active = activeRating === r;
											return (
												<li key={r}>
													<button
														aria-pressed={active}
														class="store-filter__link"
														onClick$={() =>
															setParam("rating", active ? null : String(r))
														}
														type="button"
													>
														<Stars rating={r} />
														<span class="store-filter__count">&amp; up</span>
													</button>
												</li>
											);
										})}
									</ul>
								</div>

								{hasFilters ? (
									<button
										class="store-filter__clear"
										onClick$={() => nav("/store")}
										type="button"
									>
										Clear all filters
									</button>
								) : null}
							</aside>

							{/* Grid */}
							<div class="store-results">
								<div class="store-results__bar">
									<p class="store-results__count">
										{data.value.items.length}{" "}
										{data.value.items.length === 1 ? "product" : "products"}
									</p>
									<label class="store-results__sort">
										<span>Sort</span>
										<select
											class="biab-select"
											onChange$={(e) =>
												setParam(
													"sort",
													(e.target as HTMLSelectElement).value === "featured"
														? null
														: (e.target as HTMLSelectElement).value,
												)
											}
											value={activeSort}
										>
											{SORT_VALUES.map((s) => (
												<option key={s} value={s}>
													{SORT_LABELS[s]}
												</option>
											))}
										</select>
									</label>
								</div>

								{data.value.items.length === 0 ? (
									<div class="biab-empty">
										No products match these filters. Try clearing a filter or
										broadening your search.
									</div>
								) : (
									<div class="biab-grid-3">
										{data.value.items.map((p) => (
											<Link
												class="biab-card service-card store-card"
												href={`/store/${p.id}`}
												key={p.id}
											>
												<div class="store-card__media">
													{p.coverImage ? (
														<img
															alt={p.name}
															loading="lazy"
															referrerPolicy="no-referrer"
															src={p.coverImage}
														/>
													) : (
														<div class="store-card__placeholder">No image</div>
													)}
													{p.isBestSeller || p.isNew || p.isOnSale ? (
														<div class="store-card__badges">
															{p.isBestSeller ? (
																<span class="biab-badge">Best seller</span>
															) : null}
															{p.isNew ? (
																<span class="biab-badge">New</span>
															) : null}
															{p.isOnSale ? (
																<span class="biab-badge store-card__badge--sale">
																	Sale
																</span>
															) : null}
														</div>
													) : null}
												</div>
												<h3>{p.name}</h3>
												{p.reviewCount > 0 ? (
													<div class="store-card__rating">
														<Stars rating={p.avgRating} />
														<span class="store-card__reviews">
															({p.reviewCount})
														</span>
													</div>
												) : null}
												<div class="store-card__price">
													<span class="service-card__price">
														{p.hasMultipleVariants ? "From " : ""}
														{p.cheapestPriceCents != null
															? formatMoney(p.cheapestPriceCents, "usd")
															: "—"}
													</span>
													{p.isOnSale && p.comparePriceCents != null ? (
														<span class="store-card__compare">
															{formatMoney(p.comparePriceCents, "usd")}
														</span>
													) : null}
												</div>
												{p.isLowStock ? (
													<span class="store-card__lowstock">Low stock</span>
												) : null}
											</Link>
										))}
									</div>
								)}
							</div>
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Store — Your Business",
	meta: [
		{
			name: "description",
			content:
				"Browse and filter products from the BIAB storefront. Server-rendered via routeLoader$ with a visitor-token cart.",
		},
	],
};

// React-Bun/src/pages/Store.tsx
import { useMemo, useState } from "react";

import { biab, money } from "../lib/biab";
import { Link } from "../lib/router";
import { ErrorBox, PageHead, useApi } from "./ui";

type Sort = "featured" | "newest" | "price-asc" | "price-desc" | "rating-desc";

const SORT_LABELS: Record<Sort, string> = {
	featured: "Featured",
	newest: "Newest",
	"price-asc": "Price: low to high",
	"price-desc": "Price: high to low",
	"rating-desc": "Top rated",
};

/** Five-star glyph row from an average rating (supports half stars). */
function Stars({ rating }: { rating: number }) {
	const full = Math.floor(rating);
	const half = rating - full >= 0.5;
	return (
		<span className="product-card__stars" aria-label={`${rating.toFixed(1)} out of 5`}>
			{[0, 1, 2, 3, 4].map((i) => (
				<span key={i}>{i < full ? "★" : i === full && half ? "⯨" : "☆"}</span>
			))}
		</span>
	);
}

export function Store() {
	const [search, setSearch] = useState("");
	const [categoryId, setCategoryId] = useState<string | null>(null);
	const [minRating, setMinRating] = useState<number | null>(null);
	const [minPrice, setMinPrice] = useState("");
	const [maxPrice, setMaxPrice] = useState("");
	const [sort, setSort] = useState<Sort>("featured");

	const minPriceCents = minPrice ? Math.round(Number(minPrice) * 100) : undefined;
	const maxPriceCents = maxPrice ? Math.round(Number(maxPrice) * 100) : undefined;

	const { data, error, loading } = useApi(
		() =>
			biab.storefront.listProductsWithMeta({
				limit: 48,
				...(search ? { search } : {}),
				...(categoryId ? { categoryId } : {}),
				...(minRating != null ? { minRating } : {}),
				...(minPriceCents != null ? { minPriceCents } : {}),
				...(maxPriceCents != null ? { maxPriceCents } : {}),
				sort,
			}),
		[search, categoryId, minRating, minPriceCents, maxPriceCents, sort],
	);
	// Categories load once for the sidebar (id → display name).
	const { data: catData } = useApi(() => biab.storefront.listCategories(), []);

	const items: Record<string, any>[] = data?.items ?? [];
	const categoryCounts: { categoryId: string; count: number }[] = data?.categoryCounts ?? [];
	const priceRange = data?.priceRange as { minDollars: number; maxDollars: number } | undefined;

	const categoryName = useMemo(() => {
		const m = new Map<string, string>();
		for (const c of (catData?.items ?? []) as { id: string; name: string }[]) m.set(c.id, c.name);
		return m;
	}, [catData]);

	const hasFilters = Boolean(
		search || categoryId || minRating != null || minPrice || maxPrice || sort !== "featured",
	);
	const clearFilters = () => {
		setSearch("");
		setCategoryId(null);
		setMinRating(null);
		setMinPrice("");
		setMaxPrice("");
		setSort("featured");
	};

	return (
		<main className="page">
			<PageHead title="Store" sub="Native storefront on the BIAB SDK." />
			<div className="store-layout">
				<aside className="store-sidebar">
					<div className="store-facet">
						<label className="biab-label" htmlFor="store-search">
							Search
						</label>
						<input
							className="biab-input"
							id="store-search"
							type="search"
							placeholder="Search products…"
							value={search}
							onChange={(e) => setSearch(e.target.value)}
						/>
					</div>

					{categoryCounts.length > 0 ? (
						<div className="store-facet">
							<div className="store-facet__title">Categories</div>
							<ul className="store-facet__list">
								<li>
									<button
										type="button"
										className={`store-facet__opt${categoryId === null ? " is-active" : ""}`}
										onClick={() => setCategoryId(null)}
									>
										<span>All products</span>
									</button>
								</li>
								{categoryCounts.map((c) => (
									<li key={c.categoryId}>
										<button
											type="button"
											className={`store-facet__opt${categoryId === c.categoryId ? " is-active" : ""}`}
											onClick={() =>
												setCategoryId(categoryId === c.categoryId ? null : c.categoryId)
											}
										>
											<span>{categoryName.get(c.categoryId) ?? "Category"}</span>
											<span className="store-facet__count">{c.count}</span>
										</button>
									</li>
								))}
							</ul>
						</div>
					) : null}

					<div className="store-facet">
						<div className="store-facet__title">Price</div>
						<div className="store-facet__price">
							<input
								className="biab-input"
								type="number"
								min={0}
								inputMode="decimal"
								placeholder={priceRange ? `$${priceRange.minDollars}` : "Min"}
								value={minPrice}
								onChange={(e) => setMinPrice(e.target.value)}
								aria-label="Minimum price"
							/>
							<span className="store-facet__dash">—</span>
							<input
								className="biab-input"
								type="number"
								min={0}
								inputMode="decimal"
								placeholder={priceRange ? `$${priceRange.maxDollars}` : "Max"}
								value={maxPrice}
								onChange={(e) => setMaxPrice(e.target.value)}
								aria-label="Maximum price"
							/>
						</div>
					</div>

					<div className="store-facet">
						<div className="store-facet__title">Rating</div>
						<div className="store-facet__ratings">
							{[4, 3, 2, 1].map((r) => (
								<button
									key={r}
									type="button"
									className={`store-facet__opt${minRating === r ? " is-active" : ""}`}
									onClick={() => setMinRating(minRating === r ? null : r)}
								>
									<span className="product-card__stars">
										{"★".repeat(r)}
										{"☆".repeat(5 - r)}
									</span>
									<span>&amp; up</span>
								</button>
							))}
						</div>
					</div>

					{hasFilters ? (
						<button type="button" className="btn btn--ghost btn--sm" onClick={clearFilters}>
							Clear filters
						</button>
					) : null}
				</aside>

				<section className="store-results">
					<div className="store-results__bar">
						<span className="muted">
							{loading ? "Loading…" : `${items.length} product${items.length === 1 ? "" : "s"}`}
						</span>
						<label className="store-sort">
							<span className="muted">Sort</span>
							<select
								className="biab-select"
								value={sort}
								onChange={(e) => setSort(e.target.value as Sort)}
							>
								{(Object.keys(SORT_LABELS) as Sort[]).map((s) => (
									<option key={s} value={s}>
										{SORT_LABELS[s]}
									</option>
								))}
							</select>
						</label>
					</div>

					{error ? <ErrorBox error={error} /> : null}
					{data && items.length === 0 ? (
						<p className="biab-empty">
							{hasFilters
								? "No products match these filters."
								: "No products published yet."}
						</p>
					) : null}

					{items.length > 0 ? (
						<div className="product-grid">
							{items.map((p) => (
								<Link
									key={p.id}
									className="product-card"
									to={`/store/${encodeURIComponent(p.id)}`}
								>
									<div className="product-card__media">
										{p.coverImage ? (
											<img
												className="product-card__img"
												src={p.coverImage}
												alt={p.name}
												loading="lazy"
											/>
										) : (
											<div className="product-card__img product-card__img--ph" />
										)}
										<div className="product-card__badges">
											{p.isOnSale ? <span className="biab-badge badge--sale">Sale</span> : null}
											{p.isNew ? <span className="biab-badge">New</span> : null}
											{p.isBestSeller ? (
												<span className="biab-badge">Best seller</span>
											) : null}
											{p.isLowStock ? (
												<span className="biab-badge badge--low">Low stock</span>
											) : null}
										</div>
									</div>
									<div className="product-card__body">
										<div className="product-card__name">{p.name ?? "Product"}</div>
										{p.reviewCount > 0 ? (
											<div className="product-card__rating">
												<Stars rating={p.avgRating} />
												<span className="muted">({p.reviewCount})</span>
											</div>
										) : null}
										<div className="product-card__pricing">
											{p.cheapestPriceCents != null ? (
												<span className="product-card__price">
													{p.hasMultipleVariants ? "From " : ""}
													{money(p.cheapestPriceCents, p.currency)}
												</span>
											) : null}
											{p.isOnSale && p.comparePriceCents != null ? (
												<span className="product-card__compare">
													{money(p.comparePriceCents, p.currency)}
												</span>
											) : null}
										</div>
									</div>
								</Link>
							))}
						</div>
					) : null}
				</section>
			</div>
		</main>
	);
}
