// Qwik/src/routes/store/[id]/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import {
	type DocumentHead,
	Link,
	routeLoader$,
	server$,
	useNavigate,
} from "@builder.io/qwik-city";

import {
	BiabPaymentLapsedError,
	BiabServiceSuspendedError,
} from "@businessdash/sdk";
import type {
	StorefrontAddon,
	StorefrontProductDetail,
	StorefrontRelatedProduct,
	StorefrontReview,
} from "@businessdash/sdk/contracts";

import { Footer } from "../../../components/biab/Footer";
import { SiteHeader } from "../../../components/biab/SiteHeader";
import { Stars } from "../../../components/biab/Stars";
import { getBiab } from "../../../lib/biab";
import {
	addToCart,
	formatMoney,
	getCartSnapshot,
	getStoreProductAddons,
	getStoreProductReviews,
	getStoreRelatedProducts,
} from "../../../lib/biab-store";
import { getCustomerSession } from "../../../lib/biab-portal";

/** A variant row is an untyped passthrough record; pull the fields we render. */
type Variant = {
	id?: string;
	title?: string | null;
	priceCents?: number | null;
	currency?: string | null;
	isLive?: boolean;
};

export const useProduct = routeLoader$(async ({ params, cookie, status }) => {
	const biab = getBiab();
	const empty = {
		configured: false,
		suspended: false,
		product: null as StorefrontProductDetail | null,
		reviews: { items: [] as StorefrontReview[], avgRating: 0, totalCount: 0 },
		addons: [] as StorefrontAddon[],
		related: [] as StorefrontRelatedProduct[],
		cartCount: 0,
		signedIn: false,
	} as const;

	if (!biab) return empty;
	try {
		const [product, reviews, addons, related, cart, session] =
			await Promise.all([
				biab.storefront.getProduct(params.id),
				getStoreProductReviews(params.id, { limit: 20 }),
				getStoreProductAddons(params.id),
				getStoreRelatedProducts(params.id, { limit: 6 }),
				getCartSnapshot(cookie),
				getCustomerSession(cookie),
			]);
		return {
			configured: true,
			suspended: false,
			product: product as StorefrontProductDetail,
			reviews: reviews
				? {
						items: reviews.items,
						avgRating: reviews.avgRating,
						totalCount: reviews.totalCount,
					}
				: { items: [], avgRating: 0, totalCount: 0 },
			addons: addons?.items ?? [],
			related: related?.items ?? [],
			cartCount: cart?.itemCount ?? 0,
			signedIn: !!session,
		} as const;
	} catch (err) {
		if (
			err instanceof BiabServiceSuspendedError ||
			err instanceof BiabPaymentLapsedError
		) {
			return { ...empty, configured: true, suspended: true } as const;
		}
		status(404);
		return { ...empty, configured: true } as const;
	}
});

/**
 * Server RPC: add a (product, variant) to the visitor cart. `this` is the
 * RequestEvent, so we read/write the `biab_cart_visitor` cookie through it.
 * Mutations mint the cookie on first use inside `addToCart`.
 */
const addToCartRpc = server$(async function (
	this,
	input: { productId: string; variantId: string | null; quantity: number },
) {
	return await addToCart(this.cookie, input);
});

export default component$(() => {
	const data = useProduct();
	const nav = useNavigate();
	const product = data.value.product as StorefrontProductDetail | null;
	const variants = (product?.variants ?? []) as Variant[];
	const selectedVariant = useSignal<string>(variants[0]?.id ?? "");
	const adding = useSignal(false);
	const error = useSignal<string | null>(null);

	const handleAdd = $(async () => {
		if (!product) return;
		adding.value = true;
		error.value = null;
		const res = await addToCartRpc({
			productId: product.id,
			variantId: selectedVariant.value || null,
			quantity: 1,
		});
		adding.value = false;
		if (res.ok) {
			await nav("/cart");
		} else {
			error.value = res.error;
		}
	});

	const addToCartProduct = $(async (productId: string) => {
		const res = await addToCartRpc({ productId, variantId: null, quantity: 1 });
		if (res.ok) await nav("/cart");
		else error.value = res.error;
	});

	const image = product?.images?.[0] ?? null;
	const reviews = data.value.reviews;
	const addons = data.value.addons;
	const related = data.value.related;

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} cartCount={data.value.cartCount} />
			<main>
				<section class="biab-section biab-section--narrow">
					{data.value.suspended ? (
						<div class="biab-empty">
							The store is temporarily unavailable. Please check back soon.
						</div>
					) : !product ? (
						<div class="biab-empty">
							Product not found, or the store isn't connected yet.
						</div>
					) : (
						<div class="biab-card" style="padding: 2rem; display: flex; flex-direction: column; gap: 1.25rem;">
							{image ? (
								<img
									alt={product.name}
									src={image}
									style="border-radius: 1rem; aspect-ratio: 4/3; object-fit: cover;"
								/>
							) : null}
							<h1 class="biab-section__title">{product.name}</h1>

							{reviews.totalCount > 0 ? (
								<div class="store-card__rating">
									<Stars rating={reviews.avgRating} />
									<span class="store-card__reviews">
										{reviews.avgRating.toFixed(1)} · {reviews.totalCount}{" "}
										{reviews.totalCount === 1 ? "review" : "reviews"}
									</span>
								</div>
							) : null}

							{variants.length > 1 ? (
								<div>
									<label class="biab-label" for="variant">
										Option
									</label>
									<select
										bind:value={selectedVariant}
										class="biab-select"
										id="variant"
									>
										{variants.map((v, i) => (
											<option key={v.id ?? i} value={v.id ?? ""}>
												{`${v.title ?? `Option ${i + 1}`}${
													typeof v.priceCents === "number"
														? ` · ${formatMoney(v.priceCents, v.currency ?? "usd")}`
														: ""
												}`}
											</option>
										))}
									</select>
								</div>
							) : variants[0] && typeof variants[0].priceCents === "number" ? (
								<div class="service-card__price">
									{formatMoney(
										variants[0].priceCents,
										variants[0].currency ?? "usd",
									)}
								</div>
							) : null}

							<button
								class="biab-btn"
								disabled={adding.value}
								onClick$={handleAdd}
								style="align-self: flex-start;"
								type="button"
							>
								{adding.value ? "Adding…" : "Add to cart"}
							</button>

							{error.value ? (
								<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
									{error.value}
								</div>
							) : null}
						</div>
					)}

					{/* Addons rail — companion / cross-sell ("complete your X") */}
					{product && addons.length > 0 ? (
						<div class="store-detail__block">
							<h2 class="store-detail__heading">Complete your purchase</h2>
							<div class="store-addons">
								{addons.map((a) => (
									<div class="biab-card store-addon" key={a.id}>
										{a.imageUrl ? (
											<img
												alt={a.addonName}
												class="store-addon__img"
												loading="lazy"
												referrerPolicy="no-referrer"
												src={a.imageUrl}
											/>
										) : null}
										<div class="store-addon__body">
											{a.groupLabel ? (
												<span class="biab-badge">{a.groupLabel}</span>
											) : null}
											<h3 class="store-addon__name">{a.addonName}</h3>
											{a.addonDescription ? (
												<p class="store-addon__desc">{a.addonDescription}</p>
											) : null}
											<div class="store-card__price">
												{a.priceCents != null ? (
													<span class="service-card__price">
														{formatMoney(a.priceCents, "usd")}
													</span>
												) : null}
												{a.originalPriceCents != null &&
												a.priceCents != null &&
												a.originalPriceCents > a.priceCents ? (
													<span class="store-card__compare">
														{formatMoney(a.originalPriceCents, "usd")}
													</span>
												) : null}
											</div>
											<button
												class="biab-btn biab-btn--ghost"
												onClick$={() => addToCartProduct(a.addonProductId)}
												style="align-self: flex-start;"
												type="button"
											>
												Add
											</button>
										</div>
									</div>
								))}
							</div>
						</div>
					) : null}

					{/* Reviews */}
					{product && reviews.items.length > 0 ? (
						<div class="store-detail__block">
							<h2 class="store-detail__heading">
								Reviews{" "}
								<span class="store-detail__heading-sub">
									{reviews.avgRating.toFixed(1)} · {reviews.totalCount}{" "}
									{reviews.totalCount === 1 ? "review" : "reviews"}
								</span>
							</h2>
							<div class="store-reviews">
								{reviews.items.map((r) => (
									<div class="biab-card store-review" key={r.id}>
										<div class="store-review__head">
											<Stars rating={r.rating} />
											{r.reviewerName ? (
												<span class="store-review__author">
													{r.reviewerName}
												</span>
											) : null}
										</div>
										{r.title ? (
											<h3 class="store-review__title">{r.title}</h3>
										) : null}
										{r.body || r.content ? (
											<p class="store-review__body">{r.body ?? r.content}</p>
										) : null}
									</div>
								))}
							</div>
						</div>
					) : null}

					{/* Related grid — "you may also like" */}
					{product && related.length > 0 ? (
						<div class="store-detail__block">
							<h2 class="store-detail__heading">You may also like</h2>
							<div class="biab-grid-3">
								{related.map((p) => (
									<Link
										class="biab-card service-card store-card"
										href={`/store/${p.id}`}
										key={p.id}
									>
										<div class="store-card__media">
											{p.coverImageUrl ? (
												<img
													alt={p.name}
													loading="lazy"
													referrerPolicy="no-referrer"
													src={p.coverImageUrl}
												/>
											) : (
												<div class="store-card__placeholder">No image</div>
											)}
										</div>
										<h3>{p.name}</h3>
										{p.minPriceDollars != null ? (
											<span class="service-card__price">
												{formatMoney(Math.round(p.minPriceDollars * 100), "usd")}
											</span>
										) : null}
									</Link>
								))}
							</div>
						</div>
					) : null}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = ({ resolveValue }) => {
	const data = resolveValue(useProduct);
	const name = data.product?.name ?? "Product";
	return {
		title: `${name} — Your Business`,
		meta: [{ name: "description", content: `${name} — buy now.` }],
	};
};

// Nuxt/app/pages/store/[id].vue
<script setup lang="ts">
import { computed, ref } from "vue";
import BiabHeader from "~/components/biab/BiabHeader.vue";
import BiabFooter from "~/components/biab/BiabFooter.vue";
import { useCart } from "~/composables/useCart";
import type { StoreProductResult } from "../../../server/api/biab/store/product/[id].get";

/**
 * Product detail. Server-renders the product (via the Nitro endpoint),
 * lets the visitor pick a variant if the product has any, and adds it
 * to the visitor-token cart through `useCart`.
 */
const route = useRoute();
const id = route.params.id as string;

const { data } = await useFetch<StoreProductResult>(
	`/api/biab/store/product/${id}`,
);
const product = computed(() => data.value?.product ?? null);

// Variants are loosely typed (`Record<string, unknown>[]`). Pull the
// fields we display defensively.
type LooseVariant = Record<string, unknown>;
const variants = computed<LooseVariant[]>(() =>
	Array.isArray(product.value?.variants) ? product.value.variants : [],
);
const selectedVariantId = ref<string | null>(
	variants.value.length > 0
		? (variants.value[0]?.id as string | undefined) ?? null
		: null,
);

function variantLabel(v: LooseVariant): string {
	return (
		(v.title as string) ?? (v.name as string) ?? (v.id as string) ?? "Variant"
	);
}

const { addItem, error, busy } = useCart();
const added = ref(false);

async function handleAdd() {
	if (!product.value) return;
	added.value = false;
	const ok = await addItem({
		productId: product.value.id,
		variantId: selectedVariantId.value,
		quantity: 1,
	});
	if (ok) added.value = true;
}

useHead(() => ({ title: product.value?.name ?? "Product — Your Business" }));
</script>

<template>
	<div>
		<BiabHeader />
		<main>
			<section class="biab-section biab-section--narrow">
				<p class="store-links">
					<NuxtLink to="/store">← Back to store</NuxtLink>
				</p>

				<div v-if="data?.suspended" class="biab-empty">
					The store is temporarily unavailable. Please check back soon.
				</div>
				<div v-else-if="!product" class="biab-empty">
					This product couldn't be found.
				</div>
				<div v-else class="biab-card product-detail">
					<img
						v-if="product.images && product.images.length"
						:alt="product.name"
						class="product-detail__img"
						:src="product.images[0]"
					/>
					<h1>{{ product.name }}</h1>

					<div v-if="variants.length" class="product-detail__variants">
						<label class="biab-label" for="variant">Option</label>
						<select
							id="variant"
							v-model="selectedVariantId"
							class="biab-select"
						>
							<option
								v-for="v in variants"
								:key="(v.id as string) ?? variantLabel(v)"
								:value="v.id as string"
							>
								{{ variantLabel(v) }}
							</option>
						</select>
					</div>

					<button
						class="biab-btn"
						:disabled="busy"
						style="align-self: flex-start"
						type="button"
						@click="handleAdd"
					>
						{{ busy ? "Adding…" : "Add to cart" }}
					</button>

					<p v-if="added" class="product-detail__added">
						Added to cart. <NuxtLink to="/cart">View cart →</NuxtLink>
					</p>
					<div
						v-if="error"
						style="
							color: var(--danger);
							background: var(--danger-bg);
							padding: 0.75rem 1rem;
							border-radius: 0.5rem;
							font-size: 0.9rem;
						"
					>
						{{ error }}
					</div>
				</div>
			</section>
		</main>
		<BiabFooter />
	</div>
</template>
