// Svelte/src/lib/components/biab/ContactForm.svelte
<!--
  ContactForm — now a thin wrapper around the SDK drop-in <BiabForm>.

  Before, this component hand-rolled the field loop, value state, and submit
  fetch. <BiabForm> (from `@businessdash/sdk/svelte`) replaces all of that: it
  drives the headless form controller, renders every field type / multi-step /
  condition / concurrent-reveal exactly like the BIAB dashboard preview, and
  applies the form's own render settings (animation, progress, org icon).

  Data path (server-safe): the page's `+page.server.ts` already SSR-fetches the
  schema with the server-only BiabClient (`biab.forms.schema(slug)`), so we pass
  that `schema` straight in — no client key in the browser. Submission goes
  through `submitAction`, which POSTs to the existing
  `/api/biab/forms/[slug]` endpoint (which calls `biab.forms.submit` server-side).

  Requires `@businessdash/sdk` >= the release that ships the `./svelte` subpath
  (the version that bundles `src/svelte/BiabForm.svelte`). The package.json here
  already pins `^0.9.7`.
-->
<script lang="ts">
	import {
		BiabForm,
		type BiabFormSubmitAction,
		type FormSchema,
		type FormSubmitResult,
	} from "@businessdash/sdk/svelte";

	let { schema, slug }: { schema: FormSchema; slug: string } = $props();

	// Server-safe submit: forward the re-keyed payload to our own endpoint so the
	// bearer key stays in `$lib/server`. The endpoint returns the SDK's
	// FormSubmitResult JSON, which we hand back so <BiabForm> can show inline
	// field errors on a server-side validation failure.
	const submitAction: BiabFormSubmitAction = async (payload, options) => {
		const res = await fetch(`/api/biab/forms/${encodeURIComponent(slug)}`, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify({
				data: payload,
				submitterEmail:
					(payload.email as string | undefined) ??
					(payload.contactEmail as string | undefined),
				submitterName:
					(payload.name as string | undefined) ??
					(payload.fullName as string | undefined),
				...options,
			}),
		});
		if (!res.ok) {
			// The endpoint throws a 400 with the message on validation failure.
			throw new Error(await res.text());
		}
		return (await res.json()) as FormSubmitResult;
	};
</script>

<section class="biab-section biab-section--narrow" id="contact">
	<div class="biab-section__lead">
		<span class="biab-section__eyebrow">Contact</span>
	</div>
	<div class="biab-card contact">
		<BiabForm
			{schema}
			{slug}
			{submitAction}
			autoComplete
			submitLabel="Send message"
			successMessage="Thanks — we'll be in touch within one business day."
		/>
	</div>
</section>

// Astro/src/components/ContactForm.tsx
import { BiabForm, type BiabFormsClient } from "@businessdash/sdk/react";
import type { FormSchema, FormSubmitResult } from "@businessdash/sdk";

/**
 * Schema-driven contact form as a React island.
 *
 * Drop it into any `.astro` page with a client directive:
 *
 *     ---
 *     import ContactForm from "../components/ContactForm.tsx";
 *     ---
 *     <ContactForm client:load />
 *
 * `<BiabForm>` (from `@businessdash/sdk/react`) renders every field by `type`, runs
 * the same validation BIAB enforces, drives multi-step / conditional / grouped
 * forms, and uses the `biab-*` light-DOM classes this template already styles.
 *
 * It reads/writes through the same-origin `/api/biab/forms/[slug]` endpoint, so
 * the BIAB bearer key never reaches the browser. The `client` below structurally
 * satisfies `BiabFormsClient`.
 *
 * ── Activation ──────────────────────────────────────────────────────────────
 * This island needs React, which the base Astro starter doesn't bundle. To turn
 * it on, add the integration (these touch package.json + astro.config, which the
 * SDK keeps as a consumer choice):
 *
 *     npx astro add react
 *     # installs @astrojs/react + react + react-dom and registers the integration
 *
 * Until then the page falls back to the vanilla `ContactForm.astro` island.
 */
const FORM_SLUG = "general-inquiry";

const biabFormsProxy: BiabFormsClient = {
	forms: {
		async schema(slug: string): Promise<FormSchema> {
			const res = await fetch(`/api/biab/forms/${encodeURIComponent(slug)}`);
			if (!res.ok) throw new Error(`Failed to load form (${res.status}).`);
			return (await res.json()) as FormSchema;
		},
		async submit(
			slug: string,
			data: Record<string, unknown>,
			opts?: Record<string, unknown>,
		): Promise<FormSubmitResult> {
			const res = await fetch(`/api/biab/forms/${encodeURIComponent(slug)}`, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ data, ...opts }),
			});
			return (await res.json()) as FormSubmitResult;
		},
	},
};

export default function ContactForm() {
	return (
		<section className="biab-section biab-section--narrow" id="contact">
			<div className="biab-card contact">
				<BiabForm
					slug={FORM_SLUG}
					client={biabFormsProxy}
					submitLabel="Send message"
					successFallback={() => (
						<div>
							<span
								className="biab-badge"
								style={{ alignSelf: "flex-start" }}
							>
								Received
							</span>
							<h2 className="biab-section__title">Got it.</h2>
							<p>We'll be in touch within one business day.</p>
						</div>
					)}
				/>
			</div>
		</section>
	);
}
