// Tanstack-Start-Solid/solid/src/routes/index.tsx
import { createFileRoute } from "@tanstack/solid-router";

import { About } from "../components/biab/About";
import { Blog } from "../components/biab/Blog";
import { Booking } from "../components/biab/Booking";
import { ContactForm } from "../components/biab/ContactForm";
import { BiabFooter } from "../components/biab/Footer";
import { Gallery } from "../components/biab/Gallery";
import { BiabHeader } from "../components/biab/Header";
import { Hero } from "../components/biab/Hero";
import { NewsBanner } from "../components/biab/NewsBanner";
import { Services } from "../components/biab/Services";
import {
	getHomeData,
	getHomeJsonLd,
	getSiteContentExtras,
} from "../lib/biab-server-fns";

/**
 * `loader` runs `getHomeData` (a `createServerFn`) plus the banner/updates
 * extras and the JSON-LD graph — all server-side, in parallel. The
 * component receives fully-resolved data via `useLoaderData()`. The `head`
 * callback injects the structured-data `<script>` server-side so crawlers
 * see it on first paint.
 */
export const Route = createFileRoute("/")({
	component: App,
	loader: async () => {
		const [home, extras, jsonLd] = await Promise.all([
			getHomeData(),
			getSiteContentExtras(),
			getHomeJsonLd(),
		]);
		return { home, extras, jsonLd };
	},
	head: ({ loaderData }) => {
		const json = loaderData?.jsonLd;
		if (!json) return {};
		return {
			scripts: [{ type: "application/ld+json", children: json }],
		};
	},
});

function App() {
	const data = Route.useLoaderData();
	const home = () => data().home;

	return (
		<>
			<NewsBanner banner={data().extras.banner} />
			<BiabHeader />
			<main>
				<Hero hero={home().hero} />
				<About body={home().about} />
				<Services services={home().services} />
				<Gallery items={home().gallery} />
				<Booking eventTypes={home().eventTypes} />
				<Blog posts={home().blogPosts} />
				<ContactForm schema={home().formSchema} slug={home().formSlug} />
			</main>
			<BiabFooter />
		</>
	);
}

// Svelte/src/routes/+page.svelte
<script lang="ts">
	import About from '$lib/components/biab/About.svelte';
	import Banner from '$lib/components/biab/Banner.svelte';
	import Blog from '$lib/components/biab/Blog.svelte';
	import Booking from '$lib/components/biab/Booking.svelte';
	import ContactForm from '$lib/components/biab/ContactForm.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import Gallery from '$lib/components/biab/Gallery.svelte';
	import Header from '$lib/components/biab/Header.svelte';
	import Hero from '$lib/components/biab/Hero.svelte';
	import Services from '$lib/components/biab/Services.svelte';

	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<!-- Server-rendered LocalBusiness + WebSite JSON-LD (see biab-seo.ts). -->
	{@html data.jsonLd}
</svelte:head>

{#if data.unavailable}
	<Header />
	<main class="biab-section biab-section--narrow">
		<div class="biab-empty">
			<h1 class="biab-section__title" style="margin-bottom: 0.5rem;">
				Site temporarily unavailable
			</h1>
			<p>
				We're updating our billing and will be back shortly. Please check back
				soon.
			</p>
		</div>
	</main>
	<Footer />
{:else}
	<Banner banner={data.banner} />
	<Header />
	<main>
		<Hero hero={data.hero} />
		<About body={data.about} />
		<Services services={data.services} />
		<Gallery items={data.gallery} />
		<Booking eventTypes={data.eventTypes} />
		<Blog posts={data.blogPosts} />
		<ContactForm schema={data.formSchema} slug={data.formSlug} />
	</main>
	<Footer />
{/if}
