// Nuxt/app/pages/services/[service]/[area].vue
<script setup lang="ts">
import { computed } from "vue";
import BiabHeader from "~/components/biab/BiabHeader.vue";
import BiabFooter from "~/components/biab/BiabFooter.vue";
import type { ParallelRenderResult } from "../../../../server/api/biab/parallel/render.get";

/**
 * A single (service × area) parallel page, rendered server-side from
 * BIAB via `parallelPages.render("service-area", { service, area })`.
 * BIAB resolves the brand/service/area tokens, so `meta` + `body` come
 * back fully expanded — crawlers see finished HTML.
 *
 * Failure modes mirror DGP: unknown slug → 404; billing suspended → a
 * minimal "temporarily unavailable" notice with a 503 (set on the
 * server endpoint).
 */
const route = useRoute();
const service = route.params.service as string;
const area = route.params.area as string;

const { data } = await useFetch<ParallelRenderResult>(
	"/api/biab/parallel/render",
	{ query: { key: "service-area", service, area } },
);

const variant = computed(() =>
	data.value?.state === "ok" ? data.value.variant : null,
);
const suspended = computed(() => data.value?.state === "suspended");

// Loose-shaped body (BIAB template output). Pull the common fields.
const body = computed(
	() =>
		(variant.value?.body as
			| { PageTitle?: string; PageHeadline?: string }
			| null
			| undefined) ?? null,
);

// Surface a real 404 status for unknown variants (good for SEO).
if (data.value?.state === "not-found") {
	throw createError({ statusCode: 404, statusMessage: "Page not found" });
}

useHead(() => {
	const meta = variant.value?.meta;
	if (!meta) return { title: "Service area" };
	return {
		title: meta.title,
		meta: [{ name: "description", content: meta.description }],
		link: meta.canonical ? [{ rel: "canonical", href: meta.canonical }] : [],
	};
});
</script>

<template>
	<div>
		<BiabHeader />
		<main>
			<section class="biab-section biab-section--narrow">
				<div v-if="suspended" class="biab-empty">
					This page is temporarily unavailable. Please check back soon.
				</div>
				<template v-else-if="variant">
					<div class="biab-section__lead" style="text-align: left">
						<h1 class="biab-section__title">
							{{ variant.meta.title.split(" | ")[0] }}
						</h1>
						<p class="biab-section__sub" style="margin: 0">
							{{ variant.meta.description }}
						</p>
					</div>
					<div v-if="body?.PageTitle" class="biab-card service-area-body">
						<h2>{{ body.PageTitle }}</h2>
						<p v-if="body.PageHeadline">{{ body.PageHeadline }}</p>
					</div>
					<p class="store-links">
						<NuxtLink to="/services">← All service areas</NuxtLink>
					</p>
				</template>
			</section>
		</main>
		<BiabFooter />
	</div>
</template>

// Qwik/src/routes/services/[service]/[area]/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import {
	BiabPaymentLapsedError,
	BiabServiceSuspendedError,
} from "@businessdash/sdk";

import { Footer } from "../../../../components/biab/Footer";
import { SiteHeader } from "../../../../components/biab/SiteHeader";
import { getBiab } from "../../../../lib/biab";
import { getCustomerSession } from "../../../../lib/biab-portal";

/**
 * One programmatic (service × area) page. `client.parallelPages.render(
 * "service-area", { service, area })` returns `{ meta, body }` with tokens
 * (`{service.type}`, `{area.name}`, …) already resolved server-side by BIAB,
 * so crawlers see fully-rendered HTML.
 *
 * Suspension handling: a fully-suspended org throws `BiabServiceSuspendedError`
 * → we set a 503 and render a minimal unavailable state so search engines
 * treat the outage as temporary.
 */
export const useVariant = routeLoader$(async ({ params, cookie, status }) => {
	const biab = getBiab();
	const session = await getCustomerSession(cookie);
	if (!biab) {
		status(404);
		return { state: "notfound" as const, signedIn: !!session };
	}
	try {
		const rendered = await biab.parallelPages.render("service-area", {
			service: params.service,
			area: params.area,
		});
		return {
			state: "ok" as const,
			meta: rendered.meta,
			body: rendered.body,
			signedIn: !!session,
		};
	} catch (err) {
		if (err instanceof BiabServiceSuspendedError) {
			status(503);
			return { state: "suspended" as const, signedIn: !!session };
		}
		if (err instanceof BiabPaymentLapsedError) {
			status(404);
			return { state: "notfound" as const, signedIn: !!session };
		}
		status(404);
		return { state: "notfound" as const, signedIn: !!session };
	}
});

export default component$(() => {
	const data = useVariant();
	const value = data.value;

	const body =
		value.state === "ok"
			? (value.body as { PageTitle?: string; PageHeadline?: string } | null)
			: null;

	return (
		<>
			<SiteHeader signedIn={value.signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					{value.state === "suspended" ? (
						<div class="biab-empty">
							This page is temporarily unavailable. Please check back soon.
						</div>
					) : value.state === "notfound" ? (
						<div class="biab-empty">Page not found.</div>
					) : (
						<>
							<header class="biab-section__lead" style="text-align: left; align-items: flex-start;">
								<h1 class="biab-section__title">
									{value.meta.title.split(" | ")[0]}
								</h1>
								<p class="biab-section__sub" style="margin: 0;">
									{value.meta.description}
								</p>
							</header>
							{body?.PageTitle ? (
								<div class="biab-card" style="padding: 2rem;">
									<h2>{body.PageTitle}</h2>
									{body.PageHeadline ? (
										<p style="margin-top: 0.75rem;">{body.PageHeadline}</p>
									) : null}
								</div>
							) : null}
						</>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = ({ resolveValue }) => {
	const data = resolveValue(useVariant);
	if (data.state !== "ok") {
		return { title: "Unavailable — Your Business" };
	}
	return {
		title: data.meta.title,
		meta: [{ name: "description", content: data.meta.description }],
		links: data.meta.canonical
			? [{ rel: "canonical", href: data.meta.canonical }]
			: [],
	};
};
