// T3-App/src/app/_components/bd/About.tsx
import { Subscribe } from "./Subscribe";

export function About({ body }: { body: string }) {
	return (
		<section className="bd-section bd-section--narrow" id="about">
			<div className="bd-section__lead">
				<span className="bd-section__eyebrow">About</span>
				<h2 className="bd-section__title">
					Built around how you actually work.
				</h2>
			</div>
			<p
				style={{ color: "var(--text)", fontSize: "1.05rem", textAlign: "center" }}
			>
				{body}
			</p>
			<Subscribe
				className="about__subscribe"
				idPrefix="about-subscribe"
				label="Stay in the loop"
				source="about"
			/>
		</section>
	);
}

// Svelte/src/lib/components/bd/About.svelte
<script lang="ts">
	import Subscribe from '$lib/components/bd/Subscribe.svelte';

	let { body }: { body: string } = $props();
</script>

<section class="bd-section bd-section--narrow" id="about">
	<div class="bd-section__lead">
		<span class="bd-section__eyebrow">About</span>
		<h2 class="bd-section__title">Built around how you actually work.</h2>
	</div>
	<p style="color: var(--text); font-size: 1.05rem; text-align: center;">
		{body}
	</p>
	<div class="about__subscribe">
		<Subscribe
			source="about"
			idPrefix="about-subscribe"
			label="Stay in the loop"
			buttonLabel="Subscribe"
		/>
	</div>
</section>

<style>
	.about__subscribe {
		display: flex;
		justify-content: center;
		margin-top: 2rem;
	}
</style>
