// Nuxt/app/components/bd/Subscribe.vue
<script setup lang="ts">
/**
 * Newsletter signup — wired to BD followers via the browser-safe publishable
 * token. The SAME component powers the footer and the about section (mirroring
 * the DGP `SubscribeStub`), so a visitor sees one consistent signup everywhere.
 *
 * Why the core client (not a hook)? Vue has no `useFollowers` hook — only
 * React/Astro/Remix/T3 do. So we drive `createBdClient(...).followers`
 * directly and reimplement the per-browser "already subscribed" hint ourselves:
 * on a successful `join` we write `{ email, at }` to localStorage under
 * `bd.followers.<siteId>` and read it on mount, exactly like the React hook.
 *
 * Source of truth for "is this visitor subscribed": logged-in → `me(email)`
 * (authoritative, cross-device); anonymous → this per-browser flag. IP is
 * deliberately NOT used. The flag is just a privacy-friendly UX hint so an
 * anonymous visitor isn't shown the form forever; clearing storage re-shows it,
 * and re-subscribing is idempotent (no dupes).
 *
 * Graceful fallback: when the publishable token / site id aren't configured the
 * widget renders a "coming soon" placeholder with identical fields, so the page
 * never breaks in an unconfigured checkout. The token is browser-safe
 * (origin-locked, rate-limited, scoped `followers:self`).
 */
import { createBdClient } from "@businessdash/sdk";
import { computed, onMounted, ref } from "vue";

const props = withDefaults(
	defineProps<{
		/** Label shown above the email field. */
		label?: string;
		placeholder?: string;
		buttonLabel?: string;
		/** Distinguishes where a signup came from (e.g. "footer" / "about"). */
		source?: string;
		/** Unique id prefix so two instances on one page don't collide. */
		idPrefix?: string;
	}>(),
	{
		label: "Subscribe for updates",
		placeholder: "you@example.com",
		buttonLabel: "Subscribe",
		source: "subscribe",
		idPrefix: "subscribe",
	},
);

// Browser-exposed config. The publishable token + site id gate the live path;
// when either is missing we degrade to the placeholder. (`public.*` is inlined
// into the client bundle by Nuxt — these are intentionally browser-safe.)
const config = useRuntimeConfig();
const pk = config.public.bdPublicKey as string | undefined;
const siteId = config.public.bdSiteId as string | undefined;
const rawBaseUrl = config.public.bdPackageApiBaseUrl as string | undefined;
const followersEnabled = Boolean(pk && siteId);

/** The core client appends relative paths to `baseUrl`, so it must already end
 *  in `…/api/package/v1` (mirrors `server/utils/bd.ts#normalizeBaseUrl`). */
function normalizeBaseUrl(input: string): string {
	const next = input.trim().replace(/\/+$/, "");
	if (next.endsWith("/api/package/v1")) return next;
	return `${next}/api/package/v1`;
}

const STORE_PREFIX = "bd.followers.";
const storeKey = computed(() => `${STORE_PREFIX}${siteId ?? ""}`);

type Status = "idle" | "submitting" | "done" | "error";
const status = ref<Status>("idle");
// Per-browser "already subscribed" hint (read on mount; SSR starts false so the
// form renders, then hydration reconciles to the stored value).
const subscribedLocally = ref(false);

onMounted(() => {
	if (typeof window === "undefined") return;
	try {
		const raw = window.localStorage.getItem(storeKey.value);
		subscribedLocally.value = Boolean(
			raw && typeof (JSON.parse(raw) as { email?: unknown }).email === "string",
		);
	} catch {
		subscribedLocally.value = false;
	}
});

function writeLocalFollow(email: string) {
	if (typeof window === "undefined") return;
	try {
		window.localStorage.setItem(
			storeKey.value,
			JSON.stringify({ email, at: Date.now() }),
		);
	} catch {
		// storage disabled / quota — the local hint is best-effort.
	}
}

// Built lazily so the placeholder path never instantiates a client.
let client: ReturnType<typeof createBdClient> | null = null;
function getClient() {
	if (client) return client;
	client = createBdClient({
		apiKey: pk as string,
		siteId: siteId as string,
		baseUrl: normalizeBaseUrl(rawBaseUrl || "https://www.biab.app"),
	});
	return client;
}

async function onSubmit(event: Event) {
	event.preventDefault();
	const form = event.currentTarget as HTMLFormElement;
	const email = String(new FormData(form).get("email") ?? "").trim();
	if (!email) return;

	// Placeholder mode: same fields, just confirm "coming soon".
	if (!followersEnabled) {
		status.value = "done";
		return;
	}

	status.value = "submitting";
	try {
		await getClient().followers.join({ email, source: props.source });
		writeLocalFollow(email);
		status.value = "done";
	} catch {
		status.value = "error";
	}
}

// Anonymous "already subscribed" hint, or a fresh success.
const showSubscribed = computed(
	() => subscribedLocally.value || status.value === "done",
);
const subscribedMessage = computed(() =>
	followersEnabled
		? "You're subscribed — thanks!"
		: "Thanks — newsletter signup is coming soon.",
);
</script>

<template>
	<p v-if="showSubscribed" class="subscribe__done">{{ subscribedMessage }}</p>
	<form v-else class="subscribe" @submit="onSubmit">
		<label class="bd-label subscribe__label" :for="`${idPrefix}-email`">
			{{ label }}
		</label>
		<div class="subscribe__row">
			<input
				:id="`${idPrefix}-email`"
				autocomplete="email"
				class="bd-input subscribe__input"
				:disabled="status === 'submitting'"
				name="email"
				:placeholder="placeholder"
				required
				type="email"
			/>
			<button
				class="bd-btn subscribe__btn"
				:disabled="status === 'submitting'"
				type="submit"
			>
				{{ status === "submitting" ? "Joining…" : buttonLabel }}
			</button>
		</div>
		<p v-if="status === 'error'" class="subscribe__error">
			Couldn't subscribe — please try again.
		</p>
	</form>
</template>

<style scoped>
.subscribe {
	display: flex;
	flex-direction: column;
	gap: 0.5rem;
	max-width: 26rem;
}

.subscribe__row {
	display: flex;
	gap: 0.5rem;
	align-items: stretch;
}

.subscribe__input {
	flex: 1;
	min-width: 0;
}

.subscribe__btn {
	white-space: nowrap;
}

.subscribe__done {
	color: var(--success);
	font-size: 0.9rem;
}

.subscribe__error {
	color: var(--danger);
	font-size: 0.85rem;
}
</style>

// Svelte/src/lib/components/bd/Subscribe.svelte
<!--
  Subscribe — newsletter signup wired to BD followers.

  Browser-safe: it talks to the followers surface (`followers:self`) through a
  PUBLISHABLE token (`pk_…`, origin-locked, rate-limited) via the core client —
  no backend, no bearer key. SvelteKit doesn't ship a `useFollowers` hook, so
  the per-browser "already subscribed" hint is implemented here directly: after
  a successful `join` we persist `{ email, at }` under `bd.followers.<siteId>`
  in localStorage and read it on mount, exactly like `useFollowers` does in
  React (see `@businessdash/sdk/react`).

  Graceful split (mirrors DGP `SubscribeStub`):
    - Live mode (PK + SITE_ID set)  → real join, shows "You're subscribed".
    - Placeholder mode (env unset)  → identical fields, submit shows "coming soon".

  One shared component, used in BOTH the footer and the about section.

  Env (SvelteKit public, `$env/dynamic/public` — dynamic on purpose: the
  static module turns an unset var into a BUILD error, and a fresh clone
  with no .env must still build in placeholder mode):
    PUBLIC_BD_PK                       publishable followers token
    PUBLIC_BD_SITE_ID                  the site UUID
    PUBLIC_BD_PACKAGE_API_BASE_URL     optional, defaults to production apex
-->
<script lang="ts">
	import { onMount } from 'svelte';
	import { createBdClient } from '@businessdash/sdk';
	import { env } from '$env/dynamic/public';

	let {
		label = 'Get updates in your inbox',
		placeholder = 'you@example.com',
		buttonLabel = 'Subscribe',
		/** Tags the follower row so the org sees where they signed up. */
		source = 'subscribe',
		idPrefix = 'subscribe',
	}: {
		label?: string;
		placeholder?: string;
		buttonLabel?: string;
		source?: string;
		idPrefix?: string;
	} = $props();

	// Publishable creds are browser-safe. When unset → placeholder mode so the
	// template still renders in an unconfigured checkout.
	const PK = env.PUBLIC_BD_PK;
	const SITE_ID = env.PUBLIC_BD_SITE_ID;
	const BASE_URL = env.PUBLIC_BD_PACKAGE_API_BASE_URL;
	const enabled = Boolean(PK && SITE_ID);

	const STORE_KEY = `bd.followers.${SITE_ID}`;

	type Status = 'idle' | 'submitting' | 'done' | 'error';
	let status = $state<Status>('idle');
	// Per-browser "already subscribed" hint (anonymous). Read on mount so SSR
	// always renders the form; the client hides it if this browser subscribed.
	let subscribedLocally = $state(false);

	// The core client is constructed lazily (live mode only) and bound to the
	// publishable token. The bearer key never appears here. Guarded on the
	// values themselves (not `enabled`) so TypeScript narrows the dynamic
	// env's string | undefined.
	const client =
		PK && SITE_ID
			? createBdClient({
					apiKey: PK,
					siteId: SITE_ID,
					...(BASE_URL ? { baseUrl: BASE_URL } : {}),
				})
			: null;

	onMount(() => {
		if (!enabled || typeof window === 'undefined') return;
		try {
			const raw = window.localStorage.getItem(STORE_KEY);
			if (raw) {
				const parsed = JSON.parse(raw) as { email?: unknown };
				subscribedLocally = typeof parsed?.email === 'string';
			}
		} catch {
			// storage disabled / quota — the local hint is best-effort.
		}
	});

	function rememberLocally(email: string): void {
		if (typeof window === 'undefined') return;
		try {
			window.localStorage.setItem(STORE_KEY, JSON.stringify({ email, at: Date.now() }));
		} catch {
			// ignore — best-effort UX hint only.
		}
	}

	async function handleSubmit(event: SubmitEvent): Promise<void> {
		event.preventDefault();
		const form = event.currentTarget as HTMLFormElement;
		const email = String(new FormData(form).get('email') ?? '').trim();
		if (!email) return;

		// Placeholder mode: no creds — just acknowledge.
		if (!client) {
			status = 'done';
			return;
		}

		status = 'submitting';
		try {
			await client.followers.join({ email, source });
			rememberLocally(email);
			subscribedLocally = true;
			status = 'done';
		} catch {
			status = 'error';
		}
	}

	const doneMessage = $derived(
		enabled ? "You're subscribed — thanks!" : 'Thanks — newsletter signup is coming soon.',
	);
</script>

{#if subscribedLocally || status === 'done'}
	<p class="subscribe__done">{doneMessage}</p>
{:else}
	<form class="subscribe" onsubmit={handleSubmit}>
		<label class="bd-label" for={`${idPrefix}-email`}>{label}</label>
		<div class="subscribe__row">
			<input
				class="bd-input"
				id={`${idPrefix}-email`}
				name="email"
				type="email"
				autocomplete="email"
				placeholder={placeholder}
				required
				disabled={status === 'submitting'}
			/>
			<button class="bd-btn" type="submit" disabled={status === 'submitting'}>
				{status === 'submitting' ? 'Joining…' : buttonLabel}
			</button>
		</div>
		{#if status === 'error'}
			<p class="subscribe__error">Couldn't subscribe — please try again.</p>
		{/if}
	</form>
{/if}

<style>
	.subscribe {
		display: flex;
		flex-direction: column;
		gap: 0.4rem;
		width: 100%;
		max-width: 26rem;
	}
	.subscribe__row {
		display: flex;
		gap: 0.5rem;
		align-items: stretch;
	}
	.subscribe__row .bd-input {
		flex: 1;
	}
	.subscribe__row .bd-btn {
		white-space: nowrap;
		flex-shrink: 0;
	}
	.subscribe__done {
		color: var(--success);
		font-size: 0.9rem;
		font-weight: 600;
	}
	.subscribe__error {
		color: var(--danger);
		font-size: 0.85rem;
	}
</style>
