// Qwik/src/routes/subscriptions/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$, server$ } from "@builder.io/qwik-city";

import {
	BiabPaymentLapsedError,
	BiabServiceSuspendedError,
} from "@businessdash/sdk";
import type { SubscriptionOffering } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import { getBiab } from "../../lib/biab";
import { formatMoney } from "../../lib/biab-store";
import { getCustomerSession } from "../../lib/biab-portal";

/** Subscription offerings list. Each plan starts its own Stripe checkout. */
export const useSubscriptions = routeLoader$(async ({ cookie }) => {
	const biab = getBiab();
	if (!biab) {
		return { configured: false, suspended: false, items: [], signedIn: false } as const;
	}
	try {
		const [res, session] = await Promise.all([
			biab.subscriptions.list(),
			getCustomerSession(cookie),
		]);
		return {
			configured: true,
			suspended: false,
			items: res.items,
			signedIn: !!session,
		} as const;
	} catch (err) {
		if (
			err instanceof BiabServiceSuspendedError ||
			err instanceof BiabPaymentLapsedError
		) {
			return { configured: true, suspended: true, items: [], signedIn: false } as const;
		}
		return { configured: true, suspended: false, items: [], signedIn: false } as const;
	}
});

const startSubscriptionRpc = server$(async function (this, id: string) {
	const biab = getBiab();
	if (!biab) return { ok: false as const, error: "Plans aren't connected." };
	try {
		const res = await biab.subscriptions.startCheckout(id, {
			successUrl: `${this.url.origin}/store/order?session_id={CHECKOUT_SESSION_ID}`,
			cancelUrl: `${this.url.origin}/subscriptions`,
		});
		return { ok: true as const, url: res.stripeUrl };
	} catch (err) {
		return {
			ok: false as const,
			error: err instanceof Error ? err.message : "Couldn't start checkout.",
		};
	}
});

export default component$(() => {
	const data = useSubscriptions();
	const busy = useSignal<string | null>(null);
	const error = useSignal<string | null>(null);

	const subscribe = $(async (id: string) => {
		busy.value = id;
		error.value = null;
		const res = await startSubscriptionRpc(id);
		busy.value = null;
		if (res.ok) window.location.href = res.url;
		else error.value = res.error;
	});

	const items = data.value.items as SubscriptionOffering[];

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} />
			<main>
				<section class="biab-section">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Memberships</span>
						<h2 class="biab-section__title">Plans</h2>
						<p class="biab-section__sub">
							Recurring offerings from the BIAB subscriptions surface. Each
							subscribe button opens Stripe-hosted checkout.
						</p>
					</div>

					{data.value.suspended ? (
						<div class="biab-empty">
							Plans are temporarily unavailable. Please check back soon.
						</div>
					) : items.length === 0 ? (
						<div class="biab-empty">
							No subscription plans yet. Add some in BIAB at Dashboard →
							Products → Subscriptions.
						</div>
					) : (
						<div class="biab-grid-3">
							{items.map((plan) => (
								<div
									class="biab-card service-card"
									key={plan.id}
								>
									{plan.imageUrl ? (
										<img
											alt={plan.name}
											src={plan.imageUrl}
											style="border-radius: 0.75rem; aspect-ratio: 4/3; object-fit: cover;"
										/>
									) : null}
									<h3>{plan.name}</h3>
									{plan.description ? <p>{plan.description}</p> : null}
									<div class="service-card__price">
										{formatMoney(plan.amountCents, "usd")} / {plan.interval}
									</div>
									<button
										class="biab-btn"
										disabled={busy.value === plan.id}
										onClick$={() => subscribe(plan.id)}
										style="align-self: flex-start; margin-top: 0.5rem;"
										type="button"
									>
										{busy.value === plan.id ? "Working…" : "Subscribe"}
									</button>
								</div>
							))}
						</div>
					)}

					{error.value ? (
						<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; margin-top: 1.5rem;">
							{error.value}
						</div>
					) : null}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Plans — Your Business",
	meta: [
		{ name: "description", content: "Recurring subscription plans via Stripe." },
	],
};

// Svelte/src/routes/store/subscriptions/+page.svelte
<script lang="ts">
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import StoreNav from '$lib/components/biab/StoreNav.svelte';
	import { formatCents } from '$lib/biab/cart-client';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	let busyId = $state<string | null>(null);
	let error = $state<string | null>(null);

	function intervalLabel(interval: string): string {
		return { day: 'day', week: 'week', month: 'mo', year: 'yr' }[interval] ?? interval;
	}

	async function subscribe(id: string) {
		busyId = id;
		error = null;
		try {
			const res = await fetch(
				`/api/biab/subscriptions/${encodeURIComponent(id)}/checkout`,
				{ method: 'POST' },
			);
			const body = (await res.json()) as
				| { ok: true; url: string }
				| { ok: false; error: string };
			if (body.ok) {
				window.location.href = body.url;
				return;
			}
			error = body.error;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Network error.';
		} finally {
			busyId = null;
		}
	}
</script>

<svelte:head><title>Subscriptions</title></svelte:head>

<Header />
<StoreNav cartCount={data.cartCount} />

<main class="biab-section">
	<div class="biab-section__lead">
		<span class="biab-section__eyebrow">Memberships</span>
		<h1 class="biab-section__title">Subscriptions</h1>
		<p class="biab-section__sub">
			Recurring plans from the BIAB subscriptions surface. Checkout hands off to
			Stripe in subscription mode.
		</p>
	</div>

	{#if !data.configured}
		<div class="biab-empty">Store isn't connected.</div>
	{:else if data.subscriptions.length === 0}
		<div class="biab-empty">
			No subscription offerings yet. Create one in the BIAB dashboard and sync it
			to Stripe.
		</div>
	{:else}
		<div class="biab-grid-3">
			{#each data.subscriptions as sub (sub.id)}
				<article class="biab-card sub-card">
					{#if sub.imageUrl}
						<img class="sub-card__img" src={sub.imageUrl} alt={sub.name} loading="lazy" />
					{/if}
					<div class="sub-card__body">
						<h3>{sub.name}</h3>
						{#if sub.description}
							<p>{sub.description}</p>
						{/if}
						<div class="sub-card__price">
							{formatCents(sub.amountCents)}<span> / {intervalLabel(sub.interval)}</span>
						</div>
						<button
							class="biab-btn"
							onclick={() => subscribe(sub.id)}
							disabled={busyId === sub.id}
						>
							{busyId === sub.id ? 'Working…' : 'Subscribe'}
						</button>
					</div>
				</article>
			{/each}
		</div>
	{/if}

	{#if error}
		<div
			style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem; margin-top: 1rem;"
		>
			{error}
		</div>
	{/if}
</main>

<Footer />

<style>
	.sub-card {
		display: flex;
		flex-direction: column;
		overflow: hidden;
	}
	.sub-card__img {
		width: 100%;
		aspect-ratio: 4 / 3;
		object-fit: cover;
	}
	.sub-card__body {
		padding: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 0.6rem;
	}
	.sub-card__body p {
		color: var(--text-muted);
		font-size: 0.9rem;
	}
	.sub-card__price {
		color: var(--accent);
		font-weight: 700;
		font-size: 1.2rem;
	}
	.sub-card__price span {
		color: var(--text-muted);
		font-weight: 500;
		font-size: 0.85rem;
	}
</style>
