// Svelte/src/routes/updates/+page.svelte
<script lang="ts">
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	function formatDate(iso: string | null): string {
		if (!iso) return '';
		const d = new Date(iso);
		return Number.isNaN(d.getTime())
			? ''
			: d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
	}
</script>

<svelte:head><title>Updates</title></svelte:head>

<Header />

<main class="biab-section biab-section--narrow">
	<div class="biab-section__lead">
		<span class="biab-section__eyebrow">News</span>
		<h1 class="biab-section__title">Updates</h1>
		<p class="biab-section__sub">
			Recent posts, syncing from the business profile via BIAB.
		</p>
	</div>

	{#if data.unavailable}
		<div class="biab-empty">Updates are temporarily unavailable.</div>
	{:else if data.updates.length === 0}
		<div class="biab-empty">
			No updates yet. Posts from the connected business profile will appear here.
		</div>
	{:else}
		<div class="updates-list">
			{#each data.updates as update (update.id)}
				<article class="biab-card update-card">
					{#if update.imageUrl}
						<img class="update-card__img" src={update.imageUrl} alt={update.title ?? 'Update'} loading="lazy" />
					{/if}
					<div class="update-card__body">
						{#if update.title}<h3>{update.title}</h3>{/if}
						<p>{update.body}</p>
						<div class="update-card__meta">
							{#if update.postedAt}<span>{formatDate(update.postedAt)}</span>{/if}
							{#if update.kind}<span class="biab-badge">{update.kind}</span>{/if}
							{#if update.link}<a href={update.link} target="_blank" rel="noreferrer">Learn more →</a>{/if}
						</div>
					</div>
				</article>
			{/each}
		</div>
	{/if}
</main>

<Footer />

<style>
	.updates-list {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	.update-card {
		display: flex;
		flex-direction: column;
		overflow: hidden;
	}
	.update-card__img {
		width: 100%;
		max-height: 18rem;
		object-fit: cover;
	}
	.update-card__body {
		padding: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 0.6rem;
	}
	.update-card__meta {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		color: var(--text-muted);
		font-size: 0.8rem;
	}
</style>

// Qwik/src/routes/updates/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import { getBiab } from "../../lib/biab";
import { getUpdatesFromBundle } from "../../lib/biab-content";
import { getCustomerSession } from "../../lib/biab-portal";

/**
 * News / Updates feed. `bundle.updates` is a Google-Business-style posts feed
 * that rides the marketing bundle as an untyped passthrough at 0.9.5; we read
 * it defensively via `getUpdatesFromBundle`.
 */
export const useUpdates = routeLoader$(async ({ cookie }) => {
	const biab = getBiab();
	const session = await getCustomerSession(cookie);
	if (!biab) {
		return { configured: false, items: [], signedIn: !!session };
	}
	const bundle = await biab.marketing
		.getPageBundle({ pageKey: "home", locale: "en" })
		.catch(() => null);
	return {
		configured: true,
		items: getUpdatesFromBundle(bundle),
		signedIn: !!session,
	};
});

function formatDate(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	return Number.isNaN(d.getTime())
		? ""
		: d.toLocaleDateString(undefined, {
				year: "numeric",
				month: "short",
				day: "numeric",
			});
}

export default component$(() => {
	const data = useUpdates();

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">News</span>
						<h2 class="biab-section__title">Updates</h2>
						<p class="biab-section__sub">
							Recent posts, synced from the business profile via the BIAB
							marketing bundle.
						</p>
					</div>

					{!data.value.configured ? (
						<div class="biab-empty">
							Updates aren't connected yet. Set the BIAB env vars to pull them
							in.
						</div>
					) : data.value.items.length === 0 ? (
						<div class="biab-empty">No updates posted yet.</div>
					) : (
						<div style="display: flex; flex-direction: column; gap: 1.25rem;">
							{data.value.items.map((u) => (
								<article class="biab-card" style="padding: 1.5rem;" key={u.id}>
									{u.imageUrl ? (
										<img
											alt={u.title ?? "Update"}
											src={u.imageUrl}
											style="border-radius: 0.75rem; margin-bottom: 1rem; aspect-ratio: 16/9; object-fit: cover;"
										/>
									) : null}
									{u.title ? <h3>{u.title}</h3> : null}
									<p style="margin-top: 0.5rem; white-space: pre-line;">
										{u.body}
									</p>
									<div style="display: flex; justify-content: space-between; align-items: center; margin-top: 0.75rem;">
										<span style="color: var(--text-muted); font-size: 0.8rem;">
											{formatDate(u.postedAt)}
										</span>
										{u.link ? (
											<a class="biab-btn biab-btn--ghost" href={u.link}>
												Learn more
											</a>
										) : null}
									</div>
								</article>
							))}
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Updates — Your Business",
	meta: [{ name: "description", content: "News and updates feed." }],
};
