// React-Bun/src/components/Subscribe.tsx
import { type FormEvent, useState } from "react";

import { useFollowers } from "@businessdash/sdk/react";

/**
 * Newsletter signup wired to BIAB followers.
 *
 * Unlike the rest of this template (which proxies through the Bun server so the
 * bearer key never reaches the browser), the followers/subscribe surface runs
 * directly in the browser via a **publishable token** (`pk_…`): origin-locked,
 * rate-limited, and scoped to `followers:self`. That's why this is the one
 * feature that reads `VITE_`-prefixed env (exposed to the browser bundle) rather
 * than the server-only `BIAB_*` vars in `.env.example`.
 *
 * `useFollowers` (from `@businessdash/sdk/react`) owns the per-browser
 * "already subscribed" hint (`subscribedLocally`, persisted in localStorage),
 * `join`, `leave`, `me`, and `edit`.
 *
 * Graceful fallback: when the publishable token + site id aren't set, the same
 * fields render in a "coming soon" placeholder mode so the page never breaks in
 * an unconfigured checkout. One shared component powers both the footer and the
 * about section.
 *
 * Reads the canonical browser-safe names (`VITE_BIAB_*`, exposed to the
 * bundle via `envPrefix` in vite.config.ts), falling back to the legacy
 * `VITE_BIAB_*` twins so existing setups keep working.
 */

const BIAB_PK = (import.meta.env.VITE_BIAB_PK ??
	import.meta.env.VITE_BIAB_PK) as string | undefined;
const BIAB_SITE_ID = (import.meta.env.VITE_BIAB_SITE_ID ??
	import.meta.env.VITE_BIAB_SITE_ID) as string | undefined;
const BIAB_BASE_URL = (import.meta.env.VITE_BIAB_PACKAGE_API_BASE_URL ??
	import.meta.env.VITE_BIAB_PACKAGE_API_BASE_URL) as string | undefined;
const BIAB_FOLLOWERS_ENABLED = Boolean(BIAB_PK && BIAB_SITE_ID);

export type SubscribeProps = {
	/** Heading/label shown above the field. */
	label?: string;
	placeholder?: string;
	buttonLabel?: string;
	/** Identifies where the signup happened (followers `source`); also the field id prefix. */
	source?: string;
	className?: string;
};

/** Newsletter signup. Live when the publishable token is configured, otherwise a
 *  graceful "coming soon" placeholder with the same fields. */
export function Subscribe(props: SubscribeProps) {
	if (BIAB_FOLLOWERS_ENABLED) {
		return <LiveSubscribe {...props} />;
	}
	return <PlaceholderSubscribe {...props} />;
}

/** Shared field markup (identical look in both modes), using the template's
 *  existing form primitives from index.css. */
function SubscribeFields({
	label = "Get updates in your inbox.",
	placeholder = "you@example.com",
	buttonLabel = "Subscribe",
	source = "subscribe",
	disabled = false,
	onSubmit,
}: SubscribeProps & {
	disabled?: boolean;
	onSubmit: (event: FormEvent<HTMLFormElement>) => void;
}) {
	return (
		<form className="subscribe__form" onSubmit={onSubmit}>
			<label className="biab-label" htmlFor={`${source}-email`}>
				{label}
			</label>
			<div className="subscribe__row">
				<input
					autoComplete="email"
					className="biab-input"
					disabled={disabled}
					id={`${source}-email`}
					name="email"
					placeholder={placeholder}
					required
					type="email"
				/>
				<button
					className="biab-btn"
					disabled={disabled}
					type="submit"
				>
					{buttonLabel}
				</button>
			</div>
		</form>
	);
}

/** Live signup → BIAB followers table via the publishable token. */
function LiveSubscribe(props: SubscribeProps) {
	const followers = useFollowers({
		token: BIAB_PK as string,
		siteId: BIAB_SITE_ID as string,
		...(BIAB_BASE_URL ? { baseUrl: BIAB_BASE_URL } : {}),
	});
	const [status, setStatus] = useState<
		"idle" | "submitting" | "done" | "error"
	>("idle");

	// Anonymous "already subscribed" hint (per-browser) — or a fresh success.
	if (followers.subscribedLocally || status === "done") {
		return (
			<p className={`subscribe__done ${props.className ?? ""}`.trim()}>
				You&apos;re subscribed — thanks!
			</p>
		);
	}

	const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
		event.preventDefault();
		const email = String(
			new FormData(event.currentTarget).get("email") ?? "",
		).trim();
		if (!email) return;
		setStatus("submitting");
		try {
			await followers.join({ email, source: props.source ?? "subscribe" });
			setStatus("done");
		} catch {
			setStatus("error");
		}
	};

	return (
		<div className={`subscribe ${props.className ?? ""}`.trim()}>
			<SubscribeFields
				{...props}
				disabled={status === "submitting"}
				onSubmit={onSubmit}
			/>
			{status === "error" ? (
				<p className="subscribe__error">
					Couldn&apos;t subscribe — please try again.
				</p>
			) : null}
		</div>
	);
}

/** Fallback when BIAB isn't configured (no publishable token). */
function PlaceholderSubscribe(props: SubscribeProps) {
	const [submitted, setSubmitted] = useState(false);
	if (submitted) {
		return (
			<p className={`subscribe__done ${props.className ?? ""}`.trim()}>
				Thanks — newsletter signup is coming soon.
			</p>
		);
	}
	return (
		<div className={`subscribe ${props.className ?? ""}`.trim()}>
			<SubscribeFields
				{...props}
				onSubmit={(event) => {
					event.preventDefault();
					setSubmitted(true);
				}}
			/>
		</div>
	);
}

// Tanstack-Start/solid/src/components/biab/Subscribe.tsx
import { createBiabClient } from "@businessdash/sdk";
import { createMemo, createSignal, onMount, Show } from "solid-js";

/**
 * Newsletter signup wired to BIAB followers.
 *
 * Browser-safe by design: it runs on a BIAB *publishable* token (origin-locked,
 * rate-limited, `followers:self` only) — never the server-side secret key. The
 * three browser-exposed env vars are the same trio the analytics tracker uses
 * in `__root.tsx`: the canonical `VITE_BIAB_*` names (exposed to the
 * bundle via `envPrefix` in vite.config.ts), falling back to the legacy
 * `VITE_BIAB_*` twins so existing setups keep working.
 *
 * Solid has no `useFollowers` hook (that's the React adapter), so this talks to
 * the core client's `followers` resource directly and re-implements the same
 * per-browser "already subscribed" hint the hook keeps internally: a
 * `localStorage` flag under `biab.followers.<siteId>`, written on a successful
 * `join` and read on mount.
 *
 * Graceful fallback (golden rule #2): when the publishable token or site id is
 * unset the component renders a placeholder that POSTs nowhere and just shows a
 * "coming soon" note, so the page still works in an unconfigured checkout. One
 * shared component powers both the footer and the home about block.
 */

const BIAB_PK = (import.meta.env.VITE_BIAB_PK ??
	import.meta.env.VITE_BIAB_PUBLIC_KEY) as string | undefined;
const BIAB_SITE_ID = (import.meta.env.VITE_BIAB_SITE_ID ??
	import.meta.env.VITE_BIAB_SITE_ID) as string | undefined;
const BIAB_BASE_URL = (import.meta.env.VITE_BIAB_PACKAGE_API_BASE_URL ??
	import.meta.env.VITE_BIAB_PACKAGE_API_BASE_URL) as string | undefined;
const BIAB_FOLLOWERS_ENABLED = Boolean(BIAB_PK && BIAB_SITE_ID);

const FOLLOWER_STORE_PREFIX = "biab.followers.";

type LocalFollow = { email: string; at: number };

/** `createBiabClient` concatenates `baseUrl` + path verbatim, so the base must
 *  already carry the `/api/package/v1` suffix. The template's
 *  `VITE_BIAB_PACKAGE_API_BASE_URL` is a bare host (e.g. https://www.biab.app),
 *  so normalize it here — mirrors `normalizeBaseUrl` in `src/lib/biab.ts`. */
function normalizeBaseUrl(input: string): string {
	const next = input.trim().replace(/\/+$/, "");
	if (next.endsWith("/api/package/v1")) return next;
	return `${next}/api/package/v1`;
}

function readLocalFollow(key: string): LocalFollow | null {
	if (typeof window === "undefined") return null;
	try {
		const raw = window.localStorage.getItem(key);
		if (!raw) return null;
		const parsed = JSON.parse(raw) as Partial<LocalFollow>;
		return typeof parsed?.email === "string"
			? { email: parsed.email, at: Number(parsed.at) || 0 }
			: null;
	} catch {
		return null;
	}
}

function writeLocalFollow(key: string, value: LocalFollow): void {
	if (typeof window === "undefined") return;
	try {
		window.localStorage.setItem(key, JSON.stringify(value));
	} catch {
		// storage disabled / quota — the local hint is best-effort.
	}
}

export type SubscribeProps = {
	label?: string;
	placeholder?: string;
	buttonLabel?: string;
	/** Extra class on the wrapping element. */
	class?: string;
	/** `source` tag persisted on the follower row + id-prefix for field ids. */
	source?: string;
};

/** Public entry — live signup when configured, placeholder otherwise. */
export function Subscribe(props: SubscribeProps) {
	return (
		<Show
			when={BIAB_FOLLOWERS_ENABLED}
			fallback={<PlaceholderSubscribe {...props} />}
		>
			<LiveSubscribe {...props} />
		</Show>
	);
}

/** Shared input + button markup (identical look in both modes). */
function SubscribeFields(
	props: SubscribeProps & {
		disabled?: boolean;
		onSubmit: (event: SubmitEvent) => void;
	},
) {
	const idPrefix = () => props.source ?? "subscribe";
	const label = () => props.label ?? "Get updates in your inbox";
	const placeholder = () => props.placeholder ?? "you@example.com";
	const buttonLabel = () => props.buttonLabel ?? "Subscribe";
	return (
		<form class="biab-subscribe" onSubmit={props.onSubmit}>
			<label class="biab-label" for={`${idPrefix()}-email`}>
				{label()}
			</label>
			<div class="biab-subscribe__row">
				<input
					autocomplete="email"
					class="biab-input"
					disabled={props.disabled}
					id={`${idPrefix()}-email`}
					name="email"
					placeholder={placeholder()}
					required
					type="email"
				/>
				<button class="biab-btn" disabled={props.disabled} type="submit">
					{buttonLabel()}
				</button>
			</div>
		</form>
	);
}

/** Live signup → BIAB followers table via the publishable token. */
function LiveSubscribe(props: SubscribeProps) {
	const storeKey = `${FOLLOWER_STORE_PREFIX}${BIAB_SITE_ID}`;
	const client = createMemo(() =>
		createBiabClient({
			apiKey: BIAB_PK as string,
			siteId: BIAB_SITE_ID as string,
			...(BIAB_BASE_URL ? { baseUrl: normalizeBaseUrl(BIAB_BASE_URL) } : {}),
		}),
	);

	// Anonymous "already subscribed" hint (per-browser). Read on mount so SSR and
	// the first client paint agree (localStorage is unavailable during SSR).
	const [subscribedLocally, setSubscribedLocally] = createSignal(false);
	onMount(() => setSubscribedLocally(readLocalFollow(storeKey) !== null));

	const [status, setStatus] = createSignal<
		"idle" | "submitting" | "done" | "error"
	>("idle");

	const onSubmit = async (event: SubmitEvent) => {
		event.preventDefault();
		const form = event.currentTarget as HTMLFormElement;
		const email = String(new FormData(form).get("email") ?? "").trim();
		if (!email) return;
		setStatus("submitting");
		try {
			await client().followers.join({
				email,
				source: props.source ?? "subscribe",
			});
			writeLocalFollow(storeKey, { email, at: Date.now() });
			setSubscribedLocally(true);
			setStatus("done");
		} catch {
			setStatus("error");
		}
	};

	return (
		<Show
			when={!(subscribedLocally() || status() === "done")}
			fallback={
				<p class={`biab-subscribe__note ${props.class ?? ""}`.trim()}>
					You're subscribed — thanks!
				</p>
			}
		>
			<div class={props.class}>
				<SubscribeFields
					{...props}
					disabled={status() === "submitting"}
					onSubmit={onSubmit}
				/>
				<Show when={status() === "error"}>
					<p class="biab-subscribe__error">
						Couldn't subscribe — please try again.
					</p>
				</Show>
			</div>
		</Show>
	);
}

/** Fallback when BIAB isn't configured (no publishable token). */
function PlaceholderSubscribe(props: SubscribeProps) {
	const [submitted, setSubmitted] = createSignal(false);
	return (
		<Show
			when={!submitted()}
			fallback={
				<p class={`biab-subscribe__note ${props.class ?? ""}`.trim()}>
					Thanks — newsletter signup is coming soon.
				</p>
			}
		>
			<div class={props.class}>
				<SubscribeFields
					{...props}
					onSubmit={(event) => {
						event.preventDefault();
						setSubmitted(true);
					}}
				/>
			</div>
		</Show>
	);
}
