// Qwik/src/routes/store/order/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { Footer } from "../../../components/biab/Footer";
import { SiteHeader } from "../../../components/biab/SiteHeader";
import { getBiab } from "../../../lib/biab";
import { getCustomerSession } from "../../../lib/biab-portal";

/**
 * Stripe checkout return page. Stripe sends the shopper here with
 * `?session_id=…`; we look the session up server-side via
 * `checkout.getStatus(sessionId)` and render a paid / pending confirmation.
 */
export const useOrder = routeLoader$(async ({ query, cookie }) => {
	const sessionId = query.get("session_id");
	const session = await getCustomerSession(cookie);
	const biab = getBiab();
	if (!biab || !sessionId) {
		return { status: null, email: null, signedIn: !!session };
	}
	try {
		const res = await biab.checkout.getStatus(sessionId);
		return {
			status: res.paymentStatus,
			email: res.customerEmail,
			signedIn: !!session,
		};
	} catch {
		return { status: null, email: null, signedIn: !!session };
	}
});

export default component$(() => {
	const data = useOrder();
	const paid = data.value.status === "paid";

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-card" style="padding: 2.5rem; display: flex; flex-direction: column; gap: 1rem; align-items: flex-start;">
						<span class="biab-badge">{paid ? "Paid" : "Order"}</span>
						<h1 class="biab-section__title">
							{paid ? "Thank you for your order!" : "Order received"}
						</h1>
						<p>
							{paid
								? `A receipt is on its way${data.value.email ? ` to ${data.value.email}` : ""}.`
								: "We're confirming your payment. You'll get an email shortly."}
						</p>
						<a class="biab-btn biab-btn--ghost" href="/store">
							Continue shopping
						</a>
					</div>
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Order — Your Business",
	meta: [{ name: "description", content: "Order confirmation." }],
};

// T3-App/src/app/store/order/page.tsx
import Link from "next/link";

import { getCheckoutStatus } from "@/server/lib/biab-store";

import { Notice } from "../_components/Notice";
import { usd } from "../_components/store-utils";

export const dynamic = "force-dynamic";

/**
 * Post-checkout return page. Stripe redirects here with `?session_id=…`; we
 * confirm payment via `checkout.getStatus(sessionId)`. The cart is cleared
 * server-side on a paid session, so this just reports the outcome.
 */
export default async function OrderPage({
	searchParams,
}: {
	searchParams: Promise<{ session_id?: string }>;
}) {
	const { session_id } = await searchParams;

	if (!session_id) {
		return (
			<Notice
				body="This page expects a Stripe checkout session id. Start a checkout from your cart."
				title="No order to show"
			/>
		);
	}

	const status = await getCheckoutStatus(session_id);

	if (!status) {
		return (
			<Notice
				body="checkout.getStatus() returned nothing. If you were charged, you'll still receive a receipt by email."
				title="Couldn't load your order"
			/>
		);
	}

	const paid =
		status.paymentStatus === "paid" ||
		status.paymentStatus === "no_payment_required";

	return (
		<div className="biab-section--narrow">
			<div className="biab-card order">
				<span className="biab-badge">{paid ? "Paid" : "Pending"}</span>
				<h1 className="biab-section__title">
					{paid ? "Thanks for your order!" : "Payment pending"}
				</h1>
				<p className="biab-section__sub">
					{paid
						? "Your payment went through. A receipt is on its way to your email."
						: "We haven't confirmed payment yet. Check back shortly."}
				</p>
				<dl className="order__meta">
					{status.amountTotalCents != null ? (
						<div>
							<dt>Total</dt>
							<dd>
								{usd(status.amountTotalCents / 100, status.currency ?? "USD")}
							</dd>
						</div>
					) : null}
					{status.customerEmail ? (
						<div>
							<dt>Email</dt>
							<dd>{status.customerEmail}</dd>
						</div>
					) : null}
				</dl>
				<Link className="biab-btn biab-btn--ghost" href="/store">
					Back to store
				</Link>
			</div>
		</div>
	);
}
