// Qwik/src/components/bd/ContactForm.tsx
import { component$ } from "@builder.io/qwik";
import { server$ } from "@builder.io/qwik-city";
import { BdForm } from "@businessdash/sdk/qwik";
import type {
	FormSchema,
	FormSubmitOptions,
	FormSubmitResult,
} from "@businessdash/sdk/forms";

import { getBd } from "../../lib/bd";

// Re-export the schema type so `routes/index.tsx` keeps its import path. The
// loader hands `<BdForm>` the FULL published schema (nested field tree +
// settings + org icon) — the drop-in renders every field type, multi-step
// progress, conditions, and concurrent reveal, identical to the dashboard
// preview, with no hand-rolled per-field markup here anymore.
export type { FormSchema };

// The form slug to load + submit. Swap for any of your org's form slugs.
const SLUG = "general-inquiry";

/**
 * Server RPC — the actual `forms.submit` round-trip runs ONLY here, so the
 * BD bearer key never enters the client bundle. `<BdForm>` validates +
 * re-keys the payload (id → published output key) in the headless core, then
 * hands us the wire-ready payload to forward through the SDK. The SDK re-runs
 * server-side validation before persisting, so a bad payload fails here without
 * writing anything to BD.
 */
const submitContactForm = server$(async function (
	payload: Record<string, unknown>,
	options: FormSubmitOptions,
): Promise<FormSubmitResult> {
	const bd = getBd();
	if (!bd) {
		return {
			ok: false,
			status: 0,
			reason: "network_error",
			message: "BD is not configured (missing env).",
		};
	}
	return await bd.forms.submit(SLUG, payload, {
		// Recipient hints help BD attribute the lead; the field output keys
		// "email"/"name" come from the published schema.
		submitterEmail:
			typeof payload.email === "string" ? payload.email : undefined,
		submitterName: typeof payload.name === "string" ? payload.name : undefined,
		source: "qwik-starter",
		...options,
	});
});

/**
 * The contact section, now a thin shell around the SDK's `<BdForm>` drop-in.
 * `schema` comes pre-fetched from the page's `routeLoader$` (server-side, no
 * client flicker, key stays server-side); `submit$` delegates the round-trip to
 * the `server$` RPC above. Everything else — values, validation, conditions,
 * multi-step nav, progress, file uploads, the submit lifecycle — lives in the
 * headless core. Style it via the `bd-*` classes in your CSS.
 */
export const ContactForm = component$<{ schema: FormSchema; slug: string }>(
	({ schema }) => {
		return (
			<section class="bd-section bd-section--narrow" id="contact">
				<div class="bd-section__lead">
					<span class="bd-section__eyebrow">Contact</span>
					<h2 class="bd-section__title">{schema.title ?? "Get in touch"}</h2>
					{schema.description ? (
						<p class="bd-section__sub">{schema.description}</p>
					) : null}
				</div>

				<BdForm
					// Autofill is ON by default in 0.9.12 — `<BdForm>` infers a
					// sensible HTML `autocomplete` token per field (name/email/tel/
					// address/…), so browsers offer autofill with no config. Set
					// explicitly here to document intent; pass `autoComplete={false}` to
					// turn it off, or `fieldAutoComplete={{ phone: "tel" }}` to override
					// individual fields.
					autoComplete
					class="bd-card contact"
					schema={schema}
					submit$={submitContactForm}
					submitLabel="Send message"
				>
					{/* Optional override slots — style or replace as you like. */}
					<div q:slot="success" class="bd-form__success">
						<span class="bd-badge">Received</span>
						<h3>Got it.</h3>
						<p>We'll be in touch within one business day.</p>
					</div>
					<div q:slot="loading" class="bd-form__loading">
						Loading form…
					</div>
				</BdForm>
			</section>
		);
	},
);

// Nuxt/app/components/bd/ContactForm.vue
<script setup lang="ts">
/**
 * Contact section — now a thin wrapper around the SDK's <BdForm> drop-in.
 *
 * Before, this component hand-rolled the field loop, the submit fetch, and the
 * confirmation state. Now `@businessdash/sdk/vue`'s <BdForm> owns ALL of that:
 * it renders the full field tree (every field type, condition_block /
 * or_condition, multi-step + progress, concurrent reveal, org icon, animation)
 * straight from the published schema, validates against the same rules the BD
 * server enforces, and manages the submit lifecycle. We just hand it the
 * SSR-prefetched `schema` and a custom `:on-submit`.
 *
 * Why `:on-submit` (and not `:client`)? This starter keeps the BD bearer key
 * SERVER-ONLY (`server/utils/bd.ts`). So instead of giving the browser an SDK
 * client, we let <BdForm> validate locally and hand us the re-keyed wire
 * payload, which we POST through the existing proxy route
 * (`server/api/bd/forms/[slug].post.ts`). The key never reaches the client.
 *
 * The `bd-*` classes <BdForm> emits are already themed by
 * `app/assets/css/bd-tokens.css` (`.bd-input`, `.bd-label`, `.bd-btn`,
 * `.bd-textarea`), so the drop-in inherits the site's look with no extra CSS.
 */
import { BdForm } from "@businessdash/sdk/vue";
import type {
	FormData,
	FormSchema,
	FormSubmitOptions,
	FormSubmitResult,
} from "@businessdash/sdk/vue";

// The SSR endpoint (`server/api/bd/home.get.ts`) prefetches this via
// `bd.forms.schema(FORM_SLUG)`; the SDK's `FormSchema` is the full nested
// tree the renderer needs (a superset of the starter's local minimal type).
const props = defineProps<{ schema: FormSchema; slug: string }>();

/**
 * Custom submit: POST the re-keyed payload to our own Nitro proxy. We surface
 * the proxy's response as a `FormSubmitResult` so <BdForm> can render the
 * exact success / error state inline.
 */
async function handleSubmit(
	payload: FormData,
	opts: FormSubmitOptions,
): Promise<FormSubmitResult> {
	try {
		await $fetch(`/api/bd/forms/${encodeURIComponent(props.slug)}`, {
			method: "POST",
			body: {
				data: payload,
				submitterEmail: opts.submitterEmail,
				submitterName: opts.submitterName,
			},
		});
		return { ok: true, status: 200 };
	} catch (err) {
		const message =
			err && typeof err === "object" && "statusMessage" in err
				? String((err as { statusMessage?: unknown }).statusMessage)
				: err instanceof Error
					? err.message
					: "Couldn't submit. Please try again.";
		return { ok: false, status: 0, reason: "server_error", message };
	}
}
</script>

<template>
	<section id="contact" class="bd-section bd-section--narrow">
		<div class="bd-section__lead">
			<span class="bd-section__eyebrow">Contact</span>
			<h2 class="bd-section__title">
				{{ schema.title ?? "Get in touch" }}
			</h2>
			<p v-if="schema.description" class="bd-section__sub">
				{{ schema.description }}
			</p>
		</div>

		<div class="bd-card contact">
			<!--
				The whole form is now this one tag. Swap `:schema`/`:slug` for any
				published form slug — e.g. drop <BdForm slug="job-application" />
				with a `:client` instead of `:schema` if you expose a browser-safe
				SDK client. Here we stay server-only and submit via `:on-submit`.
			-->
			<!--
				`auto-complete` is ON by default in 0.9.12 — <BdForm> infers a
				sensible HTML autocomplete token per field (name/email/tel/address/…)
				so browsers offer autofill with no config. Passed explicitly here to
				make the intent visible; set `:auto-complete="false"` to disable, or
				`:field-auto-complete="{ phone: 'tel', note: 'off' }"` to override
				individual fields.
			-->
			<BdForm
				:schema="schema"
				:slug="slug"
				:on-submit="handleSubmit"
				:auto-complete="true"
				submit-label="Send message"
			>
				<template #success>
					<span class="bd-badge" style="align-self: flex-start"
						>Received</span
					>
					<h3 class="bd-section__title">Got it.</h3>
					<p>We'll be in touch within one business day.</p>
				</template>
			</BdForm>
		</div>
	</section>
</template>
