// Qwik/src/components/bd/Header.tsx
import { component$ } from "@builder.io/qwik";

export const Header = component$(() => {
	return (
		<header class="app-header">
			<div class="app-header__inner">
				<div class="app-header__brand">Your Business</div>
				<nav>
					<a href="#services">Services</a>
					<a href="#gallery">Gallery</a>
					<a href="#booking">Book</a>
					<a href="#blog">Blog</a>
					<a href="#contact">Contact</a>
				</nav>
			</div>
		</header>
	);
});

// React-Bun/src/components/Header.tsx
import { Link } from "../lib/router";

export function Header() {
	return (
		<header className="app-header">
			<div className="app-header__inner">
				<Link className="app-header__brand" to="/">
					Your Business
				</Link>
				<nav>
					<Link to="/store">Store</Link>
					<Link to="/subscriptions">Plans</Link>
					<Link to="/reviews">Reviews</Link>
					<Link to="/updates">Updates</Link>
					<Link to="/cart">Cart</Link>
					<Link to="/my-account">Account</Link>
				</nav>
			</div>
		</header>
	);
}
