// Nuxt/app/components/biab/NewsBanner.vue
<script setup lang="ts">
import { ref } from "vue";
import type { BannerMessage } from "../../../server/api/biab/home.get";

/**
 * Dismissible news bar driven by `bundle.banner`. Shows the first
 * active message; dismissing it hides the bar for the session. The
 * banner is schedule-aware on the server — by the time messages reach
 * here they're already filtered to the active set.
 */
const props = defineProps<{ messages: BannerMessage[] }>();

const dismissed = ref(false);
const message = props.messages[0] ?? null;
</script>

<template>
	<div
		v-if="message && !dismissed"
		class="news-banner"
		:class="{ 'news-banner--urgent': message.urgent }"
		role="region"
		aria-label="Announcement"
	>
		<span class="news-banner__text">{{ message.text }}</span>
		<a
			v-if="message.linkUrl"
			class="news-banner__link"
			:href="message.linkUrl"
			:rel="message.openInNewTab ? 'noopener' : undefined"
			:target="message.openInNewTab ? '_blank' : undefined"
		>
			{{ message.buttonText || "Learn more" }}
		</a>
		<button
			aria-label="Dismiss announcement"
			class="news-banner__close"
			type="button"
			@click="dismissed = true"
		>
			×
		</button>
	</div>
</template>

// T3-App/src/app/_components/biab/NewsBanner.tsx
"use client";

import { useEffect, useState } from "react";

import type { BundleBanner } from "@/server/lib/biab";

/**
 * Dismissible news banner fed by `bundle.banner`. Cycles through the org's
 * active messages (one strip, first message shown; the rest accessible if you
 * add navigation later). Dismissal is remembered for the session via
 * sessionStorage so a refresh doesn't re-show it.
 */
export function NewsBanner({ banner }: { banner: BundleBanner | null }) {
	const [dismissed, setDismissed] = useState(true);

	const first = banner?.messages[0] ?? null;
	const key = first ? `biab-banner-dismissed:${first.id}` : null;

	useEffect(() => {
		if (!key) return;
		setDismissed(sessionStorage.getItem(key) === "1");
	}, [key]);

	if (!first || dismissed) return null;

	function dismiss() {
		if (key) sessionStorage.setItem(key, "1");
		setDismissed(true);
	}

	return (
		<div
			className={`news-banner${first.urgent ? "news-banner--urgent" : ""}`}
			role="status"
		>
			<span className="news-banner__text">{first.text}</span>
			{first.linkUrl ? (
				<a
					className="news-banner__cta"
					href={first.linkUrl}
					rel={first.openInNewTab ? "noreferrer" : undefined}
					target={first.openInNewTab ? "_blank" : undefined}
				>
					{first.buttonText || "Learn more"}
				</a>
			) : null}
			<button
				aria-label="Dismiss"
				className="news-banner__close"
				onClick={dismiss}
				type="button"
			>
				×
			</button>
		</div>
	);
}
