// Svelte/src/routes/todos/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import type { ActionData, PageData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	let submitting = $state(false);
</script>

<svelte:head><title>Todos</title></svelte:head>

<Header />

<main class="biab-section biab-section--narrow">
	<div class="biab-section__lead">
		<span class="biab-section__eyebrow">Custom collections</span>
		<h1 class="biab-section__title">Todos</h1>
		<p class="biab-section__sub">
			A relational custom-collections demo — todos and their images live in your BIAB custom
			database.
		</p>
	</div>

	<form
		class="biab-card todo-form"
		method="POST"
		use:enhance={() => {
			submitting = true;
			return async ({ update }) => {
				submitting = false;
				await update();
			};
		}}
	>
		<label class="todo-form__label" for="todo-title">Title</label>
		<input
			id="todo-title"
			name="title"
			class="todo-form__input"
			placeholder="What needs doing?"
			required
		/>
		<label class="todo-form__label" for="todo-notes">Notes (optional)</label>
		<textarea id="todo-notes" name="notes" class="todo-form__input" rows="2"></textarea>
		<button class="todo-form__btn" disabled={submitting} type="submit">
			{submitting ? 'Adding…' : 'Add todo'}
		</button>
		{#if form && 'message' in form && form.message}
			<p class="todo-form__msg todo-form__msg--error">{form.message}</p>
		{:else if form?.added}
			<p class="todo-form__msg">Added.</p>
		{/if}
	</form>

	{#if !data.available}
		<div class="biab-empty">
			{data.reason ??
				"Todos aren't readable yet — sync + promote biab.data-model.config.ts and check your key's scopes."}
		</div>
	{:else if data.todos.length === 0}
		<div class="biab-empty">No todos yet — add the first one.</div>
	{:else}
		<ul class="todo-list">
			{#each data.todos as todo (todo.id)}
				<li class="biab-card todo-item">
					<div class="todo-item__head">
						<span class="todo-item__mark">{todo.done ? '✓' : '○'}</span>
						<strong class="todo-item__title" class:todo-item__title--done={todo.done}>
							{todo.title}
						</strong>
					</div>
					{#if todo.notes}<p class="todo-item__notes">{todo.notes}</p>{/if}
					{#if todo.images.length}
						<div class="todo-item__images">
							{#each todo.images as image, i (i)}
								<figure class="todo-item__figure">
									<img
										class="todo-item__img"
										src={image.url}
										alt={image.alt ?? image.label ?? todo.title}
										loading="lazy"
									/>
									{#if image.label}<figcaption>{image.label}</figcaption>{/if}
								</figure>
							{/each}
						</div>
					{/if}
				</li>
			{/each}
		</ul>
	{/if}
</main>

<Footer />

<style>
	.todo-form {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		padding: 1.25rem;
		margin-bottom: 1.5rem;
	}
	.todo-form__label {
		font-weight: 600;
		font-size: 0.875rem;
	}
	.todo-form__input {
		border: 1px solid var(--biab-border, #d4d4d8);
		border-radius: 0.5rem;
		padding: 0.5rem 0.75rem;
		font: inherit;
	}
	.todo-form__btn {
		align-self: flex-start;
		margin-top: 0.5rem;
		border: none;
		border-radius: 0.5rem;
		padding: 0.55rem 1.1rem;
		background: var(--biab-accent, #047857);
		color: #fff;
		font-weight: 600;
		cursor: pointer;
	}
	.todo-form__btn:disabled {
		opacity: 0.6;
		cursor: wait;
	}
	.todo-form__msg {
		font-size: 0.875rem;
	}
	.todo-form__msg--error {
		color: #b91c1c;
	}
	.todo-list {
		list-style: none;
		margin: 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	.todo-item {
		padding: 1.25rem;
	}
	.todo-item__head {
		display: flex;
		align-items: baseline;
		gap: 0.5rem;
	}
	.todo-item__title--done {
		text-decoration: line-through;
		opacity: 0.6;
	}
	.todo-item__notes {
		margin: 0.5rem 0 0;
		color: var(--biab-muted, #52525b);
	}
	.todo-item__images {
		display: flex;
		flex-wrap: wrap;
		gap: 0.75rem;
		margin-top: 0.75rem;
	}
	.todo-item__figure {
		margin: 0;
	}
	.todo-item__img {
		width: 7rem;
		height: 7rem;
		object-fit: cover;
		border-radius: 0.5rem;
	}
</style>

// Nuxt/app/pages/todos.vue
<script setup lang="ts">
import BiabHeader from "~/components/biab/BiabHeader.vue";
import BiabFooter from "~/components/biab/BiabFooter.vue";
import type { TodosPayload } from "../../server/api/biab/todos.get";

// Slug of the generated create form — see TODO_FORM_SLUG in
// `biab.data-model.config.ts`. Kept as a local literal so the schema config
// (which imports the SDK's schema pipeline) never enters the client bundle.
const TODO_FORM_SLUG = "todo-form";

/**
 * Todos — the relational custom-collections demo (`biab.data-model.config.ts`).
 *
 * READ: `/api/biab/todos` lists both collections via the SDK's
 * `dataModel.listRecords({ object })` and joins images to todos through the
 * `todo` RELATION field.
 * WRITE: submitting the generated "Todo Form" (slug `todo-form`) through the
 * existing `/api/biab/forms/[slug]` proxy — forms are the SDK's documented
 * create path for custom collections; there is no direct row-write surface.
 */
const { data, refresh } = await useFetch<TodosPayload>("/api/biab/todos");

const title = ref("");
const notes = ref("");
const submitting = ref(false);
const message = ref<string | null>(null);
const failed = ref(false);

async function addTodo() {
	if (!title.value.trim() || submitting.value) return;
	submitting.value = true;
	message.value = null;
	failed.value = false;
	try {
		const result = await $fetch<{ ok: boolean; message?: string }>(
			`/api/biab/forms/${TODO_FORM_SLUG}`,
			{
				method: "POST",
				body: {
					// Keyed by each field's output key — `validateFormSubmission`
					// accepts output keys (preferred) or legacy field ids.
					data: { title: title.value.trim(), notes: notes.value.trim() || undefined },
				},
			},
		);
		if (result.ok === false) {
			failed.value = true;
			message.value = result.message ?? "Couldn't add that todo.";
		} else {
			title.value = "";
			notes.value = "";
			message.value = "Added.";
			await refresh();
		}
	} catch (err) {
		failed.value = true;
		message.value =
			err instanceof Error
				? err.message
				: "Couldn't add that todo — is the generated \"Todo Form\" Live?";
	} finally {
		submitting.value = false;
	}
}

useHead({ title: "Todos — Your Business" });
</script>

<template>
	<div>
		<BiabHeader />
		<main>
			<section class="biab-section biab-section--narrow">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Custom collections</span>
					<h1 class="biab-section__title">Todos</h1>
					<p class="biab-section__sub">
						A relational custom-collections demo — todos and their images live
						in your BIAB custom database.
					</p>
				</div>

				<form class="biab-card todo-form" @submit.prevent="addTodo">
					<label class="todo-form__label" for="todo-title">Title</label>
					<input
						id="todo-title"
						v-model="title"
						class="todo-form__input"
						placeholder="What needs doing?"
						required
					/>
					<label class="todo-form__label" for="todo-notes">Notes (optional)</label>
					<textarea
						id="todo-notes"
						v-model="notes"
						class="todo-form__input"
						rows="2"
					></textarea>
					<button class="todo-form__btn" :disabled="submitting" type="submit">
						{{ submitting ? "Adding…" : "Add todo" }}
					</button>
					<p v-if="message" :class="failed ? 'todo-form__msg todo-form__msg--error' : 'todo-form__msg'">
						{{ message }}
					</p>
				</form>

				<div v-if="!data || !data.available" class="biab-empty">
					{{
						data?.reason ??
						"Todos aren't readable yet — sync + promote biab.data-model.config.ts and check your key's scopes."
					}}
				</div>
				<div v-else-if="data.todos.length === 0" class="biab-empty">
					No todos yet — add the first one.
				</div>
				<ul v-else class="todo-list">
					<li v-for="todo in data.todos" :key="todo.id" class="biab-card todo-item">
						<div class="todo-item__head">
							<span class="todo-item__mark">{{ todo.done ? "✓" : "○" }}</span>
							<strong :class="todo.done ? 'todo-item__title todo-item__title--done' : 'todo-item__title'">
								{{ todo.title }}
							</strong>
						</div>
						<p v-if="todo.notes" class="todo-item__notes">{{ todo.notes }}</p>
						<div v-if="todo.images.length" class="todo-item__images">
							<figure v-for="(image, i) in todo.images" :key="i" class="todo-item__figure">
								<img
									:alt="image.alt ?? image.label ?? todo.title"
									class="todo-item__img"
									loading="lazy"
									:src="image.url"
								/>
								<figcaption v-if="image.label">{{ image.label }}</figcaption>
							</figure>
						</div>
					</li>
				</ul>
			</section>
		</main>
		<BiabFooter />
	</div>
</template>

<style scoped>
.todo-form {
	display: flex;
	flex-direction: column;
	gap: 0.5rem;
	padding: 1.25rem;
	margin-bottom: 1.5rem;
}
.todo-form__label {
	font-weight: 600;
	font-size: 0.875rem;
}
.todo-form__input {
	border: 1px solid var(--biab-border, #d4d4d8);
	border-radius: 0.5rem;
	padding: 0.5rem 0.75rem;
	font: inherit;
}
.todo-form__btn {
	align-self: flex-start;
	margin-top: 0.5rem;
	border: none;
	border-radius: 0.5rem;
	padding: 0.55rem 1.1rem;
	background: var(--biab-accent, #047857);
	color: #fff;
	font-weight: 600;
	cursor: pointer;
}
.todo-form__btn:disabled {
	opacity: 0.6;
	cursor: wait;
}
.todo-form__msg {
	font-size: 0.875rem;
}
.todo-form__msg--error {
	color: #b91c1c;
}
.todo-list {
	list-style: none;
	margin: 0;
	padding: 0;
	display: flex;
	flex-direction: column;
	gap: 1rem;
}
.todo-item {
	padding: 1.25rem;
}
.todo-item__head {
	display: flex;
	align-items: baseline;
	gap: 0.5rem;
}
.todo-item__title--done {
	text-decoration: line-through;
	opacity: 0.6;
}
.todo-item__notes {
	margin: 0.5rem 0 0;
	color: var(--biab-muted, #52525b);
}
.todo-item__images {
	display: flex;
	flex-wrap: wrap;
	gap: 0.75rem;
	margin-top: 0.75rem;
}
.todo-item__figure {
	margin: 0;
}
.todo-item__img {
	width: 7rem;
	height: 7rem;
	object-fit: cover;
	border-radius: 0.5rem;
}
</style>
