// T3-App/src/app/_components/bd/Updates.tsx
import type { BundleUpdateItem } from "@/server/lib/bd";

/**
 * News / Updates feed — Google-Business-style posts delivered via
 * `bundle.updates`. Renders nothing when the org has no cached posts (so the
 * home page just skips the section rather than showing an empty block).
 */

function formatDate(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	return Number.isNaN(d.getTime())
		? ""
		: d.toLocaleDateString(undefined, {
				year: "numeric",
				month: "short",
				day: "numeric",
			});
}

export function Updates({ items }: { items: BundleUpdateItem[] }) {
	if (items.length === 0) return null;

	return (
		<section className="bd-section" id="updates">
			<div className="bd-section__lead">
				<span className="bd-section__eyebrow">News</span>
				<h2 className="bd-section__title">Latest updates</h2>
				<p className="bd-section__sub">
					Fresh from our Google Business profile, synced through BD.
				</p>
			</div>
			<div className="bd-grid-3">
				{items.map((u) => {
					const image = u.imageUrl ?? u.images[0] ?? null;
					return (
						<UpdateCard
							body={u.body}
							date={u.postedAt ? formatDate(u.postedAt) : null}
							image={image}
							key={u.id}
							link={u.link}
							title={u.title}
						/>
					);
				})}
			</div>
		</section>
	);
}

function UpdateCard({
	image,
	date,
	title,
	body,
	link,
}: {
	image: string | null;
	date: string | null;
	title: string | null;
	body: string;
	link: string | null;
}) {
	const card = (
		<article className="bd-card update-card">
			{image ? (
				// eslint-disable-next-line @next/next/no-img-element
				<img
					alt={title ?? "Update"}
					className="update-card__img"
					loading="lazy"
					src={image}
				/>
			) : null}
			<div className="update-card__body">
				{date ? <span className="update-card__date">{date}</span> : null}
				{title ? <h3>{title}</h3> : null}
				<p>{body}</p>
			</div>
		</article>
	);
	return link ? (
		<a href={link} rel="noreferrer" target="_blank">
			{card}
		</a>
	) : (
		card
	);
}

// Nuxt/app/pages/updates.vue
<script setup lang="ts">
import BdHeader from "~/components/bd/BdHeader.vue";
import BdFooter from "~/components/bd/BdFooter.vue";
import type { HomeData } from "../../server/api/bd/home.get";

/**
 * News & updates feed. Renders `bundle.updates` (Google-Business-style
 * posts) carried on the marketing bundle and surfaced by the home
 * aggregator. Degrades to an empty state when there are none.
 */
const { data } = await useFetch<HomeData>("/api/bd/home");

function formatDate(iso: string | null | undefined): string {
	if (!iso) return "";
	const d = new Date(iso);
	return Number.isNaN(d.getTime())
		? ""
		: d.toLocaleDateString(undefined, {
				year: "numeric",
				month: "short",
				day: "numeric",
			});
}

useHead({ title: "Updates — Your Business" });
</script>

<template>
	<div>
		<BdHeader />
		<main>
			<section class="bd-section bd-section--narrow">
				<div class="bd-section__lead">
					<span class="bd-section__eyebrow">News</span>
					<h1 class="bd-section__title">Updates</h1>
					<p class="bd-section__sub">
						The latest from us — synced from your Google Business posts.
					</p>
				</div>

				<div v-if="!data || data.updates.length === 0" class="bd-empty">
					No updates yet. Posts you publish to your Google Business profile show
					up here.
				</div>
				<div v-else class="updates-feed">
					<article
						v-for="update in data.updates"
						:key="update.id"
						class="bd-card update-card"
					>
						<img
							v-if="update.imageUrl"
							:alt="update.title ?? 'Update'"
							class="update-card__img"
							:src="update.imageUrl"
						/>
						<div class="update-card__body">
							<span v-if="update.postedAt" class="update-card__date">
								{{ formatDate(update.postedAt) }}
							</span>
							<h3 v-if="update.title">{{ update.title }}</h3>
							<p>{{ update.body }}</p>
							<a
								v-if="update.link"
								:href="update.link"
								rel="noopener"
								target="_blank"
							>
								Learn more →
							</a>
						</div>
					</article>
				</div>
			</section>
		</main>
		<BdFooter />
	</div>
</template>
