// Remix/app/root.tsx
import {
	Links,
	Meta,
	Outlet,
	Scripts,
	ScrollRestoration,
	useLoaderData,
} from "react-router";
import type { LinksFunction, LoaderFunctionArgs } from "react-router";

import { SdkSetupBanner } from "./components/SdkSetupBanner";
import { getAnalyticsConfig } from "./lib/biab.server";
import stylesUrl from "./styles.css?url";
// SDK form styles: file-upload box, multi-step progress header, choice/
// availability chips. Required wherever `<BiabForm>` renders (contact, book).
// The container background is intentionally transparent — the template owns it.
import biabFormsUrl from "@businessdash/sdk/biab-forms.css?url";

export const links: LinksFunction = () => [
	{ rel: "stylesheet", href: stylesUrl },
	{ rel: "stylesheet", href: biabFormsUrl },
];

export async function loader(_: LoaderFunctionArgs) {
	return { analytics: getAnalyticsConfig() };
}

export default function App() {
	const { analytics } = useLoaderData<typeof loader>();
	return (
		<html lang="en">
			<head>
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<Meta />
				<Links />
			</head>
			<body>
				<Outlet />
				<SdkSetupBanner />
				<ScrollRestoration />
				<Scripts />
				{analytics ? (
					<script
						// Server-known config inlined so the public key never lives
						// in the static client bundle. The dynamic-import below
						// reads it after hydration.
						dangerouslySetInnerHTML={{
							__html: `window.__BIAB_ANALYTICS__=${JSON.stringify(analytics)};`,
						}}
					/>
				) : null}
				<script
					type="module"
					dangerouslySetInnerHTML={{
						__html: `
							const cfg = window.__BIAB_ANALYTICS__;
							if (cfg && cfg.siteId && cfg.baseUrl && cfg.apiKey) {
								import("@businessdash/sdk/analytics-core").then(({ initBiabAnalytics }) => {
									initBiabAnalytics({
										siteId: cfg.siteId,
										baseUrl: cfg.baseUrl,
										apiKey: cfg.apiKey,
									});
								});
							}
						`,
					}}
				/>
			</body>
		</html>
	);
}

// Tanstack-Start-Solid/solid/src/routes/__root.tsx
import {
	createRootRouteWithContext,
	HeadContent,
	Outlet,
	Scripts,
} from "@tanstack/solid-router";
import { TanStackRouterDevtools } from "@tanstack/solid-router-devtools";

import "@fontsource/inter/400.css";
// Styles for <BiabForm> (file upload, multi-step progress header, choice chips).
// These surfaces are unstyled without it; imported once, globally.
import "@businessdash/sdk/biab-forms.css";

import { initBiabAnalytics } from "@businessdash/sdk/analytics-core";
import { onCleanup, onMount, Suspense } from "solid-js";
import { HydrationScript } from "solid-js/web";

import Header from "../components/Header";
import { SdkSetupBanner } from "../components/biab/SdkSetupBanner";

import styleCss from "../styles.css?url";

export const Route = createRootRouteWithContext()({
	head: () => ({
		links: [{ rel: "stylesheet", href: styleCss }],
	}),
	shellComponent: RootComponent,
});

function RootComponent() {
	onMount(() => {
		// Canonical VITE_ names (exposed to the browser via envPrefix in
		// vite.config.ts), falling back to the legacy VITE_ twins.
		const siteId = (import.meta.env.VITE_BIAB_SITE_ID ??
			import.meta.env.VITE_BIAB_SITE_ID) as string | undefined;
		const baseUrl = (import.meta.env.VITE_BIAB_PACKAGE_API_BASE_URL ??
			import.meta.env.VITE_BIAB_PACKAGE_API_BASE_URL) as string | undefined;
		const apiKey = (import.meta.env.VITE_BIAB_PK ??
			import.meta.env.VITE_BIAB_PUBLIC_KEY) as string | undefined;
		if (!siteId || !baseUrl || !apiKey) return;
		const tracker = initBiabAnalytics({ siteId, baseUrl, apiKey });
		onCleanup(() => tracker.stop());
	});

	return (
		<html lang="en">
			<head>
				<HydrationScript />
				<HeadContent />
			</head>
			<body>
				<Suspense>
					<Header />
					<Outlet />
					<SdkSetupBanner />
					<TanStackRouterDevtools />
				</Suspense>
				<Scripts />
			</body>
		</html>
	);
}
