// Qwik/src/routes/my-account/index.tsx
import { component$ } from "@builder.io/qwik";
import {
	type DocumentHead,
	Form,
	routeAction$,
	routeLoader$,
	zod$,
	z,
} from "@builder.io/qwik-city";

import type { CustomerWorkBundle } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import {
	getCustomerSession,
	getCustomerWork,
	isCustomerPortalConfigured,
	submitCustomerReview,
} from "../../lib/biab-portal";

/**
 * Customer portal "my account" page.
 *
 *  - `routeLoader$` reads the `biab_session` cookie via `getCustomerSession`
 *    (which calls `getTenantSession`), then loads the work bundle (`getWork`).
 *  - When signed out, we render sign-in / sign-up links to the auth handler.
 *  - `routeAction$` submits a customer review through the portal.
 */
export const useAccount = routeLoader$(async ({ cookie }) => {
	const session = await getCustomerSession(cookie);
	if (!session) {
		return { configured: isCustomerPortalConfigured(), session: null, work: null };
	}
	const work = await getCustomerWork(cookie);
	return {
		configured: true,
		session: {
			email: session.user.email,
			firstName: session.user.firstName,
			lastName: session.user.lastName,
		},
		work,
	};
});

export const useSubmitReview = routeAction$(
	async (data, { cookie }) => {
		try {
			const res = await submitCustomerReview(cookie, {
				rating: data.rating,
				title: data.title || undefined,
				body: data.body,
				jobId: data.jobId || undefined,
			});
			return {
				ok: true as const,
				message:
					"Thanks! Your review was submitted and will appear once it's approved.",
				status: res.status,
			};
		} catch (err) {
			return {
				ok: false as const,
				message:
					err instanceof Error
						? err.message
						: "We couldn't submit your review. You may need to be signed in.",
			};
		}
	},
	zod$({
		rating: z.coerce.number().int().min(1).max(5),
		title: z.string().trim().max(200).optional(),
		body: z.string().trim().min(1, "Please write a few words.").max(5000),
		jobId: z
			.string()
			.uuid()
			.optional()
			.or(z.literal("").transform(() => undefined)),
	}),
);

function WorkSummary({ work }: { work: CustomerWorkBundle }) {
	const s = work.summary;
	return (
		<div class="biab-card" style="padding: 1.5rem; display: flex; gap: 1.5rem; flex-wrap: wrap;">
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.openJobCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Open jobs
				</div>
			</div>
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.pendingQuoteCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Pending quotes
				</div>
			</div>
			<div>
				<div style="font-size: 1.5rem; font-weight: 700; color: var(--title);">
					{s.unpaidInvoiceCount}
				</div>
				<div style="color: var(--text-muted); font-size: 0.85rem;">
					Unpaid invoices
				</div>
			</div>
		</div>
	);
}

export default component$(() => {
	const data = useAccount();
	const review = useSubmitReview();
	const signedIn = !!data.value.session;
	const work = data.value.work;

	return (
		<>
			<SiteHeader signedIn={signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Portal</span>
						<h2 class="biab-section__title">My account</h2>
					</div>

					{!data.value.configured ? (
						<div class="biab-empty">
							Customer accounts aren't connected yet. Set
							<code> BIAB_AUTH_CALLBACK_URL</code> (see .env.example).
						</div>
					) : !signedIn ? (
						<div class="biab-card" style="padding: 2rem; display: flex; flex-direction: column; gap: 1rem; align-items: flex-start;">
							<p>Sign in to view your jobs, quotes, and invoices.</p>
							<div style="display: flex; gap: 0.75rem;">
								<a class="biab-btn" href="/api/biab-auth/sign-in">
									Sign in
								</a>
								<a class="biab-btn biab-btn--ghost" href="/api/biab-auth/sign-up">
									Create account
								</a>
							</div>
						</div>
					) : (
						<div style="display: flex; flex-direction: column; gap: 2rem;">
							<div class="biab-card" style="padding: 1.5rem;">
								<div style="font-weight: 600; color: var(--title);">
									{[data.value.session?.firstName, data.value.session?.lastName]
										.filter(Boolean)
										.join(" ") || "Signed in"}
								</div>
								<div style="color: var(--text-muted);">
									{data.value.session?.email}
								</div>
							</div>

							{work?.unlinked ? (
								<div class="biab-empty">
									Your account isn't linked to a customer record yet. Once we
									connect it, your jobs and invoices will show here.
								</div>
							) : work ? (
								<WorkSummary work={work} />
							) : null}

							{/* Customer review submission */}
							<div class="biab-card" style="padding: 2rem;">
								<h3 style="margin-bottom: 1rem;">Leave a review</h3>
								{review.value?.ok ? (
									<p style="color: var(--success);">
										{review.value.message}
									</p>
								) : (
									<Form
										action={review}
										style="display: flex; flex-direction: column; gap: 1rem;"
									>
										<div>
											<label class="biab-label" for="rating">
												Rating
											</label>
											<select class="biab-select" id="rating" name="rating">
												<option value="5">★★★★★ — Excellent</option>
												<option value="4">★★★★ — Good</option>
												<option value="3">★★★ — Okay</option>
												<option value="2">★★ — Poor</option>
												<option value="1">★ — Bad</option>
											</select>
										</div>
										<div>
											<label class="biab-label" for="title">
												Title (optional)
											</label>
											<input class="biab-input" id="title" name="title" />
										</div>
										<div>
											<label class="biab-label" for="body">
												Your review
											</label>
											<textarea
												class="biab-textarea"
												id="body"
												name="body"
												required
											/>
										</div>
										<button
											class="biab-btn"
											style="align-self: flex-start;"
											type="submit"
										>
											Submit review
										</button>
										{review.value && !review.value.ok ? (
											<div style="color: var(--danger); font-size: 0.9rem;">
												{review.value.message}
											</div>
										) : null}
									</Form>
								)}
							</div>
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "My account — Your Business",
	meta: [
		{
			name: "description",
			content: "Customer portal: jobs, quotes, invoices, and reviews.",
		},
	],
};

// Tanstack-Start-Solid/solid/src/routes/my-account.tsx
import { createFileRoute } from "@tanstack/solid-router";
import { createSignal, Show } from "solid-js";

import { getMyAccount, submitCustomerReview } from "../lib/biab-server-fns";

/**
 * Customer portal home. The loader reads the `biab_session` cookie via
 * `getTenantSession` and, when signed in, pulls the customer's work
 * bundle (`getWork()`). Sign-in / sign-up / sign-out are plain links to
 * the `/api/biab-auth/*` catch-all handler — no client SDK needed. A
 * signed-in customer can submit a review (lands pending for moderation).
 */
export const Route = createFileRoute("/my-account")({
	component: MyAccount,
	loader: () => getMyAccount(),
});

function MyAccount() {
	const data = Route.useLoaderData();
	const session = () => data().session;
	const work = () => data().work;

	return (
		<main>
			<section class="biab-section biab-section--narrow">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Account</span>
					<h1 class="biab-section__title">My account</h1>
				</div>

				<Show
					when={data().configured}
					fallback={
						<div class="biab-empty">
							Customer accounts aren't connected yet. Set{" "}
							<code>BIAB_AUTH_CALLBACK_URL</code> (plus the BIAB API key + base
							URL) in <code>.env</code>.
						</div>
					}
				>
					<Show
						when={session()}
						fallback={
							<div
								class="biab-card"
								style="padding: 2rem; text-align: center; display: flex; flex-direction: column; gap: 1rem; align-items: center;"
							>
								<p>Sign in to view your jobs, quotes, and invoices.</p>
								<div style="display: flex; gap: 0.75rem;">
									<a class="biab-btn" href="/api/biab-auth/sign-in">
										Sign in
									</a>
									<a
										class="biab-btn biab-btn--ghost"
										href="/api/biab-auth/sign-up"
									>
										Create account
									</a>
								</div>
							</div>
						}
					>
						<div
							class="biab-card"
							style="padding: 1.5rem; display: flex; flex-direction: column; gap: 1.25rem;"
						>
							<div style="display: flex; justify-content: space-between; align-items: center; gap: 1rem; flex-wrap: wrap;">
								<div>
									<div style="font-weight: 700; color: var(--title);">
										{[session()?.firstName, session()?.lastName]
											.filter(Boolean)
											.join(" ") ||
											session()?.email ||
											"Signed in"}
									</div>
									<Show when={session()?.email}>
										<div style="font-size: 0.85rem; color: var(--text-muted);">
											{session()?.email}
										</div>
									</Show>
								</div>
								<a
									class="biab-btn biab-btn--ghost"
									href="/api/biab-auth/sign-out"
								>
									Sign out
								</a>
							</div>

							<WorkSummary work={work()} />
						</div>

						<ReviewForm />
					</Show>
				</Show>
			</section>
		</main>
	);
}

function WorkSummary(props: { work: unknown }) {
	const w = props.work as {
		unlinked?: boolean;
		summary?: {
			openJobCount: number;
			pendingQuoteCount: number;
			unpaidInvoiceCount: number;
			awaitingSignatureCount: number;
		};
	} | null;
	return (
		<Show
			when={w && !w.unlinked}
			fallback={
				<div class="biab-empty" style="margin: 0;">
					No work records are linked to this account yet.
				</div>
			}
		>
			<div class="biab-grid-4">
				<Stat label="Open jobs" value={w?.summary?.openJobCount ?? 0} />
				<Stat
					label="Pending quotes"
					value={w?.summary?.pendingQuoteCount ?? 0}
				/>
				<Stat
					label="Unpaid invoices"
					value={w?.summary?.unpaidInvoiceCount ?? 0}
				/>
				<Stat
					label="Awaiting signature"
					value={w?.summary?.awaitingSignatureCount ?? 0}
				/>
			</div>
		</Show>
	);
}

function Stat(props: { label: string; value: number }) {
	return (
		<div class="biab-card" style="padding: 1rem; text-align: center;">
			<div style="font-size: 1.6rem; font-weight: 800; color: var(--accent);">
				{props.value}
			</div>
			<div style="font-size: 0.8rem; color: var(--text-muted);">
				{props.label}
			</div>
		</div>
	);
}

function ReviewForm() {
	const [rating, setRating] = createSignal(5);
	const [title, setTitle] = createSignal("");
	const [body, setBody] = createSignal("");
	const [busy, setBusy] = createSignal(false);
	const [done, setDone] = createSignal<string | null>(null);
	const [error, setError] = createSignal<string | null>(null);

	async function submit(e: Event) {
		e.preventDefault();
		if (!body().trim()) {
			setError("Please write a few words.");
			return;
		}
		setBusy(true);
		setError(null);
		const res = await submitCustomerReview({
			data: { rating: rating(), title: title() || undefined, body: body() },
		});
		setBusy(false);
		if (res.ok) {
			setDone(
				`Thanks! Your review was submitted (${res.status}) and will appear once approved.`,
			);
			setBody("");
			setTitle("");
		} else {
			setError(res.error);
		}
	}

	return (
		<div class="biab-card" style="padding: 1.5rem; margin-top: 1.5rem;">
			<h2 style="font-size: 1.15rem; margin-bottom: 1rem;">Leave a review</h2>
			<Show
				when={!done()}
				fallback={
					<div style="color: var(--success); background: var(--success-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
						{done()}
					</div>
				}
			>
				<form
					onSubmit={submit}
					style="display: flex; flex-direction: column; gap: 1rem;"
				>
					<div>
						<label class="biab-label" for="rating">
							Rating
						</label>
						<select
							id="rating"
							class="biab-select"
							value={String(rating())}
							onChange={(e) => setRating(Number(e.currentTarget.value))}
						>
							<option value="5">★★★★★ (5)</option>
							<option value="4">★★★★ (4)</option>
							<option value="3">★★★ (3)</option>
							<option value="2">★★ (2)</option>
							<option value="1">★ (1)</option>
						</select>
					</div>
					<div>
						<label class="biab-label" for="review-title">
							Title (optional)
						</label>
						<input
							id="review-title"
							class="biab-input"
							value={title()}
							onInput={(e) => setTitle(e.currentTarget.value)}
						/>
					</div>
					<div>
						<label class="biab-label" for="review-body">
							Your review
						</label>
						<textarea
							id="review-body"
							class="biab-textarea"
							value={body()}
							onInput={(e) => setBody(e.currentTarget.value)}
						/>
					</div>
					<button type="submit" class="biab-btn" disabled={busy()}>
						{busy() ? "Submitting…" : "Submit review"}
					</button>
					<Show when={error()}>
						<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
							{error()}
						</div>
					</Show>
				</form>
			</Show>
		</div>
	);
}
