// Svelte/src/routes/reviews/+page.svelte
<script lang="ts">
	import Header from '$lib/components/bd/Header.svelte';
	import Footer from '$lib/components/bd/Footer.svelte';
	import type { ReviewWallItem } from '@businessdash/sdk/contracts';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	// Seed local state from the server's first page, then grow it via "Load
	// more". Intentionally a one-time snapshot of `data`.
	// svelte-ignore state_referenced_locally
	let items = $state<ReviewWallItem[]>(data.items);
	// svelte-ignore state_referenced_locally
	let nextOffset = $state<number | null>(data.nextOffset);
	let loading = $state(false);

	function stars(rating: number): string {
		const full = Math.round(rating);
		return '★'.repeat(full) + '☆'.repeat(Math.max(0, 5 - full));
	}

	function formatDate(iso: string): string {
		const d = new Date(iso);
		return Number.isNaN(d.getTime())
			? ''
			: d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
	}

	async function loadMore() {
		if (nextOffset == null) return;
		loading = true;
		try {
			const res = await fetch(`/api/bd/reviews?limit=10&offset=${nextOffset}`);
			const body = (await res.json()) as {
				items: ReviewWallItem[];
				nextOffset: number | null;
			};
			items = [...items, ...body.items];
			nextOffset = body.nextOffset;
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head><title>Reviews</title></svelte:head>

<Header />

<main class="bd-section bd-section--narrow">
	<div class="bd-section__lead">
		<span class="bd-section__eyebrow">What customers say</span>
		<h1 class="bd-section__title">Reviews</h1>
		{#if data.average != null}
			<p class="bd-section__sub">
				<strong>{data.average.toFixed(1)}</strong>
				average across {data.totalCount} reviews.
			</p>
		{/if}
	</div>

	{#if !data.configured}
		<div class="bd-empty">
			Reviews aren't connected. Once BD is configured, your aggregate rating
			and reviews appear here.
		</div>
	{:else if items.length === 0}
		<div class="bd-empty">No reviews yet.</div>
	{:else}
		<div class="reviews-wall">
			{#each items as review (review.id)}
				<article class="bd-card review-card">
					<div class="review-card__head">
						<strong>{review.reviewerName}</strong>
						<span class="review-card__stars" aria-label={`${review.rating} out of 5`}>
							{stars(review.rating)}
						</span>
					</div>
					<p class="review-card__body">{review.text}</p>
					<div class="review-card__meta">
						<span>{formatDate(review.timeCreated)}</span>
						<span class="bd-badge">{review.source}</span>
						{#if review.verified}<span class="review-card__verified">Verified</span>{/if}
					</div>
				</article>
			{/each}
		</div>

		{#if nextOffset != null}
			<div style="text-align: center; margin-top: 2rem;">
				<button class="bd-btn bd-btn--ghost" onclick={loadMore} disabled={loading}>
					{loading ? 'Loading…' : 'Load more reviews'}
				</button>
			</div>
		{/if}
	{/if}
</main>

<Footer />

<style>
	.reviews-wall {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	.review-card {
		padding: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 0.6rem;
	}
	.review-card__head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 1rem;
	}
	.review-card__stars {
		color: var(--accent);
		letter-spacing: 0.1em;
	}
	.review-card__body {
		color: var(--text);
	}
	.review-card__meta {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		color: var(--text-muted);
		font-size: 0.8rem;
	}
	.review-card__verified {
		color: var(--success);
		font-weight: 600;
	}
</style>

// Tanstack-Start-Solid/solid/src/routes/reviews.tsx
import type { ReviewWallItem } from "@businessdash/sdk/contracts";
import { createFileRoute } from "@tanstack/solid-router";
import { createSignal, For, Show } from "solid-js";

import { fetchReviewsPage, getReviewsWall } from "../lib/bd-server-fns";

/**
 * Reviews wall. The aggregate (average / count) rides the marketing
 * bundle; the first page of wall items comes from `reviews.list`. "Load
 * more" pages forward via the `fetchReviewsPage` server fn until the
 * server returns `nextOffset: null`.
 *
 * Note the two distinct review shapes: the bundle aggregate carries
 * `{ reviewee, description, date }`, while wall items are
 * `{ reviewerName, text, timeCreated }`. We render the wall items here.
 */
export const Route = createFileRoute("/reviews")({
	component: ReviewsWall,
	loader: () => getReviewsWall(),
});

function stars(rating: number): string {
	const full = Math.round(rating);
	return "★★★★★".slice(0, full) + "☆☆☆☆☆".slice(0, 5 - full);
}

function formatDate(iso: string): string {
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return "";
	return d.toLocaleDateString(undefined, { year: "numeric", month: "short" });
}

function ReviewsWall() {
	const data = Route.useLoaderData();
	const [items, setItems] = createSignal<ReviewWallItem[]>(
		data().page?.items ?? [],
	);
	const [nextOffset, setNextOffset] = createSignal<number | null>(
		data().page?.nextOffset ?? null,
	);
	const [busy, setBusy] = createSignal(false);

	const aggregate = () => data().aggregate;

	async function loadMore() {
		const offset = nextOffset();
		if (offset == null) return;
		setBusy(true);
		const page = await fetchReviewsPage({ data: { offset } });
		setBusy(false);
		if (page) {
			setItems([...items(), ...page.items]);
			setNextOffset(page.nextOffset);
		} else {
			setNextOffset(null);
		}
	}

	return (
		<main>
			<section class="bd-section bd-section--narrow">
				<div class="bd-section__lead">
					<span class="bd-section__eyebrow">Reviews</span>
					<h1 class="bd-section__title">What customers say</h1>
					<Show when={aggregate()?.rating != null}>
						<p class="bd-section__sub">
							{stars(aggregate()?.rating ?? 0)}{" "}
							{(aggregate()?.rating ?? 0).toFixed(1)} average across{" "}
							{aggregate()?.totalCount ?? 0} reviews
						</p>
					</Show>
				</div>

				<Show
					when={items().length > 0}
					fallback={
						<div class="bd-empty">
							No reviews yet. Connect a Google/Yelp source in BD, or invite
							customers to leave one from their account.
						</div>
					}
				>
					<div style="display: flex; flex-direction: column; gap: 1rem;">
						<For each={items()}>
							{(review) => (
								<article
									class="bd-card"
									style="padding: 1.25rem 1.5rem; display: flex; flex-direction: column; gap: 0.4rem;"
								>
									<div style="display: flex; justify-content: space-between; align-items: center; gap: 1rem;">
										<div style="font-weight: 600; color: var(--title);">
											{review.reviewerName}
										</div>
										<div style="color: var(--accent);">
											{stars(review.rating)}
										</div>
									</div>
									<p>{review.text}</p>
									<div class="blog-card__meta">
										{formatDate(review.timeCreated)}
										<Show when={review.verified}> · Verified</Show>
									</div>
								</article>
							)}
						</For>
					</div>

					<Show when={nextOffset() != null}>
						<div style="text-align: center; margin-top: 1.5rem;">
							<button
								type="button"
								class="bd-btn bd-btn--ghost"
								disabled={busy()}
								onClick={loadMore}
							>
								{busy() ? "Loading…" : "Load more"}
							</button>
						</div>
					</Show>
				</Show>
			</section>
		</main>
	);
}
