// Remix/app/routes/services._index.tsx
import { Link, useLoaderData } from "react-router";
import type { LoaderFunctionArgs, MetaFunction } from "react-router";

import { SiteHeader } from "~/components/SiteHeader";
import { listServiceAreaVariants } from "~/lib/biab-pages.server";

export const meta: MetaFunction = () => [
	{ title: "Service areas — Your Business" },
	{
		name: "description",
		content: "Every service we offer, in every area we serve.",
	},
];

/** Index for the programmatic /services/[service]/[area] pages: lists every
 *  (service × area) variant BIAB has materialised, each linking to its
 *  server-rendered page. */
export async function loader(_: LoaderFunctionArgs) {
	const variants = await listServiceAreaVariants();
	return { variants };
}

export default function ServicesIndex() {
	const { variants } = useLoaderData<typeof loader>();
	return (
		<>
			<SiteHeader />
			<main>
				<section className="section">
					<h1 className="section__title">Service areas</h1>
					{variants.length === 0 ? (
						<p className="muted">
							No programmatic pages yet — define services and service areas in
							BIAB, then publish to generate them.
						</p>
					) : (
						<ul className="link-grid">
							{variants.map((v) => (
								<li key={`${v.service}/${v.area}`}>
									<Link to={`/services/${v.service}/${v.area}`}>
										{v.service.replace(/-/g, " ")} in {v.area.replace(/-/g, " ")}
									</Link>
								</li>
							))}
						</ul>
					)}
				</section>
			</main>
		</>
	);
}

// Tanstack-Start-Solid/solid/src/routes/services.index.tsx
import { createFileRoute, Link } from "@tanstack/solid-router";
import { For, Show } from "solid-js";

import { listServiceAreaVariants } from "../lib/biab-server-fns";

/**
 * Parallel-page index. Lists every (service × area) variant declared in
 * `biab.config.ts` (`defineParallelPage("service-area")`) and resolved by
 * BIAB via `parallelPages.listVariants`. Each links to the SSR-rendered
 * `/services/[service]/[area]` page. This is the link list a sitemap or
 * a "service areas" section would surface.
 */
export const Route = createFileRoute("/services/")({
	component: ServicesIndex,
	loader: () => listServiceAreaVariants(),
});

function titleCase(slug: string): string {
	return slug
		.split("-")
		.map((p) => p.charAt(0).toUpperCase() + p.slice(1))
		.join(" ");
}

function ServicesIndex() {
	const variants = Route.useLoaderData();

	return (
		<main>
			<section class="biab-section">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Coverage</span>
					<h1 class="biab-section__title">Services by area</h1>
					<p class="biab-section__sub">
						Programmatic pages: one URL per service × area. Tokens resolve
						server-side in BIAB so crawlers see fully-rendered copy.
					</p>
				</div>

				<Show
					when={variants().length > 0}
					fallback={
						<div class="biab-empty">
							No parallel-page variants yet. Seed services + service areas in
							BIAB, then run <code>npm run sync-schema</code>.
						</div>
					}
				>
					<div class="biab-grid-3">
						<For each={variants()}>
							{(v) => (
								<Link
									to="/services/$service/$area"
									params={{ service: v.service, area: v.area }}
									class="biab-card service-card"
									style="text-decoration: none; border-bottom: none;"
								>
									<h3>{titleCase(v.service)}</h3>
									<p>{titleCase(v.area)}</p>
								</Link>
							)}
						</For>
					</div>
				</Show>
			</section>
		</main>
	);
}
