// Remix/app/routes/store._index.tsx
import { Form, Link, useLoaderData, useSearchParams } from "react-router";
import type { LoaderFunctionArgs, MetaFunction } from "react-router";

import { SiteHeader } from "~/components/SiteHeader";
import { formatCents } from "~/lib/format";
import {
	getCartSnapshot,
	listStoreCategories,
	listStoreProductsWithMeta,
} from "~/lib/biab-store.server";

export const meta: MetaFunction = () => [
	{ title: "Store — Your Business" },
	{ name: "description", content: "Browse products and services." },
];

const SORTS = [
	{ value: "featured", label: "Featured" },
	{ value: "newest", label: "Newest" },
	{ value: "price-asc", label: "Price: low to high" },
	{ value: "price-desc", label: "Price: high to low" },
	{ value: "rating-desc", label: "Top rated" },
] as const;

type Sort = (typeof SORTS)[number]["value"];

function parseSort(raw: string | null): Sort {
	return SORTS.some((s) => s.value === raw) ? (raw as Sort) : "featured";
}

function parseCents(raw: string | null): number | undefined {
	if (!raw) return undefined;
	const dollars = Number.parseFloat(raw);
	return Number.isFinite(dollars) ? Math.round(dollars * 100) : undefined;
}

export async function loader({ request }: LoaderFunctionArgs) {
	const url = new URL(request.url);
	const search = url.searchParams.get("q")?.trim() || undefined;
	const categoryId = url.searchParams.get("category") || undefined;
	const sort = parseSort(url.searchParams.get("sort"));
	const minPriceCents = parseCents(url.searchParams.get("min"));
	const maxPriceCents = parseCents(url.searchParams.get("max"));
	const minRatingRaw = url.searchParams.get("rating");
	const minRating = minRatingRaw ? Number.parseInt(minRatingRaw, 10) : undefined;

	const [meta, categories, cart] = await Promise.all([
		listStoreProductsWithMeta({
			limit: 48,
			...(search ? { search } : {}),
			...(categoryId ? { categoryId } : {}),
			...(minPriceCents != null ? { minPriceCents } : {}),
			...(maxPriceCents != null ? { maxPriceCents } : {}),
			...(minRating ? { minRating } : {}),
			sort,
		}),
		listStoreCategories(),
		getCartSnapshot(request),
	]);

	const categoryNames = new Map<string, string>(
		(categories?.items ?? []).map((c) => [c.id, c.name]),
	);

	return {
		connected: meta !== null,
		products: (meta?.items ?? []).map((p) => ({
			id: p.id,
			name: p.name,
			image: p.coverImage,
			priceLabel:
				p.cheapestPriceCents != null
					? formatCents(p.cheapestPriceCents)
					: "View details",
			comparePriceLabel:
				p.isOnSale && p.comparePriceCents != null
					? formatCents(p.comparePriceCents)
					: null,
			fromPrice: p.hasMultipleVariants,
			avgRating: p.avgRating,
			reviewCount: p.reviewCount,
			isBestSeller: p.isBestSeller,
			isNew: p.isNew,
			isLowStock: p.isLowStock,
		})),
		categories: (meta?.categoryCounts ?? []).map((c) => ({
			id: c.categoryId,
			name: categoryNames.get(c.categoryId) ?? "Category",
			count: c.count,
		})),
		priceRange: meta?.priceRange ?? null,
		cartCount: cart?.itemCount ?? 0,
	};
}

export default function StoreIndex() {
	const { connected, products, categories, priceRange, cartCount } =
		useLoaderData<typeof loader>();
	const [params] = useSearchParams();
	const activeCategory = params.get("category");
	const activeRating = params.get("rating");

	return (
		<>
			<SiteHeader cartCount={cartCount} />
			<main>
				<section className="section">
					<div className="section__head">
						<h1 className="section__title">Store</h1>
						<Link className="muted" to="/store/subscriptions">
							Subscriptions →
						</Link>
					</div>

					{!connected ? (
						<p className="muted">
							Store isn't connected yet. Add your BIAB env to list products.
						</p>
					) : (
						<div className="store-layout">
							{/* Facet sidebar — GET form so filters live in the URL. */}
							<aside>
								<Form method="get" className="store-facets">
									<div className="facet">
										<h3>Search</h3>
										<input
											type="search"
											name="q"
											defaultValue={params.get("q") ?? ""}
											placeholder="Search products"
										/>
									</div>

									{categories.length > 0 ? (
										<div className="facet">
											<h3>Categories</h3>
											<ul className="facet-cats">
												<li>
													<CategoryLink
														params={params}
														id={null}
														label="All"
														active={!activeCategory}
													/>
												</li>
												{categories.map((c) => (
													<li key={c.id}>
														<CategoryLink
															params={params}
															id={c.id}
															label={c.name}
															count={c.count}
															active={activeCategory === c.id}
														/>
													</li>
												))}
											</ul>
										</div>
									) : null}

									<div className="facet">
										<h3>Price</h3>
										<div className="facet-range">
											<input
												type="number"
												name="min"
												min={0}
												step="0.01"
												placeholder={
													priceRange
														? `$${priceRange.minDollars.toFixed(0)}`
														: "Min"
												}
												defaultValue={params.get("min") ?? ""}
											/>
											<span className="muted">–</span>
											<input
												type="number"
												name="max"
												min={0}
												step="0.01"
												placeholder={
													priceRange
														? `$${priceRange.maxDollars.toFixed(0)}`
														: "Max"
												}
												defaultValue={params.get("max") ?? ""}
											/>
										</div>
									</div>

									<div className="facet">
										<h3>Minimum rating</h3>
										<select name="rating" defaultValue={activeRating ?? ""}>
											<option value="">Any rating</option>
											<option value="4">4★ & up</option>
											<option value="3">3★ & up</option>
											<option value="2">2★ & up</option>
											<option value="1">1★ & up</option>
										</select>
									</div>

									<div className="facet">
										<h3>Sort</h3>
										<select
											name="sort"
											defaultValue={params.get("sort") ?? "featured"}
										>
											{SORTS.map((s) => (
												<option value={s.value} key={s.value}>
													{s.label}
												</option>
											))}
										</select>
									</div>

									{/* Preserve the active category across an Apply submit. */}
									{activeCategory ? (
										<input type="hidden" name="category" value={activeCategory} />
									) : null}
									<button className="biab-btn" type="submit">
										Apply filters
									</button>
								</Form>
							</aside>

							{/* Product grid */}
							<div>
								{products.length === 0 ? (
									<p className="muted">No products match these filters.</p>
								) : (
									<div className="grid">
										{products.map((p) => (
											<Link
												className="card card--link"
												to={`/store/${p.id}`}
												key={p.id}
											>
												{p.image ? (
													<img className="card__img" src={p.image} alt={p.name} />
												) : null}
												{p.isBestSeller || p.isNew || p.isLowStock ? (
													<div className="card__badges">
														{p.isBestSeller ? (
															<span className="biab-badge">Best seller</span>
														) : null}
														{p.isNew ? (
															<span className="biab-badge">New</span>
														) : null}
														{p.isLowStock ? (
															<span className="biab-badge">Low stock</span>
														) : null}
													</div>
												) : null}
												<h3>{p.name}</h3>
												<div className="card__price-row">
													<span className="price">
														{p.fromPrice ? `From ${p.priceLabel}` : p.priceLabel}
													</span>
													{p.comparePriceLabel ? (
														<span className="price price--compare">
															{p.comparePriceLabel}
														</span>
													) : null}
												</div>
												{p.reviewCount > 0 ? (
													<span className="card__rating">
														<span className="stars">
															{"★".repeat(Math.round(p.avgRating))}
														</span>
														{p.avgRating.toFixed(1)} ({p.reviewCount})
													</span>
												) : null}
											</Link>
										))}
									</div>
								)}
							</div>
						</div>
					)}
				</section>
			</main>
		</>
	);
}

/** Category link that preserves the other active facets in the query string. */
function CategoryLink({
	params,
	id,
	label,
	count,
	active,
}: {
	params: URLSearchParams;
	id: string | null;
	label: string;
	count?: number;
	active: boolean;
}) {
	const next = new URLSearchParams(params);
	if (id) next.set("category", id);
	else next.delete("category");
	const qs = next.toString();
	return (
		<Link
			to={qs ? `/store?${qs}` : "/store"}
			className={active ? "is-active" : undefined}
			prefetch="intent"
		>
			<span>{label}</span>
			{count != null ? <span className="count">{count}</span> : null}
		</Link>
	);
}

// Tanstack-Start-Solid/solid/src/routes/store.index.tsx
import type { StorefrontSort } from "@businessdash/sdk/contracts";
import { createFileRoute, Link } from "@tanstack/solid-router";
import { createMemo, createResource, createSignal, For, Show } from "solid-js";

import { formatMoney } from "../components/biab/money";
import { Stars } from "../components/biab/Stars";
import {
	getStoreListing,
	type StoreFilters,
	type StoreListingResult,
} from "../lib/biab-server-fns";

/**
 * Storefront listing — `storefront.listProductsWithMeta` powers an enriched,
 * platform-style grid (price / compareAt / ratings / badges) with a facet
 * sidebar (search, categories with counts, price range, min-rating, sort).
 *
 * The loader fetches the unfiltered first page server-side; facet changes drive
 * a `createResource` that refetches through the same `getStoreListing` server fn
 * (the secret key stays on the server). Degrades to a "not connected" /
 * "unavailable" state when BIAB env is unset or the org is suspended.
 */
export const Route = createFileRoute("/store/")({
	component: StoreIndex,
	loader: () => getStoreListing({ data: {} }),
});

const SORT_LABELS: Record<StorefrontSort, string> = {
	featured: "Featured",
	newest: "Newest",
	"price-asc": "Price: low to high",
	"price-desc": "Price: high to low",
	"rating-desc": "Top rated",
};

function StoreIndex() {
	const initial = Route.useLoaderData();

	const [filters, setFilters] = createSignal<StoreFilters>({});

	// Refetch through the server fn whenever a facet changes. Seeded with the
	// loader's first page so there's no flash before the first interaction.
	const [listing] = createResource<StoreListingResult, StoreFilters>(
		filters,
		(f) => getStoreListing({ data: f }),
		{ initialValue: initial() },
	);

	const result = () => listing() ?? initial();
	const data = () => {
		const r = result();
		return r.ok ? r : null;
	};
	const reason = () => {
		const r = result();
		return r.ok ? null : r.reason;
	};

	const countByCategory = createMemo(() => {
		const d = data();
		return new Map(
			(d?.categoryCounts ?? []).map((c) => [c.categoryId, c.count]),
		);
	});

	const patch = (next: Partial<StoreFilters>) =>
		setFilters((prev) => ({ ...prev, ...next }));

	const hasFilters = () => {
		const f = filters();
		return Boolean(
			f.search ||
				f.categoryId ||
				f.minRating ||
				f.minPriceCents != null ||
				f.maxPriceCents != null,
		);
	};

	const onSearch = (e: SubmitEvent) => {
		e.preventDefault();
		const q = String(
			new FormData(e.currentTarget as HTMLFormElement).get("q") ?? "",
		).trim();
		patch({ search: q || undefined });
	};

	const onPrice = (e: SubmitEvent) => {
		e.preventDefault();
		const fd = new FormData(e.currentTarget as HTMLFormElement);
		const min = Number(String(fd.get("min") ?? "").trim());
		const max = Number(String(fd.get("max") ?? "").trim());
		patch({
			minPriceCents:
				Number.isFinite(min) && min > 0 ? Math.round(min * 100) : undefined,
			maxPriceCents:
				Number.isFinite(max) && max > 0 ? Math.round(max * 100) : undefined,
		});
	};

	return (
		<main>
			<section class="biab-section">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Shop</span>
					<h1 class="biab-section__title">Store</h1>
					<p class="biab-section__sub">
						Products synced live from BIAB. Filter, add to cart, apply a coupon,
						and check out through Stripe.
					</p>
				</div>

				<Show
					when={data()}
					fallback={
						<div class="biab-empty">
							<Show
								when={reason() === "suspended"}
								fallback={
									<>
										Store isn't connected yet. Set <code>BIAB_API_KEY</code>,{" "}
										<code>BIAB_SITE_ID</code>, and{" "}
										<code>BIAB_PACKAGE_API_BASE_URL</code> in <code>.env</code>.
									</>
								}
							>
								This store is temporarily unavailable. Please check back soon.
							</Show>
						</div>
					}
				>
					{(d) => (
						<div class="store-layout">
							{/* Facet sidebar */}
							<aside class="store-sidebar">
								<form onSubmit={onSearch}>
									<div class="store-facet__title">Search</div>
									<input
										class="biab-input"
										name="q"
										placeholder="Search products…"
										type="search"
										value={filters().search ?? ""}
									/>
								</form>

								<Show when={d().categories.length > 0}>
									<div>
										<div class="store-facet__title">Category</div>
										<ul class="store-facet__list">
											<li>
												<button
													class="store-facet__btn"
													classList={{
														"store-facet__btn--active": !filters().categoryId,
													}}
													onClick={() => patch({ categoryId: undefined })}
													type="button"
												>
													All products
												</button>
											</li>
											<For each={d().categories}>
												{(c) => {
													const active = () => filters().categoryId === c.id;
													return (
														<li>
															<button
																class="store-facet__btn"
																classList={{
																	"store-facet__btn--active": active(),
																}}
																onClick={() =>
																	patch({
																		categoryId: active() ? undefined : c.id,
																	})
																}
																type="button"
															>
																<span>{c.name}</span>
																<span class="store-facet__count">
																	{countByCategory().get(c.id) ?? 0}
																</span>
															</button>
														</li>
													);
												}}
											</For>
										</ul>
									</div>
								</Show>

								<form onSubmit={onPrice}>
									<div class="store-facet__title">Price</div>
									<div class="store-facet__price">
										<input
											class="biab-input"
											inputmode="numeric"
											name="min"
											placeholder={`$${Math.floor(d().priceRange.minDollars)}`}
										/>
										<span>–</span>
										<input
											class="biab-input"
											inputmode="numeric"
											name="max"
											placeholder={`$${Math.ceil(d().priceRange.maxDollars)}`}
										/>
									</div>
									<button
										class="biab-btn biab-btn--ghost"
										style="margin-top: 0.5rem; width: 100%;"
										type="submit"
									>
										Apply
									</button>
								</form>

								<div>
									<div class="store-facet__title">Rating</div>
									<ul class="store-facet__list">
										<For each={[4, 3, 2]}>
											{(r) => {
												const active = () => filters().minRating === r;
												return (
													<li>
														<button
															class="store-facet__btn"
															classList={{
																"store-facet__btn--active": active(),
															}}
															onClick={() =>
																patch({ minRating: active() ? undefined : r })
															}
															type="button"
														>
															<span style="display: inline-flex; align-items: center; gap: 0.4rem;">
																<Stars rating={r} /> &amp; up
															</span>
														</button>
													</li>
												);
											}}
										</For>
									</ul>
								</div>

								<Show when={hasFilters()}>
									<button
										class="store-facet__btn store-facet__btn--active"
										onClick={() => setFilters({})}
										type="button"
									>
										Clear all filters
									</button>
								</Show>
							</aside>

							{/* Grid */}
							<div>
								<div class="store-toolbar">
									<span class="store-toolbar__count">
										{d().items.length}{" "}
										{d().items.length === 1 ? "product" : "products"}
										<Show when={listing.loading}> · updating…</Show>
									</span>
									<label style="display: inline-flex; align-items: center; gap: 0.5rem; font-size: 0.9rem; color: var(--text-muted);">
										<span>Sort</span>
										<select
											class="biab-input biab-select"
											onChange={(e) =>
												patch({
													sort:
														e.currentTarget.value === "featured"
															? undefined
															: (e.currentTarget.value as StorefrontSort),
												})
											}
											style="width: auto;"
											value={filters().sort ?? "featured"}
										>
											<For
												each={Object.keys(SORT_LABELS) as Array<StorefrontSort>}
											>
												{(s) => <option value={s}>{SORT_LABELS[s]}</option>}
											</For>
										</select>
									</label>
								</div>

								<Show
									when={d().items.length > 0}
									fallback={
										<div class="biab-empty">
											No products match these filters. Try clearing one or
											broadening your search.
										</div>
									}
								>
									<div class="biab-grid-3">
										<For each={d().items}>
											{(p) => (
												<Link
													class="biab-card store-card"
													params={{ id: p.id }}
													style="text-decoration: none; border-bottom: none;"
													to="/store/$id"
												>
													<div class="store-card__media">
														<Show when={p.coverImage}>
															<img alt={p.name} src={p.coverImage ?? ""} />
														</Show>
														<div class="store-card__badges">
															<Show when={p.isBestSeller}>
																<span class="store-badge store-badge--featured">
																	Best seller
																</span>
															</Show>
															<Show when={p.isNew}>
																<span class="store-badge store-badge--new">
																	New
																</span>
															</Show>
															<Show when={p.isOnSale}>
																<span class="store-badge store-badge--sale">
																	Sale
																</span>
															</Show>
														</div>
													</div>
													<div class="store-card__body">
														<h3>{p.name}</h3>
														<Show when={p.reviewCount > 0}>
															<div class="store-card__rating">
																<Stars rating={p.avgRating} />
																<span>({p.reviewCount})</span>
															</div>
														</Show>
														<div class="store-card__price">
															<Show when={p.cheapestPriceCents != null}>
																<span class="store-card__price-now">
																	{p.hasMultipleVariants ? "From " : ""}
																	{formatMoney(p.cheapestPriceCents ?? 0)}
																</span>
															</Show>
															<Show
																when={p.isOnSale && p.comparePriceCents != null}
															>
																<span class="store-card__price-was">
																	{formatMoney(p.comparePriceCents ?? 0)}
																</span>
															</Show>
														</div>
														<Show when={p.isLowStock}>
															<span class="store-card__lowstock">
																Low stock
															</span>
														</Show>
													</div>
												</Link>
											)}
										</For>
									</div>
								</Show>
							</div>
						</div>
					)}
				</Show>

				<div style="margin-top: 2rem; display: flex; gap: 0.75rem;">
					<Link class="biab-btn biab-btn--ghost" to="/store/cart">
						View cart
					</Link>
					<Link class="biab-btn biab-btn--ghost" to="/subscriptions">
						Subscriptions
					</Link>
				</div>
			</section>
		</main>
	);
}
