// Remix/app/routes/store.cart.tsx
import { Form, Link, useActionData, useLoaderData } from "react-router";
import { redirect } from "react-router";
import type {
	ActionFunctionArgs,
	LoaderFunctionArgs,
	MetaFunction,
} from "react-router";

import { SiteHeader } from "~/components/SiteHeader";
import { formatCents } from "~/lib/format";
import {
	applyCartCoupon,
	clearCart,
	getCartSnapshot,
	removeCartCoupon,
	removeCartItem,
	startCheckout,
	updateCartItem,
	type CartMutationResult,
} from "~/lib/bd-store.server";

export const meta: MetaFunction = () => [{ title: "Cart — Your Business" }];

export async function loader({ request }: LoaderFunctionArgs) {
	const cart = await getCartSnapshot(request);
	return {
		cart: cart
			? {
					currency: cart.currency,
					couponCode: cart.couponCode,
					subtotal: cart.subtotal,
					itemCount: cart.itemCount,
					items: cart.items.map((it) => ({
						id: it.id,
						name: it.productName ?? "Item",
						variantTitle: it.variantTitle,
						image: it.productImage,
						quantity: it.quantity,
						lineTotal: it.subtotal,
					})),
				}
			: null,
	};
}

/** One action, dispatched by the `intent` field, covering every cart mutation
 *  plus checkout (which redirects to the Stripe-hosted URL). */
export async function action({ request }: ActionFunctionArgs) {
	const fd = await request.formData();
	const intent = String(fd.get("intent") ?? "");

	if (intent === "checkout") {
		const origin = new URL(request.url).origin;
		const res = await startCheckout(request, origin);
		if (res.ok) return redirect(res.url);
		return { ok: false as const, error: res.error };
	}

	let result: CartMutationResult;
	switch (intent) {
		case "update":
			result = await updateCartItem(
				request,
				String(fd.get("itemId")),
				Number.parseInt(String(fd.get("quantity") ?? "1"), 10) || 0,
			);
			break;
		case "remove":
			result = await removeCartItem(request, String(fd.get("itemId")));
			break;
		case "apply-coupon":
			result = await applyCartCoupon(request, String(fd.get("code") ?? ""));
			break;
		case "remove-coupon":
			result = await removeCartCoupon(request);
			break;
		case "clear":
			result = await clearCart(request);
			break;
		default:
			return { ok: false as const, error: "Unknown action." };
	}

	if (!result.ok) return { ok: false as const, error: result.error };
	// A visitor reaching /store/cart already holds the `bd_cart_visitor`
	// cookie (it's minted on the first add-to-cart, which redirects here), so
	// no Set-Cookie is needed on these mutations. The mutation succeeded.
	return { ok: true as const, error: null };
}

export default function CartPage() {
	const { cart } = useLoaderData<typeof loader>();
	const actionData = useActionData<typeof action>();

	return (
		<>
			<SiteHeader cartCount={cart?.itemCount ?? 0} />
			<main>
				<section className="section">
					<h1 className="section__title">Your cart</h1>
					{actionData && actionData.ok === false ? (
						<p className="error">{actionData.error}</p>
					) : null}
					{!cart || cart.items.length === 0 ? (
						<p className="muted">
							Your cart is empty. <Link to="/store">Browse the store →</Link>
						</p>
					) : (
						<>
							<ul className="cart-list">
								{cart.items.map((it) => (
									<li className="cart-row" key={it.id}>
										{it.image ? (
											<img className="cart-row__img" src={it.image} alt={it.name} />
										) : null}
										<div className="cart-row__body">
											<strong>{it.name}</strong>
											{it.variantTitle ? (
												<span className="muted"> · {it.variantTitle}</span>
											) : null}
										</div>
										<Form method="post" className="cart-row__qty">
											<input type="hidden" name="intent" value="update" />
											<input type="hidden" name="itemId" value={it.id} />
											<input
												type="number"
												name="quantity"
												min={0}
												defaultValue={it.quantity}
												aria-label="Quantity"
											/>
											<button className="link-btn" type="submit">
												Update
											</button>
										</Form>
										<span className="price">
											{formatCents(it.lineTotal, cart.currency)}
										</span>
										<Form method="post">
											<input type="hidden" name="intent" value="remove" />
											<input type="hidden" name="itemId" value={it.id} />
											<button className="link-btn link-btn--danger" type="submit">
												Remove
											</button>
										</Form>
									</li>
								))}
							</ul>

							<div className="cart-foot">
								{cart.couponCode ? (
									<Form method="post" className="coupon">
										<span className="muted">Coupon: {cart.couponCode}</span>
										<input type="hidden" name="intent" value="remove-coupon" />
										<button className="link-btn" type="submit">
											Remove
										</button>
									</Form>
								) : (
									<Form method="post" className="coupon">
										<input type="hidden" name="intent" value="apply-coupon" />
										<input name="code" placeholder="Coupon code" aria-label="Coupon code" />
										<button className="link-btn" type="submit">
											Apply
										</button>
									</Form>
								)}

								<div className="cart-total">
									<span>Subtotal</span>
									<strong>{formatCents(cart.subtotal, cart.currency)}</strong>
								</div>

								<div className="cart-actions">
									<Form method="post">
										<input type="hidden" name="intent" value="clear" />
										<button className="link-btn" type="submit">
											Clear cart
										</button>
									</Form>
									<Form method="post">
										<input type="hidden" name="intent" value="checkout" />
										<button className="bd-btn" type="submit">
											Checkout
										</button>
									</Form>
								</div>
							</div>
						</>
					)}
				</section>
			</main>
		</>
	);
}

// Tanstack-Start-Solid/solid/src/routes/store.cart.tsx
import type { CartSnapshot } from "@businessdash/sdk/contracts";
import { createFileRoute, Link } from "@tanstack/solid-router";
import { createSignal, For, Show } from "solid-js";

import { formatMoney } from "../components/bd/money";
import {
	applyCartCoupon,
	type CartResult,
	clearCart,
	getCart,
	removeCartCoupon,
	removeCartItem,
	startCheckout,
	updateCartItem,
} from "../lib/bd-server-fns";

/**
 * Cart. The loader reads the current snapshot via the visitor token
 * (httpOnly cookie). Quantity / remove / coupon / clear each call a
 * server fn that returns the new snapshot — we hold it in a signal and
 * re-render. "Checkout" starts a Stripe session and redirects.
 */
export const Route = createFileRoute("/store/cart")({
	component: CartView,
	loader: () => getCart(),
});

function CartView() {
	const initial = Route.useLoaderData();
	const [cart, setCart] = createSignal<CartSnapshot | null>(initial());
	const [busy, setBusy] = createSignal(false);
	const [coupon, setCoupon] = createSignal("");
	const [error, setError] = createSignal<string | null>(null);

	function apply(res: CartResult) {
		setBusy(false);
		if (res.ok) {
			setCart(res.snapshot);
			setError(null);
		} else {
			setError(res.error);
		}
	}

	async function setQty(itemId: string, quantity: number) {
		setBusy(true);
		apply(await updateCartItem({ data: { itemId, quantity } }));
	}
	async function remove(itemId: string) {
		setBusy(true);
		apply(await removeCartItem({ data: { itemId } }));
	}
	async function addCoupon() {
		if (!coupon().trim()) return;
		setBusy(true);
		apply(await applyCartCoupon({ data: { code: coupon().trim() } }));
	}
	async function dropCoupon() {
		setBusy(true);
		apply(await removeCartCoupon());
	}
	async function empty() {
		setBusy(true);
		apply(await clearCart());
	}
	async function checkout() {
		setBusy(true);
		setError(null);
		const res = await startCheckout({
			data: { origin: window.location.origin },
		});
		setBusy(false);
		if (res.ok) window.location.href = res.url;
		else setError(res.error);
	}

	const isEmpty = () => {
		const c = cart();
		return !c || c.items.length === 0;
	};

	return (
		<main>
			<section class="bd-section bd-section--narrow">
				<div class="bd-section__lead">
					<span class="bd-section__eyebrow">Checkout</span>
					<h1 class="bd-section__title">Your cart</h1>
				</div>

				<Show
					when={!isEmpty()}
					fallback={
						<div class="bd-empty">
							Your cart is empty. <Link to="/store">Browse the store →</Link>
						</div>
					}
				>
					<div
						class="bd-card"
						style="padding: 1.5rem; display: flex; flex-direction: column; gap: 1rem;"
					>
						<For each={cart()?.items ?? []}>
							{(item) => (
								<div style="display: flex; align-items: center; gap: 1rem; padding-bottom: 1rem; border-bottom: 1px solid var(--border);">
									<Show when={item.productImage}>
										<img
											src={item.productImage ?? ""}
											alt={item.productName ?? "Item"}
											style="width: 64px; height: 64px; object-fit: cover; border-radius: 0.5rem;"
										/>
									</Show>
									<div style="flex: 1;">
										<div style="font-weight: 600; color: var(--title);">
											{item.productName ?? "Item"}
										</div>
										<Show when={item.variantTitle}>
											<div style="font-size: 0.82rem; color: var(--text-muted);">
												{item.variantTitle}
											</div>
										</Show>
										<div style="font-size: 0.85rem; color: var(--text-muted);">
											{formatMoney(
												Math.round(item.unitPrice * 100),
												item.currency,
											)}{" "}
											each
										</div>
									</div>
									<div style="display: flex; align-items: center; gap: 0.5rem;">
										<button
											type="button"
											class="slot-button"
											disabled={busy()}
											onClick={() =>
												setQty(item.id, Math.max(0, item.quantity - 1))
											}
										>
											−
										</button>
										<span style="min-width: 1.5rem; text-align: center;">
											{item.quantity}
										</span>
										<button
											type="button"
											class="slot-button"
											disabled={busy()}
											onClick={() => setQty(item.id, item.quantity + 1)}
										>
											+
										</button>
									</div>
									<button
										type="button"
										class="bd-btn bd-btn--ghost"
										disabled={busy()}
										onClick={() => remove(item.id)}
									>
										Remove
									</button>
								</div>
							)}
						</For>

						<div style="display: flex; gap: 0.5rem; align-items: flex-end;">
							<div style="flex: 1;">
								<label class="bd-label" for="coupon">
									Coupon code
								</label>
								<input
									id="coupon"
									class="bd-input"
									placeholder="SAVE10"
									value={coupon()}
									onInput={(e) => setCoupon(e.currentTarget.value)}
								/>
							</div>
							<Show
								when={cart()?.couponCode}
								fallback={
									<button
										type="button"
										class="bd-btn bd-btn--ghost"
										disabled={busy()}
										onClick={addCoupon}
									>
										Apply
									</button>
								}
							>
								<button
									type="button"
									class="bd-btn bd-btn--ghost"
									disabled={busy()}
									onClick={dropCoupon}
								>
									Remove {cart()?.couponCode}
								</button>
							</Show>
						</div>

						<div style="display: flex; justify-content: space-between; font-weight: 700; color: var(--title); font-size: 1.1rem; padding-top: 0.5rem;">
							<span>Subtotal</span>
							<span>
								{formatMoney(
									Math.round((cart()?.subtotal ?? 0) * 100),
									cart()?.currency,
								)}
							</span>
						</div>

						<div style="display: flex; gap: 0.75rem;">
							<button
								type="button"
								class="bd-btn"
								style="flex: 1;"
								disabled={busy()}
								onClick={checkout}
							>
								{busy() ? "Working…" : "Checkout with Stripe"}
							</button>
							<button
								type="button"
								class="bd-btn bd-btn--ghost"
								disabled={busy()}
								onClick={empty}
							>
								Clear
							</button>
						</div>

						<Show when={error()}>
							<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
								{error()}
							</div>
						</Show>
					</div>
				</Show>
			</section>
		</main>
	);
}
