// Remix/app/routes/store.$id.tsx
import {
	Form,
	Link,
	useActionData,
	useLoaderData,
	useNavigation,
} from "react-router";
import { redirect } from "react-router";
import type {
	ActionFunctionArgs,
	LoaderFunctionArgs,
	MetaFunction,
} from "react-router";

import { SiteHeader } from "~/components/SiteHeader";
import { formatCents } from "~/lib/format";
import {
	addToCart,
	getCartSnapshot,
	getStoreProduct,
	getStoreProductAddons,
	getStoreProductReviews,
	getStoreRelatedProducts,
} from "~/lib/bd-store.server";

export const meta: MetaFunction<typeof loader> = ({ data }) => [
	{ title: data?.product ? `${data.product.name} — Store` : "Product" },
];

export async function loader({ params, request }: LoaderFunctionArgs) {
	const id = params["id"]!;
	const [product, reviews, related, addons, cart] = await Promise.all([
		getStoreProduct(id),
		getStoreProductReviews(id),
		getStoreRelatedProducts(id),
		getStoreProductAddons(id),
		getCartSnapshot(request),
	]);
	if (!product) {
		return { product: null, cartCount: cart?.itemCount ?? 0 } as const;
	}
	const extra = product as Record<string, unknown>;
	const variants = Array.isArray(product.variants) ? product.variants : [];
	return {
		product: {
			id: product.id,
			name: product.name,
			description:
				typeof extra["description"] === "string"
					? (extra["description"] as string)
					: "",
			image:
				Array.isArray(product.images) && product.images[0]
					? product.images[0]
					: null,
			priceLabel:
				typeof extra["priceCents"] === "number"
					? formatCents(extra["priceCents"] as number)
					: null,
			variants: variants.map((v) => {
				const vv = v as Record<string, unknown>;
				return {
					id: typeof vv["id"] === "string" ? (vv["id"] as string) : "",
					title:
						typeof vv["title"] === "string"
							? (vv["title"] as string)
							: "Default",
				};
			}),
		},
		reviews: reviews
			? {
					avgRating: reviews.avgRating,
					totalCount: reviews.totalCount,
					items: reviews.items.map((r) => ({
						id: r.id,
						rating: r.rating,
						reviewerName: r.reviewerName ?? "Customer",
						text: r.body ?? r.content ?? "",
						title: r.title ?? null,
					})),
				}
			: null,
		related: (related ?? []).map((r) => ({
			id: r.id,
			name: r.name,
			image: r.coverImageUrl,
			priceLabel:
				r.minPriceDollars != null
					? formatCents(Math.round(r.minPriceDollars * 100))
					: "View",
		})),
		addons: (addons?.items ?? []).map((a) => ({
			id: a.id,
			productId: a.addonProductId,
			name: a.addonName,
			description: a.addonDescription,
			groupLabel: a.groupLabel,
			image: a.imageUrl,
			priceLabel: a.priceCents != null ? formatCents(a.priceCents) : null,
		})),
		cartCount: cart?.itemCount ?? 0,
	} as const;
}

export async function action({ params, request }: ActionFunctionArgs) {
	const fd = await request.formData();
	const variantId = (fd.get("variantId") as string) || null;
	const quantity = Number.parseInt(String(fd.get("quantity") ?? "1"), 10) || 1;
	const result = await addToCart(request, {
		productId: params["id"]!,
		variantId,
		quantity,
	});
	if (!result.ok) return { ok: false as const, error: result.error };
	// On success, redirect to the cart (carrying the visitor cookie if minted).
	const headers = new Headers();
	if (result.setCookie) headers.append("Set-Cookie", result.setCookie);
	return redirect("/store/cart", { headers });
}

export default function ProductDetail() {
	const { product, reviews, related, addons, cartCount } =
		useLoaderData<typeof loader>();
	const actionData = useActionData<typeof action>();
	const nav = useNavigation();
	const adding = nav.state === "submitting";

	if (!product) {
		return (
			<>
				<SiteHeader cartCount={cartCount} />
				<main>
					<section className="section">
						<p className="muted">Product not found.</p>
						<Link className="muted" to="/store">
							← Back to store
						</Link>
					</section>
				</main>
			</>
		);
	}

	return (
		<>
			<SiteHeader cartCount={cartCount} />
			<main>
				<section className="section">
					<Link className="muted" to="/store">
						← Back to store
					</Link>
					<div className="product">
						{product.image ? (
							<img
								className="product__img"
								src={product.image}
								alt={product.name}
							/>
						) : null}
						<div>
							<h1 className="section__title">{product.name}</h1>
							{product.priceLabel ? (
								<p className="price price--lg">{product.priceLabel}</p>
							) : null}
							{reviews && reviews.totalCount > 0 ? (
								<p className="reviews-agg">
									<span className="stars">
										{"★".repeat(Math.round(reviews.avgRating))}
									</span>{" "}
									<strong>{reviews.avgRating.toFixed(1)}</strong> ·{" "}
									{reviews.totalCount} review
									{reviews.totalCount === 1 ? "" : "s"}
								</p>
							) : null}
							{product.description ? <p>{product.description}</p> : null}
							<Form method="post">
								{product.variants.length > 1 ? (
									<label>
										Option
										<select name="variantId">
											{product.variants.map((v) => (
												<option value={v.id} key={v.id}>
													{v.title}
												</option>
											))}
										</select>
									</label>
								) : product.variants[0] ? (
									<input
										type="hidden"
										name="variantId"
										value={product.variants[0].id}
									/>
								) : null}
								<label>
									Quantity
									<input type="number" name="quantity" min={1} defaultValue={1} />
								</label>
								<button className="bd-btn" type="submit" disabled={adding}>
									{adding ? "Adding…" : "Add to cart"}
								</button>
								{actionData && actionData.ok === false ? (
									<p className="error">{actionData.error}</p>
								) : null}
							</Form>
						</div>
					</div>

					{/* Companion / cross-sell addons ("complete your X"). */}
					{addons.length > 0 ? (
						<>
							<h2 className="section__subtitle">Complete your order</h2>
							<ul className="addon-list">
								{addons.map((a) => (
									<li className="addon" key={a.id}>
										{a.image ? <img src={a.image} alt={a.name} /> : null}
										<div className="addon__body">
											{a.groupLabel ? (
												<span className="addon__group">{a.groupLabel}</span>
											) : null}
											<div>
												<Link to={`/store/${a.productId}`}>
													<strong>{a.name}</strong>
												</Link>
											</div>
											{a.description ? (
												<p className="muted">{a.description}</p>
											) : null}
										</div>
										{a.priceLabel ? (
											<span className="price">{a.priceLabel}</span>
										) : null}
									</li>
								))}
							</ul>
						</>
					) : null}

					{/* Customer reviews. */}
					{reviews && reviews.items.length > 0 ? (
						<>
							<h2 className="section__subtitle">Reviews</h2>
							<ul className="review-list">
								{reviews.items.map((r) => (
									<li className="review" key={r.id}>
										<div className="review__head">
											<strong>{r.reviewerName}</strong>
											<span className="stars">
												{"★".repeat(Math.round(r.rating))}
											</span>
										</div>
										{r.title ? <strong>{r.title}</strong> : null}
										{r.text ? <p>{r.text}</p> : null}
									</li>
								))}
							</ul>
						</>
					) : null}

					{/* You may also like. */}
					{related.length > 0 ? (
						<>
							<h2 className="section__subtitle">You may also like</h2>
							<div className="grid">
								{related.map((r) => (
									<Link
										className="card card--link"
										to={`/store/${r.id}`}
										key={r.id}
									>
										{r.image ? (
											<img className="card__img" src={r.image} alt={r.name} />
										) : null}
										<h3>{r.name}</h3>
										<span className="price">{r.priceLabel}</span>
									</Link>
								))}
							</div>
						</>
					) : null}
				</section>
			</main>
		</>
	);
}

// Tanstack-Start-Solid/solid/src/routes/store.$id.tsx
import { createFileRoute, Link, useNavigate } from "@tanstack/solid-router";
import { createSignal, For, Show } from "solid-js";

import { formatMoney, rowImage, rowPriceCents } from "../components/bd/money";
import { Stars } from "../components/bd/Stars";
import {
	addToCart,
	getStoreProduct,
	getStoreProductExtras,
} from "../lib/bd-server-fns";

/**
 * Storefront product detail. The loader resolves the full product via
 * `storefront.getProduct` and, in parallel, its reviews / related / addons via
 * `getStoreProductExtras`. "Add to cart" calls the `addToCart` server fn — the
 * visitor-token cookie is minted server-side on that first write.
 */
export const Route = createFileRoute("/store/$id")({
	component: StoreDetail,
	loader: async ({ params }) => {
		const [product, extras] = await Promise.all([
			getStoreProduct({ data: { id: params.id } }),
			getStoreProductExtras({ data: { id: params.id } }),
		]);
		return { product, extras };
	},
});

function asString(v: unknown): string {
	return typeof v === "string" ? v : "";
}

function StoreDetail() {
	const data = Route.useLoaderData();
	const result = () => data().product;
	const extras = () => data().extras;
	const navigate = useNavigate();
	const [busy, setBusy] = createSignal(false);
	const [msg, setMsg] = createSignal<string | null>(null);
	const reason = () => {
		const r = result();
		return r.ok ? null : r.reason;
	};

	async function handleAdd(productId: string) {
		setBusy(true);
		setMsg(null);
		const res = await addToCart({ data: { productId, quantity: 1 } });
		setBusy(false);
		if (res.ok) {
			navigate({ to: "/store/cart" });
		} else {
			setMsg(res.error);
		}
	}

	return (
		<main>
			<section class="bd-section bd-section--narrow">
				<Link
					class="bd-section__eyebrow"
					style="display: inline-block; margin-bottom: 1rem;"
					to="/store"
				>
					← Back to store
				</Link>

				<Show
					when={result().ok}
					fallback={
						<div class="bd-empty">
							<Show
								when={reason() === "suspended"}
								fallback={<>This product is unavailable.</>}
							>
								This store is temporarily unavailable. Please check back soon.
							</Show>
						</div>
					}
				>
					{(() => {
						const r = result();
						if (!r.ok) return null;
						const product = r.product as typeof r.product &
							Record<string, unknown>;
						const price = rowPriceCents(product);
						const img = rowImage(product);
						const description =
							typeof product.description === "string"
								? product.description
								: null;
						const reviews = () => extras().reviews;
						return (
							<>
								<div class="bd-card" style="padding: 1.5rem;">
									<Show when={img}>
										<img
											alt={product.name}
											src={img ?? ""}
											style="aspect-ratio: 16/9; object-fit: cover; border-radius: 0.6rem; margin-bottom: 1.25rem;"
										/>
									</Show>
									<h1 class="bd-section__title" style="text-align: left;">
										{product.name}
									</h1>
									<Show when={reviews() && (reviews()?.totalCount ?? 0) > 0}>
										<div style="display: flex; align-items: center; gap: 0.5rem; margin-top: 0.5rem;">
											<Stars rating={reviews()?.avgRating ?? 0} />
											<span style="color: var(--text-muted); font-size: 0.9rem;">
												{(reviews()?.avgRating ?? 0).toFixed(1)} (
												{reviews()?.totalCount})
											</span>
										</div>
									</Show>
									<Show when={price != null}>
										<div
											class="service-card__price"
											style="font-size: 1.25rem; margin: 0.75rem 0 1rem;"
										>
											{formatMoney(price ?? 0)}
										</div>
									</Show>
									<Show when={description}>
										<p style="margin-bottom: 1.5rem;">{description}</p>
									</Show>
									<button
										class="bd-btn"
										disabled={busy()}
										onClick={() => handleAdd(product.id)}
										type="button"
									>
										{busy() ? "Adding…" : "Add to cart"}
									</button>
									<Show when={msg()}>
										<div style="margin-top: 1rem; color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
											{msg()}
										</div>
									</Show>
								</div>

								{/* Addons — complete your purchase */}
								<Show when={extras().addons.length > 0}>
									<section class="store-section">
										<h2 class="store-section__title">Complete your purchase</h2>
										<div class="bd-grid-3">
											<For each={extras().addons}>
												{(a) => (
													<Link
														class="bd-card store-addon"
														params={{ id: a.addonProductId }}
														style="text-decoration: none; border-bottom: none;"
														to="/store/$id"
													>
														<Show when={a.imageUrl}>
															<img alt={a.addonName} src={a.imageUrl ?? ""} />
														</Show>
														<div>
															<div class="store-addon__name">{a.addonName}</div>
															<Show when={a.priceCents != null}>
																<div class="store-addon__price">
																	{formatMoney(a.priceCents ?? 0)}
																</div>
															</Show>
														</div>
													</Link>
												)}
											</For>
										</div>
									</section>
								</Show>

								{/* Reviews */}
								<Show when={(reviews()?.items.length ?? 0) > 0}>
									<section class="store-section">
										<h2 class="store-section__title">Reviews</h2>
										<For each={reviews()?.items ?? []}>
											{(rev) => {
												const review = rev as Record<string, unknown>;
												const name =
													asString(review.reviewerName) || "Verified buyer";
												const text =
													asString(review.content) || asString(review.body);
												const title = asString(review.title);
												const rating = Number(review.rating) || 0;
												return (
													<div class="store-review">
														<div class="store-review__head">
															<Stars rating={rating} />
															<span class="store-review__name">{name}</span>
														</div>
														<Show when={title}>
															<p class="store-review__title">{title}</p>
														</Show>
														<Show when={text}>
															<p class="store-review__body">{text}</p>
														</Show>
													</div>
												);
											}}
										</For>
									</section>
								</Show>

								{/* Related — you may also like */}
								<Show when={extras().related.length > 0}>
									<section class="store-section">
										<h2 class="store-section__title">You may also like</h2>
										<div class="bd-grid-3">
											<For each={extras().related}>
												{(rp) => (
													<Link
														class="bd-card store-card"
														params={{ id: rp.id }}
														style="text-decoration: none; border-bottom: none;"
														to="/store/$id"
													>
														<div class="store-card__media">
															<Show when={rp.coverImageUrl}>
																<img
																	alt={rp.name}
																	src={rp.coverImageUrl ?? ""}
																/>
															</Show>
														</div>
														<div class="store-card__body">
															<h3>{rp.name}</h3>
															<Show when={rp.minPriceDollars != null}>
																<div class="store-card__price">
																	<span class="store-card__price-now">
																		{formatMoney(
																			Math.round(
																				(rp.minPriceDollars ?? 0) * 100,
																			),
																		)}
																	</span>
																</div>
															</Show>
														</div>
													</Link>
												)}
											</For>
										</div>
									</section>
								</Show>
							</>
						);
					})()}
				</Show>
			</section>
		</main>
	);
}
