// Qwik/src/routes/subscriptions/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$, server$ } from "@builder.io/qwik-city";

import {
	BiabPaymentLapsedError,
	BiabServiceSuspendedError,
} from "@businessdash/sdk";
import type { SubscriptionOffering } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import { getBiab } from "../../lib/biab";
import { formatMoney } from "../../lib/biab-store";
import { getCustomerSession } from "../../lib/biab-portal";

/** Subscription offerings list. Each plan starts its own Stripe checkout. */
export const useSubscriptions = routeLoader$(async ({ cookie }) => {
	const biab = getBiab();
	if (!biab) {
		return { configured: false, suspended: false, items: [], signedIn: false } as const;
	}
	try {
		const [res, session] = await Promise.all([
			biab.subscriptions.list(),
			getCustomerSession(cookie),
		]);
		return {
			configured: true,
			suspended: false,
			items: res.items,
			signedIn: !!session,
		} as const;
	} catch (err) {
		if (
			err instanceof BiabServiceSuspendedError ||
			err instanceof BiabPaymentLapsedError
		) {
			return { configured: true, suspended: true, items: [], signedIn: false } as const;
		}
		return { configured: true, suspended: false, items: [], signedIn: false } as const;
	}
});

const startSubscriptionRpc = server$(async function (this, id: string) {
	const biab = getBiab();
	if (!biab) return { ok: false as const, error: "Plans aren't connected." };
	try {
		const res = await biab.subscriptions.startCheckout(id, {
			successUrl: `${this.url.origin}/store/order?session_id={CHECKOUT_SESSION_ID}`,
			cancelUrl: `${this.url.origin}/subscriptions`,
		});
		return { ok: true as const, url: res.stripeUrl };
	} catch (err) {
		return {
			ok: false as const,
			error: err instanceof Error ? err.message : "Couldn't start checkout.",
		};
	}
});

export default component$(() => {
	const data = useSubscriptions();
	const busy = useSignal<string | null>(null);
	const error = useSignal<string | null>(null);

	const subscribe = $(async (id: string) => {
		busy.value = id;
		error.value = null;
		const res = await startSubscriptionRpc(id);
		busy.value = null;
		if (res.ok) window.location.href = res.url;
		else error.value = res.error;
	});

	const items = data.value.items as SubscriptionOffering[];

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} />
			<main>
				<section class="biab-section">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Memberships</span>
						<h2 class="biab-section__title">Plans</h2>
						<p class="biab-section__sub">
							Recurring offerings from the BIAB subscriptions surface. Each
							subscribe button opens Stripe-hosted checkout.
						</p>
					</div>

					{data.value.suspended ? (
						<div class="biab-empty">
							Plans are temporarily unavailable. Please check back soon.
						</div>
					) : items.length === 0 ? (
						<div class="biab-empty">
							No subscription plans yet. Add some in BIAB at Dashboard →
							Products → Subscriptions.
						</div>
					) : (
						<div class="biab-grid-3">
							{items.map((plan) => (
								<div
									class="biab-card service-card"
									key={plan.id}
								>
									{plan.imageUrl ? (
										<img
											alt={plan.name}
											src={plan.imageUrl}
											style="border-radius: 0.75rem; aspect-ratio: 4/3; object-fit: cover;"
										/>
									) : null}
									<h3>{plan.name}</h3>
									{plan.description ? <p>{plan.description}</p> : null}
									<div class="service-card__price">
										{formatMoney(plan.amountCents, "usd")} / {plan.interval}
									</div>
									<button
										class="biab-btn"
										disabled={busy.value === plan.id}
										onClick$={() => subscribe(plan.id)}
										style="align-self: flex-start; margin-top: 0.5rem;"
										type="button"
									>
										{busy.value === plan.id ? "Working…" : "Subscribe"}
									</button>
								</div>
							))}
						</div>
					)}

					{error.value ? (
						<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; margin-top: 1.5rem;">
							{error.value}
						</div>
					) : null}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Plans — Your Business",
	meta: [
		{ name: "description", content: "Recurring subscription plans via Stripe." },
	],
};

// Tanstack-Start/solid/src/routes/subscriptions.tsx
import { createFileRoute, Link } from "@tanstack/solid-router";
import { createSignal, For, Show } from "solid-js";

import { formatMoney, intervalLabel } from "../components/biab/money";
import {
	getSubscriptions,
	startSubscriptionCheckout,
} from "../lib/biab-server-fns";

/**
 * Recurring plans. The loader lists offerings via `subscriptions.list`.
 * "Subscribe" starts a Stripe-hosted subscription checkout and redirects.
 */
export const Route = createFileRoute("/subscriptions")({
	component: Subscriptions,
	loader: () => getSubscriptions(),
});

function Subscriptions() {
	const result = Route.useLoaderData();
	const [busyId, setBusyId] = createSignal<string | null>(null);
	const [error, setError] = createSignal<string | null>(null);
	const items = () => {
		const r = result();
		return r.ok ? r.items : [];
	};
	const reason = () => {
		const r = result();
		return r.ok ? null : r.reason;
	};

	async function subscribe(id: string) {
		setBusyId(id);
		setError(null);
		const res = await startSubscriptionCheckout({
			data: { id, origin: window.location.origin },
		});
		setBusyId(null);
		if (res.ok) window.location.href = res.url;
		else setError(res.error);
	}

	return (
		<main>
			<section class="biab-section">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Plans</span>
					<h1 class="biab-section__title">Subscriptions</h1>
					<p class="biab-section__sub">
						Recurring plans billed through Stripe. Cancel anytime.
					</p>
				</div>

				<Show
					when={result().ok && items().length > 0}
					fallback={
						<div class="biab-empty">
							<Show
								when={reason() === "suspended"}
								fallback={
									<Show
										when={reason() === "unconfigured"}
										fallback={<>No subscription plans published yet.</>}
									>
										Subscriptions aren't connected yet (missing BIAB env).
									</Show>
								}
							>
								Subscriptions are temporarily unavailable.
							</Show>
						</div>
					}
				>
					<div class="biab-grid-3">
						<For each={items()}>
							{(plan) => (
								<article class="biab-card service-card">
									<Show when={plan.imageUrl}>
										<img
											src={plan.imageUrl ?? ""}
											alt={plan.name}
											style="aspect-ratio: 4/3; object-fit: cover; border-radius: 0.6rem;"
										/>
									</Show>
									<h3>{plan.name}</h3>
									<Show when={plan.description}>
										<p>{plan.description}</p>
									</Show>
									<div class="service-card__price">
										{formatMoney(plan.amountCents)} /{" "}
										{intervalLabel(plan.interval)}
									</div>
									<button
										type="button"
										class="biab-btn"
										style="margin-top: 0.5rem;"
										disabled={busyId() === plan.id}
										onClick={() => subscribe(plan.id)}
									>
										{busyId() === plan.id ? "Working…" : "Subscribe"}
									</button>
								</article>
							)}
						</For>
					</div>
				</Show>

				<Show when={error()}>
					<div style="margin-top: 1.5rem; color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
						{error()}
					</div>
				</Show>

				<div style="margin-top: 2rem;">
					<Link to="/store" class="biab-btn biab-btn--ghost">
						← Back to store
					</Link>
				</div>
			</section>
		</main>
	);
}
