// Qwik/src/routes/updates/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import { getBiab } from "../../lib/biab";
import { getUpdatesFromBundle } from "../../lib/biab-content";
import { getCustomerSession } from "../../lib/biab-portal";

/**
 * News / Updates feed. `bundle.updates` is a Google-Business-style posts feed
 * that rides the marketing bundle as an untyped passthrough at 0.9.5; we read
 * it defensively via `getUpdatesFromBundle`.
 */
export const useUpdates = routeLoader$(async ({ cookie }) => {
	const biab = getBiab();
	const session = await getCustomerSession(cookie);
	if (!biab) {
		return { configured: false, items: [], signedIn: !!session };
	}
	const bundle = await biab.marketing
		.getPageBundle({ pageKey: "home", locale: "en" })
		.catch(() => null);
	return {
		configured: true,
		items: getUpdatesFromBundle(bundle),
		signedIn: !!session,
	};
});

function formatDate(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	return Number.isNaN(d.getTime())
		? ""
		: d.toLocaleDateString(undefined, {
				year: "numeric",
				month: "short",
				day: "numeric",
			});
}

export default component$(() => {
	const data = useUpdates();

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">News</span>
						<h2 class="biab-section__title">Updates</h2>
						<p class="biab-section__sub">
							Recent posts, synced from the business profile via the BIAB
							marketing bundle.
						</p>
					</div>

					{!data.value.configured ? (
						<div class="biab-empty">
							Updates aren't connected yet. Set the BIAB env vars to pull them
							in.
						</div>
					) : data.value.items.length === 0 ? (
						<div class="biab-empty">No updates posted yet.</div>
					) : (
						<div style="display: flex; flex-direction: column; gap: 1.25rem;">
							{data.value.items.map((u) => (
								<article class="biab-card" style="padding: 1.5rem;" key={u.id}>
									{u.imageUrl ? (
										<img
											alt={u.title ?? "Update"}
											src={u.imageUrl}
											style="border-radius: 0.75rem; margin-bottom: 1rem; aspect-ratio: 16/9; object-fit: cover;"
										/>
									) : null}
									{u.title ? <h3>{u.title}</h3> : null}
									<p style="margin-top: 0.5rem; white-space: pre-line;">
										{u.body}
									</p>
									<div style="display: flex; justify-content: space-between; align-items: center; margin-top: 0.75rem;">
										<span style="color: var(--text-muted); font-size: 0.8rem;">
											{formatDate(u.postedAt)}
										</span>
										{u.link ? (
											<a class="biab-btn biab-btn--ghost" href={u.link}>
												Learn more
											</a>
										) : null}
									</div>
								</article>
							))}
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Updates — Your Business",
	meta: [{ name: "description", content: "News and updates feed." }],
};

// Tanstack-Start/solid/src/routes/updates.tsx
import { createFileRoute } from "@tanstack/solid-router";
import { For, Show } from "solid-js";

import { getSiteContentExtras } from "../lib/biab-server-fns";

/**
 * News / updates feed. Google-Business-style posts ride the marketing
 * bundle as `bundle.updates`; the loader extracts them. No-ops to a
 * friendly empty state when unconfigured or unseeded.
 */
export const Route = createFileRoute("/updates")({
	component: Updates,
	loader: () => getSiteContentExtras(),
});

function formatDate(iso: string | null): string {
	if (!iso) return "";
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return "";
	return d.toLocaleDateString(undefined, {
		year: "numeric",
		month: "short",
		day: "numeric",
	});
}

function Updates() {
	const data = Route.useLoaderData();
	const updates = () => data().updates;

	return (
		<main>
			<section class="biab-section biab-section--narrow">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">Latest</span>
					<h1 class="biab-section__title">Updates</h1>
					<p class="biab-section__sub">
						News and announcements, synced from the business's Google profile.
					</p>
				</div>

				<Show
					when={updates().length > 0}
					fallback={
						<div class="biab-empty">
							No updates posted yet. Check back soon.
						</div>
					}
				>
					<div style="display: flex; flex-direction: column; gap: 1.25rem;">
						<For each={updates()}>
							{(post) => (
								<article
									class="biab-card"
									style="padding: 1.5rem; display: flex; flex-direction: column; gap: 0.5rem;"
								>
									<Show when={post.imageUrl}>
										<img
											src={post.imageUrl ?? ""}
											alt={post.title ?? "Update"}
											style="aspect-ratio: 16/9; object-fit: cover; border-radius: 0.6rem; margin-bottom: 0.5rem;"
										/>
									</Show>
									<Show when={post.title}>
										<h3 style="font-size: 1.1rem;">{post.title}</h3>
									</Show>
									<Show when={post.postedAt}>
										<div class="blog-card__meta">
											{formatDate(post.postedAt)}
										</div>
									</Show>
									<p style="white-space: pre-wrap;">{post.body}</p>
									<Show when={post.link}>
										<a
											href={post.link ?? "#"}
											target="_blank"
											rel="noreferrer"
											class="biab-btn biab-btn--ghost"
											style="align-self: flex-start; margin-top: 0.5rem;"
										>
											Learn more
										</a>
									</Show>
								</article>
							)}
						</For>
					</div>
				</Show>
			</section>
		</main>
	);
}
