// Remix/app/components/SiteHeader.tsx
import { Link } from "react-router";

/**
 * Shared site header for the non-home routes (store, account, reviews, …).
 * The home route keeps its own anchor-based header for in-page section jumps;
 * this one uses real links + an optional cart-count badge. Plain `<a>` is used
 * for the auth endpoints since those are resource routes, not React routes.
 */
export function SiteHeader({ cartCount = 0 }: { cartCount?: number }) {
	return (
		<header className="header">
			<Link className="brand" to="/">
				Your Business
			</Link>
			<nav>
				<Link to="/store">Store</Link>
				<Link to="/services">Services</Link>
				<Link to="/reviews">Reviews</Link>
				<Link to="/updates">Updates</Link>
				<Link to="/book">Book</Link>
				<Link to="/my-account">Account</Link>
				<Link to="/store/cart" className="cart-link">
					Cart{cartCount > 0 ? <span className="cart-badge">{cartCount}</span> : null}
				</Link>
			</nav>
		</header>
	);
}

// Qwik/src/components/biab/SiteHeader.tsx
import { component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";

/**
 * Cross-page header for the SDK-surface routes (store, cart, reviews, …).
 * The home page keeps its own anchor-based `<Header />`; this one uses real
 * route links plus the BIAB auth + account entries.
 *
 * Auth uses plain links straight to the catch-all handler — no React
 * `SignIn`/`useUser` needed. `signedIn` is resolved server-side per route via
 * `getCustomerSession` and passed in, so the header reflects session state
 * without leaking the key to the client.
 */
export const SiteHeader = component$<{ signedIn?: boolean; cartCount?: number }>(
	({ signedIn = false, cartCount = 0 }) => {
		return (
			<header class="app-header">
				<div class="app-header__inner">
					<Link class="app-header__brand" href="/">
						Your Business
					</Link>
					<nav>
						<Link href="/store">Store</Link>
						<Link href="/subscriptions">Plans</Link>
						<Link href="/reviews">Reviews</Link>
						<Link href="/updates">Updates</Link>
						<Link href="/cart">
							Cart{cartCount > 0 ? ` (${cartCount})` : ""}
						</Link>
						{signedIn ? (
							<>
								<Link href="/my-account">Account</Link>
								<a href="/api/biab-auth/sign-out">Sign out</a>
							</>
						) : (
							<a href="/api/biab-auth/sign-in">Sign in</a>
						)}
					</nav>
				</div>
			</header>
		);
	},
);
