// Qwik/src/routes/[...slug]/index.tsx
import { component$ } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$ } from "@builder.io/qwik-city";
import {
	legalPageSeo,
	renderLegalPageHtml,
	resolveLegalPage,
} from "@businessdash/sdk/legal";

import { getBiab } from "../../lib/biab";

/**
 * The catch-all — legal pages, and everything else's 404.
 *
 * ## Your own routes always win
 *
 * Qwik City resolves a static segment before a rest parameter, so
 * `routes/privacy/index.tsx` shadows this file entirely. Write your own privacy
 * policy and this is never consulted for that path — no config, no conflict, no
 * build error, nothing to delete. That is why the SDK hands you a resolver
 * rather than generating a `privacy` route: two routes claiming one path is a
 * build failure, which would turn "I wrote my own policy" into a broken deploy.
 */
export const useLegalPage = routeLoader$(async (event) => {
	const client = getBiab();
	// Returns null for an unknown slug AND when BusinessDash is unreachable —
	// this route runs on every unmatched URL, so it must never throw.
	const document = client
		? await resolveLegalPage({ client, slug: event.params["slug"] })
		: null;

	if (!document) {
		// A real 404 status, so crawlers and uptime checks see the truth
		// rather than a 200 with an apology on it.
		event.status(404);
		return null;
	}

	return {
		title: document.title,
		description: legalPageSeo(document).description,
		html: renderLegalPageHtml(document),
	};
});

export default component$(() => {
	const page = useLegalPage();

	if (!page.value) {
		return (
			<main class="biab-section biab-section--narrow">
				<div class="biab-section__lead">
					<span class="biab-section__eyebrow">404</span>
					<h1 class="biab-section__title">We couldn't find that page</h1>
					<p class="biab-section__sub">
						The link may be out of date, or the page may have moved.
					</p>
				</div>
				<p>
					<a href="/">Back to the homepage</a>
				</p>
			</main>
		);
	}

	return (
		<main class="biab-section biab-section--narrow">
			{/*
			 * `html` is sanitised server-side when the org saves it, and the
			 * title and logo URL are escaped by `renderLegalPageHtml`. Style it
			 * via the `data-biab-legal-*` hooks — the markup ships unstyled so
			 * it inherits your site rather than fighting it.
			 */}
			<div dangerouslySetInnerHTML={page.value.html} />
		</main>
	);
});

export const head: DocumentHead = ({ resolveValue }) => {
	const page = resolveValue(useLegalPage);
	if (!page) return { title: "Page not found" };
	return {
		title: page.title,
		meta: [{ name: "description", content: page.description }],
	};
};

// T3-App/src/app/[...slug]/page.tsx
import type { Metadata } from "next";
import { notFound } from "next/navigation";

import {
	legalPageSeo,
	renderLegalPageHtml,
	resolveLegalPage,
} from "@businessdash/sdk/legal";

import { getBiab } from "@/server/lib/biab";

/**
 * The catch-all — legal pages, and everything else's 404.
 *
 * ## Your own pages always win, and nothing here can break that
 *
 * Next resolves a static segment before a catch-all, so `app/privacy/page.tsx`
 * shadows this file completely. Write your own privacy policy and this is never
 * consulted for that path — no config, no conflict, no build error, nothing to
 * delete. That is exactly why the SDK hands you a resolver instead of
 * generating `app/privacy/page.tsx`: two files claiming one route is a hard
 * build failure, which would turn "I wrote my own policy" into a broken deploy.
 *
 * ## Anything not a legal page falls through
 *
 * `resolveLegalPage()` returns null for an unknown slug and this calls
 * `notFound()`, which renders `app/not-found.tsx` with a real 404 status. It
 * also returns null rather than throwing when BusinessDash is unreachable —
 * this route runs on every unmatched URL, so an exception here would 500 the
 * whole site during an outage instead of 404ing one page.
 */

export const revalidate = 3600;

type Props = { params: Promise<{ slug: string[] }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
	const client = getBiab();
	if (!client) return {};
	const { slug } = await params;
	const document = await resolveLegalPage({ client, slug });
	if (!document) return {};

	const seo = legalPageSeo(document, { siteName: "Your Company" });
	return {
		title: seo.title,
		description: seo.description,
		openGraph: { title: seo.openGraph.title, type: "article" },
	};
}

export default async function CatchAllPage({ params }: Props) {
	const client = getBiab();
	const { slug } = await params;
	const document = client ? await resolveLegalPage({ client, slug }) : null;
	if (!document) notFound();

	return (
		<main className="biab-section biab-section--narrow">
			{/*
			 * `contentHtml` is sanitised server-side when the org saves it, and
			 * the title and logo URL are escaped by `renderLegalPageHtml`. Style
			 * it through the `data-biab-legal-*` hooks it emits — the markup
			 * ships unstyled so it inherits your site rather than fighting it.
			 */}
			<div
				dangerouslySetInnerHTML={{ __html: renderLegalPageHtml(document) }}
			/>
		</main>
	);
}
