// Qwik/src/routes/reviews/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$, server$ } from "@builder.io/qwik-city";

import type { ReviewWallItem } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import { fetchReviewsPage } from "../../lib/biab-content";
import { getCustomerSession } from "../../lib/biab-portal";

const PAGE_SIZE = 10;

/**
 * Reviews wall. `routeLoader$` pulls the aggregate (totalCount) + the first
 * page server-side; "Load more" calls a `server$` that pages forward via
 * `reviews.list({ offset })` until `nextOffset` is null.
 */
export const useReviews = routeLoader$(async ({ cookie }) => {
	const [page, session] = await Promise.all([
		fetchReviewsPage({ limit: PAGE_SIZE }),
		getCustomerSession(cookie),
	]);
	return {
		configured: page !== null,
		items: page?.items ?? [],
		totalCount: page?.totalCount ?? 0,
		nextOffset: page?.nextOffset ?? null,
		signedIn: !!session,
	};
});

const loadMoreRpc = server$(async function (this, offset: number) {
	const page = await fetchReviewsPage({ limit: PAGE_SIZE, offset });
	return {
		items: page?.items ?? [],
		nextOffset: page?.nextOffset ?? null,
	};
});

function Stars({ rating }: { rating: number }) {
	const full = Math.round(rating);
	return (
		<span aria-label={`${rating} out of 5`} style="color: var(--accent);">
			{"★".repeat(full)}
			{"☆".repeat(Math.max(0, 5 - full))}
		</span>
	);
}

function formatDate(iso: string): string {
	const d = new Date(iso);
	return Number.isNaN(d.getTime())
		? ""
		: d.toLocaleDateString(undefined, {
				year: "numeric",
				month: "short",
				day: "numeric",
			});
}

export default component$(() => {
	const data = useReviews();
	const items = useSignal<ReviewWallItem[]>(data.value.items as ReviewWallItem[]);
	const nextOffset = useSignal<number | null>(data.value.nextOffset);
	const loading = useSignal(false);

	const loadMore = $(async () => {
		if (nextOffset.value === null) return;
		loading.value = true;
		const res = await loadMoreRpc(nextOffset.value);
		items.value = [...items.value, ...(res.items as ReviewWallItem[])];
		nextOffset.value = res.nextOffset;
		loading.value = false;
	});

	const avg =
		items.value.length > 0
			? items.value.reduce((sum, r) => sum + r.rating, 0) / items.value.length
			: 0;

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Reviews</span>
						<h2 class="biab-section__title">What customers say</h2>
						{data.value.totalCount > 0 ? (
							<p class="biab-section__sub">
								<Stars rating={avg} /> · {data.value.totalCount} review
								{data.value.totalCount === 1 ? "" : "s"}
							</p>
						) : null}
					</div>

					{!data.value.configured ? (
						<div class="biab-empty">
							Reviews aren't connected yet. Set the BIAB env vars to pull them
							in.
						</div>
					) : items.value.length === 0 ? (
						<div class="biab-empty">No reviews yet. Be the first!</div>
					) : (
						<div style="display: flex; flex-direction: column; gap: 1rem;">
							{items.value.map((r) => (
								<div class="biab-card" style="padding: 1.5rem;" key={r.id}>
									<div style="display: flex; justify-content: space-between; align-items: center;">
										<strong style="color: var(--title);">
											{r.reviewerName}
										</strong>
										<Stars rating={r.rating} />
									</div>
									<p style="margin-top: 0.5rem;">{r.text}</p>
									<div style="color: var(--text-muted); font-size: 0.8rem; margin-top: 0.5rem;">
										{formatDate(r.timeCreated)}
										{r.verified ? " · Verified" : ""}
									</div>
								</div>
							))}

							{nextOffset.value !== null ? (
								<button
									class="biab-btn biab-btn--ghost"
									disabled={loading.value}
									onClick$={loadMore}
									style="align-self: center; margin-top: 1rem;"
									type="button"
								>
									{loading.value ? "Loading…" : "Load more"}
								</button>
							) : null}
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Reviews — Your Business",
	meta: [
		{ name: "description", content: "Customer reviews, paginated via the SDK." },
	],
};

// Svelte/src/routes/reviews/+page.svelte
<script lang="ts">
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import type { ReviewWallItem } from '@businessdash/sdk/contracts';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	// Seed local state from the server's first page, then grow it via "Load
	// more". Intentionally a one-time snapshot of `data`.
	// svelte-ignore state_referenced_locally
	let items = $state<ReviewWallItem[]>(data.items);
	// svelte-ignore state_referenced_locally
	let nextOffset = $state<number | null>(data.nextOffset);
	let loading = $state(false);

	function stars(rating: number): string {
		const full = Math.round(rating);
		return '★'.repeat(full) + '☆'.repeat(Math.max(0, 5 - full));
	}

	function formatDate(iso: string): string {
		const d = new Date(iso);
		return Number.isNaN(d.getTime())
			? ''
			: d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
	}

	async function loadMore() {
		if (nextOffset == null) return;
		loading = true;
		try {
			const res = await fetch(`/api/biab/reviews?limit=10&offset=${nextOffset}`);
			const body = (await res.json()) as {
				items: ReviewWallItem[];
				nextOffset: number | null;
			};
			items = [...items, ...body.items];
			nextOffset = body.nextOffset;
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head><title>Reviews</title></svelte:head>

<Header />

<main class="biab-section biab-section--narrow">
	<div class="biab-section__lead">
		<span class="biab-section__eyebrow">What customers say</span>
		<h1 class="biab-section__title">Reviews</h1>
		{#if data.average != null}
			<p class="biab-section__sub">
				<strong>{data.average.toFixed(1)}</strong>
				average across {data.totalCount} reviews.
			</p>
		{/if}
	</div>

	{#if !data.configured}
		<div class="biab-empty">
			Reviews aren't connected. Once BIAB is configured, your aggregate rating
			and reviews appear here.
		</div>
	{:else if items.length === 0}
		<div class="biab-empty">No reviews yet.</div>
	{:else}
		<div class="reviews-wall">
			{#each items as review (review.id)}
				<article class="biab-card review-card">
					<div class="review-card__head">
						<strong>{review.reviewerName}</strong>
						<span class="review-card__stars" aria-label={`${review.rating} out of 5`}>
							{stars(review.rating)}
						</span>
					</div>
					<p class="review-card__body">{review.text}</p>
					<div class="review-card__meta">
						<span>{formatDate(review.timeCreated)}</span>
						<span class="biab-badge">{review.source}</span>
						{#if review.verified}<span class="review-card__verified">Verified</span>{/if}
					</div>
				</article>
			{/each}
		</div>

		{#if nextOffset != null}
			<div style="text-align: center; margin-top: 2rem;">
				<button class="biab-btn biab-btn--ghost" onclick={loadMore} disabled={loading}>
					{loading ? 'Loading…' : 'Load more reviews'}
				</button>
			</div>
		{/if}
	{/if}
</main>

<Footer />

<style>
	.reviews-wall {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	.review-card {
		padding: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 0.6rem;
	}
	.review-card__head {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 1rem;
	}
	.review-card__stars {
		color: var(--accent);
		letter-spacing: 0.1em;
	}
	.review-card__body {
		color: var(--text);
	}
	.review-card__meta {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		color: var(--text-muted);
		font-size: 0.8rem;
	}
	.review-card__verified {
		color: var(--success);
		font-weight: 600;
	}
</style>
