// Remix/app/root.tsx
import {
	Links,
	Meta,
	Outlet,
	Scripts,
	ScrollRestoration,
	useLoaderData,
} from "react-router";
import type { LinksFunction, LoaderFunctionArgs } from "react-router";

import { SdkSetupBanner } from "./components/SdkSetupBanner";
import { getAnalyticsConfig } from "./lib/biab.server";
import stylesUrl from "./styles.css?url";
// SDK form styles: file-upload box, multi-step progress header, choice/
// availability chips. Required wherever `<BiabForm>` renders (contact, book).
// The container background is intentionally transparent — the template owns it.
import biabFormsUrl from "@businessdash/sdk/biab-forms.css?url";

export const links: LinksFunction = () => [
	{ rel: "stylesheet", href: stylesUrl },
	{ rel: "stylesheet", href: biabFormsUrl },
];

export async function loader(_: LoaderFunctionArgs) {
	return { analytics: getAnalyticsConfig() };
}

export default function App() {
	const { analytics } = useLoaderData<typeof loader>();
	return (
		<html lang="en">
			<head>
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<Meta />
				<Links />
			</head>
			<body>
				<Outlet />
				<SdkSetupBanner />
				<ScrollRestoration />
				<Scripts />
				{analytics ? (
					<script
						// Server-known config inlined so the public key never lives
						// in the static client bundle. The dynamic-import below
						// reads it after hydration.
						dangerouslySetInnerHTML={{
							__html: `window.__BIAB_ANALYTICS__=${JSON.stringify(analytics)};`,
						}}
					/>
				) : null}
				<script
					type="module"
					dangerouslySetInnerHTML={{
						__html: `
							const cfg = window.__BIAB_ANALYTICS__;
							if (cfg && cfg.siteId && cfg.baseUrl && cfg.apiKey) {
								import("@businessdash/sdk/analytics-core").then(({ initBiabAnalytics }) => {
									initBiabAnalytics({
										siteId: cfg.siteId,
										baseUrl: cfg.baseUrl,
										apiKey: cfg.apiKey,
									});
								});
							}
						`,
					}}
				/>
			</body>
		</html>
	);
}

// Qwik/src/root.tsx
import { component$, isDev } from "@builder.io/qwik";
import { QwikCityProvider, RouterOutlet } from "@builder.io/qwik-city";
import { SdkSetupBanner } from "./components/biab/SdkSetupBanner";
import { RouterHead } from "./components/router-head/router-head";

import "./global.css";
// SDK form styles — file-upload box, multi-step progress header (steps + bar),
// and the availability/choice chips. Unstyled without this. The container
// background is intentionally transparent; the template owns it (`.biab-card`).
import "@businessdash/sdk/biab-forms.css";

export default component$(() => {
  /**
   * The root of a QwikCity site always start with the <QwikCityProvider> component,
   * immediately followed by the document's <head> and <body>.
   *
   * Don't remove the `<head>` and `<body>` elements.
   */

  return (
    <QwikCityProvider>
      <head>
        <meta charset="utf-8" />
        {!isDev && (
          <link
            rel="manifest"
            href={`${import.meta.env.BASE_URL}manifest.json`}
          />
        )}
        <RouterHead />
      </head>
      <body lang="en">
        <RouterOutlet />
        <SdkSetupBanner />
      </body>
    </QwikCityProvider>
  );
});
