// Qwik/src/routes/cart/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { type DocumentHead, routeLoader$, server$ } from "@builder.io/qwik-city";

import type { CartSnapshot } from "@businessdash/sdk/contracts";

import { Footer } from "../../components/biab/Footer";
import { SiteHeader } from "../../components/biab/SiteHeader";
import {
	applyCartCoupon,
	clearCart,
	formatMoney,
	getCartSnapshot,
	removeCartCoupon,
	removeCartItem,
	startCheckout,
	updateCartItem,
} from "../../lib/biab-store";
import { getCustomerSession } from "../../lib/biab-portal";

/**
 * Cart view. `routeLoader$` reads the visitor cart server-side; the mutations
 * are `server$` RPCs that read/write the `biab_cart_visitor` cookie through
 * `this.cookie` and return a fresh snapshot the client swaps in. Checkout
 * starts a Stripe session and returns the hosted URL to redirect to.
 */
export const useCart = routeLoader$(async ({ cookie }) => {
	const [snapshot, session] = await Promise.all([
		getCartSnapshot(cookie),
		getCustomerSession(cookie),
	]);
	return { snapshot, signedIn: !!session };
});

const updateItemRpc = server$(async function (
	this,
	itemId: string,
	quantity: number,
) {
	return await updateCartItem(this.cookie, itemId, quantity);
});

const removeItemRpc = server$(async function (this, itemId: string) {
	return await removeCartItem(this.cookie, itemId);
});

const applyCouponRpc = server$(async function (this, code: string) {
	return await applyCartCoupon(this.cookie, code);
});

const removeCouponRpc = server$(async function (this) {
	return await removeCartCoupon(this.cookie);
});

const clearCartRpc = server$(async function (this) {
	return await clearCart(this.cookie);
});

const startCheckoutRpc = server$(async function (this) {
	return await startCheckout(this.cookie, this.url.origin);
});

export default component$(() => {
	const data = useCart();
	const cart = useSignal<CartSnapshot | null>(data.value.snapshot);
	const couponCode = useSignal("");
	const error = useSignal<string | null>(null);
	const busy = useSignal(false);

	const apply = $(
		async (
			result: Promise<
				{ ok: true; snapshot: CartSnapshot } | { ok: false; error: string }
			>,
		) => {
			busy.value = true;
			error.value = null;
			const res = await result;
			busy.value = false;
			if (res.ok) cart.value = res.snapshot;
			else error.value = res.error;
		},
	);

	const checkout = $(async () => {
		busy.value = true;
		error.value = null;
		const res = await startCheckoutRpc();
		busy.value = false;
		if (res.ok) {
			window.location.href = res.url;
		} else {
			error.value = res.error;
		}
	});

	const snapshot = cart.value;
	const items = snapshot?.items ?? [];

	return (
		<>
			<SiteHeader signedIn={data.value.signedIn} cartCount={snapshot?.itemCount ?? 0} />
			<main>
				<section class="biab-section biab-section--narrow">
					<div class="biab-section__lead">
						<span class="biab-section__eyebrow">Checkout</span>
						<h2 class="biab-section__title">Your cart</h2>
					</div>

					{items.length === 0 ? (
						<div class="biab-empty">
							Your cart is empty. <a href="/store">Browse the store →</a>
						</div>
					) : (
						<div class="biab-card" style="padding: 2rem; display: flex; flex-direction: column; gap: 1.25rem;">
							{items.map((item) => (
								<div
									key={item.id}
									style="display: flex; gap: 1rem; align-items: center; border-bottom: 1px solid var(--border); padding-bottom: 1rem;"
								>
									{item.productImage ? (
										<img
											alt={item.productName ?? "Item"}
											src={item.productImage}
											style="width: 64px; height: 64px; border-radius: 0.5rem; object-fit: cover;"
										/>
									) : null}
									<div style="flex: 1;">
										<div style="font-weight: 600; color: var(--title);">
											{item.productName ?? "Item"}
										</div>
										{item.variantTitle ? (
											<div style="color: var(--text-muted); font-size: 0.85rem;">
												{item.variantTitle}
											</div>
										) : null}
										<div style="color: var(--accent); font-weight: 600;">
											{formatMoney(item.subtotal, item.currency)}
										</div>
									</div>
									<div style="display: flex; align-items: center; gap: 0.5rem;">
										<button
											aria-label="Decrease quantity"
											class="slot-button"
											disabled={busy.value}
											onClick$={() =>
												apply(updateItemRpc(item.id, item.quantity - 1))
											}
											type="button"
										>
											−
										</button>
										<span style="min-width: 1.5rem; text-align: center;">
											{item.quantity}
										</span>
										<button
											aria-label="Increase quantity"
											class="slot-button"
											disabled={busy.value}
											onClick$={() =>
												apply(updateItemRpc(item.id, item.quantity + 1))
											}
											type="button"
										>
											+
										</button>
										<button
											class="biab-btn biab-btn--ghost"
											disabled={busy.value}
											onClick$={() => apply(removeItemRpc(item.id))}
											type="button"
										>
											Remove
										</button>
									</div>
								</div>
							))}

							<div style="display: flex; gap: 0.5rem; align-items: flex-end;">
								<div style="flex: 1;">
									<label class="biab-label" for="coupon">
										Coupon
									</label>
									<input
										bind:value={couponCode}
										class="biab-input"
										id="coupon"
										placeholder={snapshot?.couponCode ?? "Code"}
									/>
								</div>
								{snapshot?.couponCode ? (
									<button
										class="biab-btn biab-btn--ghost"
										disabled={busy.value}
										onClick$={() => apply(removeCouponRpc())}
										type="button"
									>
										Remove coupon
									</button>
								) : (
									<button
										class="biab-btn biab-btn--ghost"
										disabled={busy.value || !couponCode.value}
										onClick$={() => apply(applyCouponRpc(couponCode.value))}
										type="button"
									>
										Apply
									</button>
								)}
							</div>

							<div style="display: flex; justify-content: space-between; align-items: center; padding-top: 0.5rem;">
								<button
									class="biab-btn biab-btn--ghost"
									disabled={busy.value}
									onClick$={() => apply(clearCartRpc())}
									type="button"
								>
									Clear cart
								</button>
								<div style="font-size: 1.15rem; font-weight: 700; color: var(--title);">
									{snapshot
										? formatMoney(snapshot.subtotal, snapshot.currency)
										: ""}
								</div>
							</div>

							<button
								class="biab-btn"
								disabled={busy.value}
								onClick$={checkout}
								type="button"
							>
								{busy.value ? "Working…" : "Checkout with Stripe"}
							</button>

							{error.value ? (
								<div style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem;">
									{error.value}
								</div>
							) : null}
						</div>
					)}
				</section>
			</main>
			<Footer />
		</>
	);
});

export const head: DocumentHead = {
	title: "Cart — Your Business",
	meta: [{ name: "description", content: "Your shopping cart." }],
};

// Svelte/src/routes/store/cart/+page.svelte
<script lang="ts">
	import Header from '$lib/components/biab/Header.svelte';
	import Footer from '$lib/components/biab/Footer.svelte';
	import StoreNav from '$lib/components/biab/StoreNav.svelte';
	import type { CartSnapshot } from '@businessdash/sdk/contracts';
	import {
		applyCoupon,
		clearCart,
		formatDollars,
		removeCartItem,
		removeCoupon,
		startCheckout,
		updateCartItem,
		type CartCallResult,
	} from '$lib/biab/cart-client';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	// Seed from the server-loaded cart, then mutate in place after each
	// add/update/remove. Intentionally a one-time snapshot of `data`.
	// svelte-ignore state_referenced_locally
	let snapshot = $state<CartSnapshot | null>(data.snapshot);
	let busy = $state(false);
	let error = $state<string | null>(null);
	let couponCode = $state('');

	const currency = $derived(snapshot?.currency ?? 'USD');
	const cartCount = $derived(snapshot?.itemCount ?? 0);

	function apply(result: CartCallResult) {
		if (result.ok) {
			snapshot = result.snapshot;
			error = null;
		} else {
			error = result.error;
		}
	}

	async function withBusy(fn: () => Promise<CartCallResult>) {
		busy = true;
		apply(await fn());
		busy = false;
	}

	async function checkout() {
		busy = true;
		error = null;
		const res = await startCheckout();
		busy = false;
		if (res.ok) {
			window.location.href = res.url;
		} else {
			error = res.error;
		}
	}
</script>

<svelte:head><title>Cart</title></svelte:head>

<Header />
<StoreNav {cartCount} />

<main class="biab-section biab-section--narrow">
	<div class="biab-section__lead">
		<span class="biab-section__eyebrow">Checkout</span>
		<h1 class="biab-section__title">Your cart</h1>
	</div>

	{#if !data.configured}
		<div class="biab-empty">Store isn't connected.</div>
	{:else if !snapshot || snapshot.items.length === 0}
		<div class="biab-empty">
			Your cart is empty. <a href="/store">Browse products →</a>
		</div>
	{:else}
		<div class="biab-card cart">
			{#each snapshot.items as item (item.id)}
				<div class="cart-row">
					{#if item.productImage}
						<img class="cart-row__img" src={item.productImage} alt={item.productName ?? ''} />
					{/if}
					<div class="cart-row__main">
						<strong>{item.productName ?? 'Item'}</strong>
						{#if item.variantTitle}
							<span class="cart-row__variant">{item.variantTitle}</span>
						{/if}
						<span class="cart-row__unit">{formatDollars(item.unitPrice, currency)} ea</span>
					</div>
					<div class="cart-row__qty">
						<input
							class="biab-input"
							type="number"
							min="0"
							max="999"
							value={item.quantity}
							onchange={(e) =>
								withBusy(() =>
									updateCartItem(item.id, Number(e.currentTarget.value)),
								)}
							style="width: 4.5rem;"
							disabled={busy}
						/>
						<button
							class="cart-row__remove"
							onclick={() => withBusy(() => removeCartItem(item.id))}
							disabled={busy}
							aria-label="Remove item"
						>
							Remove
						</button>
					</div>
					<div class="cart-row__subtotal">{formatDollars(item.subtotal, currency)}</div>
				</div>
			{/each}

			<div class="cart-coupon">
				{#if snapshot.couponCode}
					<span class="biab-badge">Coupon: {snapshot.couponCode}</span>
					<button
						class="biab-btn biab-btn--ghost"
						onclick={() => withBusy(removeCoupon)}
						disabled={busy}
					>
						Remove coupon
					</button>
				{:else}
					<input
						class="biab-input"
						placeholder="Coupon code"
						bind:value={couponCode}
						style="max-width: 12rem;"
					/>
					<button
						class="biab-btn biab-btn--ghost"
						onclick={() => couponCode && withBusy(() => applyCoupon(couponCode))}
						disabled={busy || !couponCode}
					>
						Apply
					</button>
				{/if}
			</div>

			<div class="cart-total">
				<span>Subtotal</span>
				<strong>{formatDollars(snapshot.subtotal, currency)}</strong>
			</div>

			<div class="cart-actions">
				<button class="biab-btn biab-btn--ghost" onclick={() => withBusy(clearCart)} disabled={busy}>
					Clear cart
				</button>
				<button class="biab-btn" onclick={checkout} disabled={busy}>
					{busy ? 'Working…' : 'Checkout'}
				</button>
			</div>
		</div>
	{/if}

	{#if error}
		<div
			style="color: var(--danger); background: var(--danger-bg); padding: 0.75rem 1rem; border-radius: 0.5rem; font-size: 0.9rem; margin-top: 1rem;"
		>
			{error}
		</div>
	{/if}
</main>

<Footer />

<style>
	.cart {
		padding: 1.5rem 2rem;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}
	.cart-row {
		display: grid;
		grid-template-columns: auto 1fr auto auto;
		align-items: center;
		gap: 1rem;
		padding-bottom: 1rem;
		border-bottom: 1px solid var(--border);
	}
	.cart-row__img {
		width: 3.5rem;
		height: 3.5rem;
		object-fit: cover;
		border-radius: 0.5rem;
	}
	.cart-row__main {
		display: flex;
		flex-direction: column;
		gap: 0.15rem;
	}
	.cart-row__variant,
	.cart-row__unit {
		color: var(--text-muted);
		font-size: 0.82rem;
	}
	.cart-row__qty {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}
	.cart-row__remove {
		background: none;
		border: none;
		color: var(--danger);
		font-size: 0.8rem;
		text-decoration: underline;
	}
	.cart-row__subtotal {
		font-weight: 700;
		min-width: 5rem;
		text-align: right;
	}
	.cart-coupon {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		flex-wrap: wrap;
	}
	.cart-total {
		display: flex;
		justify-content: space-between;
		align-items: center;
		font-size: 1.1rem;
		padding-top: 0.5rem;
		border-top: 1px solid var(--border);
	}
	.cart-actions {
		display: flex;
		justify-content: flex-end;
		gap: 0.75rem;
	}
</style>
